kubernetes-sigs/gcp-compute-persistent-disk-csi-driver

CONTRIBUTING.md, LICENSE, OWNERS, README.md, SECURITY_CONTACTS, code-of-conduct.md
Added required initialization files.
=> Repository initialization

deploy/setup-project.sh
=> Reduced IAM Policy Role scope to minimal storageAdmin role

test/remote/remote/remote.go, test/run-tests.sh
See title. Also amended tests to clean up instances when done
=> Remove failing test artifact GET and added some descriptive test titles

OWNERS
=> Add Google sig-storage team to Reviewers

Makefile
Fixes https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/60
=> Fix Makefile prod-build-container arguments

deploy/gcp-compute-persistent-disk-csi-driver-custom-role.yaml
Lol I forgot this one. Its sort of important
=> Add detach disk permissions to custom role

pkg/gce-pd-csi-driver/node.go
Part of #95 but not a full solution.
Follow-up PR coming that will check the mount points for compatibility
=> Don't fail when NodePublish or NodeStage on same target path multipletimes, idempotency

Makefile
=> Makefile clarification for staging image, error if not set

Dockerfile, deploy/kubernetes/dev/node.yaml, pkg/mount-manager/device-utils.go
=> Fix so that udevadm can be run from inside kubernetes container on the host

pkg/common/utils.go, pkg/common/utils_test.go, pkg/gce-pd-csi-driver/node.go, test/remote/instance.go
=> Change NodeID to be fully qualified name

Makefile, README.md, deploy/kubernetes/dev/controller.yaml, deploy/kubernetes/dev/node.yaml, deploy/kubernetes/stable/controller.yaml, deploy/kubernetes/stable/node.yaml
/hold
until release cut, image pushed, blog post ready.
for preliminary review
=> Promote driver version to v0.2.0.beta

deploy/kubernetes/overlays/prow-gke-head/README.md, deploy/kubernetes/overlays/prow-gke-head/controller_images.yaml, deploy/kubernetes/overlays/prow-gke-head/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-head/node_images.yaml, deploy/kubernetes/overlays/prow-gke-staging/README.md, deploy/kubernetes/overlays/prow-gke-staging/controller_images.yaml, deploy/kubernetes/overlays/prow-gke-staging/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-staging/node_images.yaml, test/k8s-integration/main.go, test/run-k8s-integration.sh
Also add option to not build the driver from source
=> Add gke prow config

deploy/kubernetes/base/node.yaml
=> Add preStop hook to remove registration sockets when driver registrar node container goes down

README.md, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
=> Update stable images to official releases

deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
=> Remove hardcoded environment variables from spec

test/e2e/utils/utils.go
If you have multiple periodic jobs that have similar timing, and not enough projects available, then the slightly later job will always fail instead of waiting for a project to get freed up.
=> Add retry for acquiring a boskos resource

deploy/kubernetes/base/setup-cluster.yaml
This PR adds back the cluster role for external snapshotter
=> Add the cluster role for snapshotter

test/e2e/utils/utils.go
=> fix retry logic

README.md, cmd/main.go, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, examples/kubernetes/demo-defaultsnapshotclass.yaml, examples/kubernetes/demo-regional-sc.yaml, examples/kubernetes/demo-zonal-sc.yaml, pkg/common/constants.go
Fixes: #157 
/assign @msau42 @saad-ali
=> Change driver name and topology key to finalized name (conforms to CSI v1.0.0)

deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/dev/controller_images.yaml, deploy/kubernetes/overlays/dev/node_images.yaml, deploy/kubernetes/overlays/prow-head-template/node_images.yaml, deploy/kubernetes/overlays/stable/controller_images.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, deploy/kubernetes/overlays/stable/node_images.yaml
Make it so that `base != stable`, this makes versioning crystal clear
=> Strict Kustomize Patching

Gopkg.lock, Gopkg.toml, vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
=> Bump to CSI Spec to v1.0.0

deploy/kubernetes/base/setup-cluster.yaml
=> Added explicit cluster roles for external csi components because system roles deprecated

Dockerfile
some security patches or something
=> Bump builder and Debian base versions

deploy/kubernetes/base/node.yaml
=> Simplify socket directory

deploy/kubernetes/overlays/prow-head-template/controller_images.yaml, deploy/kubernetes/overlays/prow-head-template/node_images.yaml
=> Update Prow Head Template

deploy/kubernetes/overlays/prow-gke-staging/controller_images.yaml, deploy/kubernetes/overlays/prow-gke-staging/node_images.yaml
/hold
until external container v1.0.0 is tagged
and GCE PD CSI Driver v0.3.0 is tagged
=> Update staging PROW config to newest staging containers

test/k8s-integration/main.go
The test naming has changed
Fixes: #146
=> fix test focus

deploy/kubernetes/overlays/dev/node_images.yaml, deploy/kubernetes/overlays/prow-gke-staging/node_images.yaml, deploy/kubernetes/overlays/prow-head-template/node_images.yaml, deploy/kubernetes/overlays/stable/node_images.yaml
To fix the spec versioning issue
=> Bump Driver Registrar to v1.0.1

Makefile, README.md, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/overlays/dev/controller_images.yaml, deploy/kubernetes/overlays/dev/node_images.yaml, deploy/kubernetes/overlays/prow-gke-staging/node_images.yaml, deploy/kubernetes/overlays/prow-head-template/controller_images.yaml, deploy/kubernetes/overlays/prow-head-template/node_images.yaml, deploy/kubernetes/overlays/stable/controller_images.yaml, deploy/kubernetes/overlays/stable/node_images.yaml, test/k8s-integration/main.go
=> Cherrypick various configuration and docs fixes to 0.3.0 release branch

pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go
=> Cherrypick of #198: Fail CreateVolume() when Block volume capability is requested

deploy/kubernetes/overlays/prow-gke-staging/controller_images.yaml, deploy/kubernetes/overlays/prow-gke-staging/node_images.yaml
=> Bump PROW GKE Staging images to v0.3.1

deploy/kubernetes/overlays/dev/controller_images.yaml, deploy/kubernetes/overlays/dev/node_images.yaml, deploy/kubernetes/overlays/prow-gke-head/node_images.yaml, deploy/kubernetes/overlays/prow-head-template/controller_images.yaml, deploy/kubernetes/overlays/prow-head-template/node_images.yaml, deploy/kubernetes/overlays/stable/controller_images.yaml, deploy/kubernetes/overlays/stable/node_images.yaml
/cc @verult 
/hold
until prod images pushed
=> [cherrypick] Bump image versions for prod and tests

test/e2e/tests/multi_zone_e2e_test.go, test/e2e/tests/setup_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go, test/remote/instance.go, test/run-e2e.sh
go test has default timeout of 10m, bumping to 20m
/assign @saad-ali @msau42
=> Bump E2E go test timeout to 20m

README.md
Adding the comments in snapshot example for installing the driver in dev
version.
=> Update snapshot example doc

test/e2e/tests/multi_zone_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go
see title
/cc @saad-ali @jingxu97 @verult
=> Bump RePD disk size for tests to new 200Gb minimum

deploy/kubernetes/overlays/prow-gke-staging/controller_images.yaml, deploy/kubernetes/overlays/prow-gke-staging/node_images.yaml
=> Bump staging images to v0.4.0-rc1

deploy/kubernetes/overlays/prow-gke-staging/controller_images.yaml, deploy/kubernetes/overlays/prow-gke-staging/node_images.yaml
=> Remove gke suffix from rc tag of image

deploy/kubernetes/deploy-driver.sh
Adding more verbose logging for debugging specific issue. Also never hurts to have more verbose logs probably.
=> Add debug logging to version and apply

Makefile, README.md, deploy/kubernetes/overlays/stable/controller_images.yaml, deploy/kubernetes/overlays/stable/node_images.yaml
Updating docs n stuff first. Then will immediately branch and tag.
=> Update docs and stable image to v0.4.0

README.md, deploy/kubernetes/dev/controller.yaml, deploy/kubernetes/stable/controller.yaml, deploy/kubernetes/stable/node.yaml, test/e2e/tests/multi_zone_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go
=> Update image locations to working ones

deploy/kubernetes/overlays/alpha/controller_add_snapshotter.yaml
=> Shapshotter to GKE Release version

deploy/kubernetes/overlays/dev/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml
I have no idea how pull jobs are passing
=> Fix stable image name

deploy/kubernetes/install-kustomize.sh
If existing/requested versions don't match, update kustomize.
=> Augment script to update Kustomize if version is incorrect

deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
=> Staging v1.1.0 versions of external CSI components

deploy/kubernetes/overlays/stable/kustomization.yaml
=> Bump stable sidecars to v1.1.0-gke.0

test/k8s-integration/main.go, test/run-k8s-integration-local.sh, test/run-k8s-integration.sh
Set feature gates ability in preparation for CSI Migration tests
=> Add feature gate setting & required test focus flag to integration tests

test/run-k8s-integration.sh
=> Make integration test kube version configurable

test/k8s-integration/config/test-config-template.in
=> Add supported filesystem types to k8s integration driver test config

Dockerfile, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/dev/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, test/k8s-integration/main.go, test/run-k8s-integration-local.sh
=> Fix Kustomize overlay dependencies so that Dev overlay replaces driver image successfully

deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
=> Bump CSI Provisioner to v1.1.1 for Migration Delete fix

deploy/kubernetes/overlays/stable/kustomization.yaml
/hold
Wait for 2 green runs of the staging testgrid
=> Release stable with csi-provisioner v1.1.1

deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
=> Bump Provisioner in staging to v1.2.0-rc1

deploy/kubernetes/overlays/stable/kustomization.yaml
=> Bump csi-provisioner to v1.2.0 for migration fixes

deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
=> Bump RC overlay to contain v0.5.0 of driver rc

Makefile, README.md, deploy/kubernetes/overlays/stable/kustomization.yaml
newest release version been cut, update deployment specs and docs.
/assign @msau42 @verult
=> Release v0.5.0 version as stable

deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, test/k8s-integration/main.go
Also added comments to make sure this doesn't happen again
=> Change pd image placeholder in integration tests to gke.gcr.io vanity url

deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
=> Update rc version in staging tests to validate new driver version

README.md, deploy/kubernetes/overlays/stable/kustomization.yaml
=> Release v0.5.1 of the driver as stable

deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
=> Add 0.6.0-rc1 to staging rc test overlay

README.md
=> Add table for all public test status'

test/k8s-integration/main.go
=> Give test binary the knowledge that the clusters we bring up are on cos image for test skipping

deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
/hold
until staging image is available
=> Bump external-provisioner version in staging

deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
/kind feature
```release-note
NONE
```
=> Bump attacher to 1.2.0 in rc

test/k8s-integration/main.go
Per #319, break up the PR into small ones. This first one adds some utilities that make the flag checking process more readable and uses a cleaner temp directory creation and deletion system.
```release-note
None
```
=> add flag checking and temp dir utilities

pkg/common/utils.go, pkg/common/utils_test.go
Flaky tests
@davidz627 @saad-ali 
```release-note
Fixed a bug that causes disks in the same zone/region to be provisioned serially
```
=> fix a bug where keys are not properly translated to volume id

test/k8s-integration/main.go
Too many logs.
/assign @msau42 @hantaowang 
/kind cleanup
```release-note
NONE
```
=> Decrease verbosity to 7 to avoid verbosity 8 REST request/response spew

README.md, deploy/kubernetes/overlays/stable/kustomization.yaml
/kind feature
```release-note
NONE
```
=> Bump PD version to v0.5.2-gke.0

test/run-k8s-integration.sh
/kind feature
Need to add a variable in the run script to toggle the region option added in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/394
Fixes #
```release-note
NONE
```
=> Add region env for run-k8s-integration.sh

deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
```release-note
NONE
```
/assign @davidz627 @msau42
=> Bumping sidecars to latest versions for 0.6.0 staging RC

test/k8s-integration/config/sc-standard.yaml
Now that we have regional cluster tests, we need to use delayed binding.
Fixes #
```release-note
NONE
```
=> Use delayed binding in k8s tests

docs/kubernetes/user-guides/basic.md, docs/kubernetes/user-guides/driver-install.md, docs/kubernetes/user-guides/pre-provisioned.md, examples/kubernetes/demo-pod.yaml
Fixes: #388 
```release-note
NONE
```
=> Add user guide for pre-provisioned volumes

test/k8s-integration/config/test-config-template.in, test/k8s-integration/driver-config.go, test/k8s-integration/main.go
/assign @msau42 @misterikkit
```release-note
NONE
```
=> Make driver test capabilities configurable and remove expansion from GKE tests

deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
Add resizer version to release staging to fix failing tests
```release-note
NONE
```
=> Add resizer to release staging deployments

Gopkg.lock, Gopkg.toml, vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
/kind cleanup
```release-note
NONE
```
=> Update CSI Spec to v1.2.0

deploy/kubernetes/base/node.yaml
/kind feature
/assign @msau42 @verult 
Fixes #416 
```release-note
Add a blanket toleration to the Node Daemonset of the driver deployment so that it can be deployed on all nodes
```
=> Add blanket tolerations to node daemonsets

test/k8s-integration/cluster.go, test/k8s-integration/cluster_test.go, test/k8s-integration/main.go
/assign @msau42 @misterikkit 
```release-note
NONE
```
=> [Cherry-pick] Add test skipping based on cluster version since some tests added are fixing bugs in never versions

pkg/mount-manager/fake-safe-mounter.go
Signed-off-by: zhucan <zhucan.k8s@gmail.com>
spelling errors
Fixes #426 
@davidz627 
```release-note
None
```
=> spelling errors

Dockerfile
/kind cleanup
Fixes #423 
```release-note
Update driver base image distro to debian-amd64:v2.0.0 and build with go v1.13.4
```
=> Update build golang version to 1.13.4 and image distro to debian-amd64:v2.0.0

docs/kubernetes/user-guides/driver-install.md
>
> /kind bug
> /kind design
> /kind flake
Updates the installation documentation for `gcp-compute-persistent-disk-csi-driver` in order to clarify where the directoy needs to be put on the local machine.
Fixes #440 
```release-note
Documentation update
```
=> #440 - Updating driver installation documentation

test/run-k8s-integration.sh
/kind feature
Part of: #306 
```release-note
NONE
```
=> Add image type env var option for k8s integration script

deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
/kind cleanup
The latest sidecars have a lot of new functionality/fixes that are very useful: metrics, migration fixes, verify volumes attached, switches to informers.
Fixes #
```release-note
NONE
```
=> Test out latest released sidecars

deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
/kind bug
```release-note
NONE
```
=> Pull resizer image from staging GKE GCR repo instead of prod for staging test overlay

docs/kubernetes/user-guides/driver-install.md
Fixes #389
Improve docs a little at a time
```release-note
NONE
```
=> Add required IAM permissions to driver installation guide

pkg/mount-manager/device-utils.go
/kind cleanup
```release-note
NONE
```
=> Improve error messaging around VerifyDevicePath and reduce stutter

README.md, deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml
/kind cleanup
```release-note
NONE
```
=> Make v0.6.2 latest released version in docs and deploy

test/e2e/tests/multi_zone_e2e_test.go
/kind bug
```release-note
NONE
```
=> Update RePD test to not fail silently

deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
/kind bug
```release-note
NONE
```
=> Fix prow-gke-release-staging-head image repo for resizer

CHANGELOG, README.md, deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml
=> Release driver v0.7.0

README.md, deploy/gcp-compute-persistent-disk-csi-driver-custom-role.yaml, deploy/kubernetes/delete-driver.sh, deploy/kubernetes/deploy-driver.sh
/kind cleanup
Updating driver name to be consistent with the latest guidance. Repo and image name remains unchanged.
```release-note
NONE
```
=> Updating driver name to be consistent with the latest guidance

Makefile, deploy/kubernetes/overlays/alpha/rbac_add_snapshotter.yaml, docs/kubernetes/user-guides/snapshots.md, examples/kubernetes/snapshot/default-volumesnapshotclass.yaml, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/node.go, pkg/mount-manager/device-utils.go, test/k8s-integration/cluster.go
Update the snapshot guide as some of example commands are outdated and have wrong filenames.
Fixes #
```release-note
NONE
```
=> Update snapshot guide

test/k8s-integration/config/test-config-template.in
/kind cleanup
Enable k8s stress tests added in https://github.com/kubernetes/kubernetes/pull/87998
Fixes #
```release-note
NONE
```
=> Enable k8s stress tests

deploy/kubernetes/overlays/prow-gke-release-staging-head/controller_add_snapshotter.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-head/rbac_add_snapshots_to_provisioner.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-head/rbac_add_snapshotter.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/controller_add_snapshotter.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/enable_sidecar_metrics.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/rbac_add_snapshots_to_provisioner.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/rbac_add_snapshotter.yaml
/kind feature
>
> /kind bug
> /kind design
> /kind flake
This PR enables csi snapshotter side car to GCE PD CSI driver.
Fixes #457 
This is part 1 of the change. This change only includes yaml changes.
The second PR would add option to include SnapshotClassFile in https://github.com/saikat-royc/gcp-compute-persistent-disk-csi-driver/blob/master/test/k8s-integration/driver-config.go#L11 and add SnapshotClass tag to the template file …
=> Enable csi snapshotter

deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-head/leader-election-flag.yaml
Verified driver installation manually
```release-note
NONE
```
/assign @saikat-royc @msau42 @saad-ali
=> update leader election flags for latest provisioner image in rc-head overlay

test/k8s-integration/cluster.go
>
> /kind bug
> /kind design
> /kind flake
Add autorepair options for GKE release channel
Fixes #
```release-note
Add autorepair options for GKE release channel
```
=> Add autorepair options for GKE release channel

OWNERS
```release-note
NONE
```
/assign @msau42 @saad-ali
=> Adding verult as repo approver

OWNERS
/kind cleanup
Matt and Saikat are owning pd driver going forward.
Fixes #
```release-note
NONE
```
=> Add mattcary and saikat-royc as owners

Makefile, hack/verify-all.sh, pkg/mount-manager/safe-mounter_windows.go
Add MountSensitive
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Add MountSensitive in CSIproxy mounter

docs/kubernetes/user-guides/basic.md
/kind bug
Fixes #578
```release-note
NONE
```
=> Document provisioner parameters, especially fstype

pkg/common/parameters.go, pkg/common/parameters_test.go, pkg/gce-cloud-provider/compute/cloud-disk.go, pkg/gce-pd-csi-driver/controller.go, test/e2e/tests/single_zone_e2e_test.go, test/k8s-integration/config/sc-balanced.yaml, test/k8s-integration/config/sc-ssd.yaml, test/k8s-integration/config/test-config-template.in, test/k8s-integration/driver-config.go, test/k8s-integration/driver.go, test/k8s-integration/filter-junit.go, test/k8s-integration/main.go, test/run-k8s-integration-ci.sh, test/run-k8s-integration-local.sh, test/run-k8s-integration.sh, test/run-windows-k8s-integration.sh
/kind feature
Add testing for the new balanced PD feature
```release-note
NONE
```
=> Test support for Balanced PDs

OWNERS
Add jingxu97 to owner file
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> Add jingxu97 to owner file

test/k8s-integration/filter-junit.go, test/k8s-integration/main.go
/kind bug
Fixes #592
```release-note
NONE
```
=> Do all storage class gingko runs and report errors at the end

deploy/kubernetes/base/controller/cluster_setup.yaml, deploy/kubernetes/images/alpha/image.yaml, test/k8s-integration/driver-config.go, test/k8s-integration/driver.go, test/k8s-integration/main.go, test/k8s-integration/prepull-image.sh, test/k8s-integration/prepull.yaml, test/run-windows-k8s-integration.sh
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> update driver test code for Windows

CHANGELOG/CHANGELOG-1.0.md, README.md
kind cleanup
Update docs to reflect upcoming v1.0.1 release.
Link will not work until release process is complete.
Fixes #
```release-note
None
```
=> Update docs for v1.0.1 release

CHANGELOG/CHANGELOG-1.0.md, README.md
kind cleanup
Cherry pick #599 to release-1.0
Fixes #
```release-note
None
```
=> Cherry-pick #599 to `release-1.0` (Update docs for 1.0.1 release)

test/k8s-integration/filter-junit.go
/kind bug
Fixes #605
```release-note
NONE
```
=> Remove duplicate junit results post-merge

test/run-k8s-integration-ci.sh
>
/kind bug
> /kind design
> /kind flake
This PR fixes a bug introduced in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/629
Fixes #
```release-note
Fix ci scipt focus string
```
=> Fix ci scipt focus string

test/run-k8s-integration-ci.sh
/kind bug
**What this PR does / why we need it**: Fixes regional test failures
Fixes #
```release-note
NONE
```
/assign @mattcary
=> k8s-integration: Add .yaml suffix to sc-regional storageclass

cmd/gce-pd-csi-driver/main.go, pkg/gce-pd-csi-driver/node_test.go, pkg/mount-manager/statter_linux.go, pkg/mount-manager/statter_windows.go, test/sanity/sanity_test.go
Instead of creating new csi proxy client, this PR uses existing one
created in safe mounter.
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> Use existing csi proxy client in Statter

test/run-k8s-integration-ci.sh
>
/kind bug
> /kind design
> /kind flake
Fixes #
Without this change, the node version was not getting picked up. hence CI runs were testing with same master and node version
```release-note
None
```
=> Fix node version check for node skew tests

deploy/kubernetes/install-kustomize.sh
Update kustomizer to 3.8.6 due to issue to download 3.8.0
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Update kustomizer to 3.8.6

deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Update staging RC to use new 1.1.0 RC build
```release-note
None
```
/assign @jingxu97 
=> Update staging RC to use new 1.1.0 RC build

test/k8s-integration/main.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Skip Pod fsgroupchange policy tests for < 1.20 k8s

README.md, deploy/kubernetes/base/node_windows/node.yaml
Add disk v1beta2 api group into node yaml file
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> Update csi proxy volume setup for new disk api group

CHANGELOG/CHANGELOG-1.2.md, README.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Add release notes for upcoming 1.2 release.

deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Update RC image for new RC Release: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/releases/tag/v1.2.0-rc1
Fixes #
```release-note
NONE
```
/assign @jingxu97
=> Update RC image for 1.2.0 RC

deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Cherrypick #675 from `master` to `release-1.2`:  Update RC image for 1.2.0 RC
Fixes #
```release-note
NONE
```
/assign @jingxu97
=> Cherrypick #675 from `master` to `release-1.2`

README.md, deploy/kubernetes/images/stable/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Update docs/stable overlay images to point to upcoming v1.2.0 release image (to be cut soon).
Fixes #
```release-note
NONE
```
/assign @jingxu97
=> Update docs/stable overlay images for 1.2 release

README.md, deploy/kubernetes/images/stable/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Cherrypick #677 from `master` to `release-1.2`: Update docs/stable overlay images for 1.2 release
Fixes #
```release-note
NONE
```
/assign @jingxu97
=> Cherrypick #677 from `master` to `release-1.2`

test/k8s-integration/cluster.go, test/k8s-integration/version_test.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Fix GKE cluster version check for cluster update

deploy/kubernetes/overlays/stable/kustomization.yaml
/kind bug
Fixes #687
```release-note
NONE
```
=> Use v0.7.0 image for release-0.7

test/k8s-integration/driver.go, test/k8s-integration/main.go
Add logs for Windows pod for debugging
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Add logs for Windows pod for debugging

test/k8s-integration/prepull.yaml
update prepull image version
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Update prepull image version

deploy/kubernetes/base/node_linux/node.yaml, deploy/kubernetes/base/node_windows/node.yaml
/kind bug
Fixes #34
```release-note
Do not run controller service in node.
```
=> Disable controller service on nodes

deploy/kubernetes/install-kustomize.sh
>
> /kind bug
> /kind design
> /kind flake
This is an immediate fix to failing internal prow jobs.
A more long term fix needs to be debated whether to pin a fixed version (and avoid update to the script) or use a latest version automatically.
Fixes #
```release-note
NONE
```
=> Fix the kustomize version

test/run-k8s-windows-migration.sh
add script for running pdcsi Windows migration
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Add pdcsi Windows migration test script

deploy/kubernetes/images/prow-gke-release-staging-rc-1-15/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-16/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Update prow staging overlays with 1.2.1 rc driver image

test/run-k8s-integration-ci.sh, test/run-k8s-integration-migration.sh, test/run-k8s-integration.sh, test/run-k8s-windows-migration.sh, test/run-windows-k8s-integration.sh
>
> /kind bug
kind cleanup
> /kind design
> /kind flake
Switch to kubetest2 for test infra.
Fixes #
```release-note
NONE
```
=> Switch to kubetest2.

test/k8s-integration/cluster.go, test/k8s-integration/main.go, test/run-k8s-integration-ci.sh
=> Remove duplication of k8sDir which caused --test_version to not be effective

test/k8s-integration/main.go
#746 was not quite correct.
/kind bug
Fixes #745
```release-note
None
```
=> use testDir correctly, and make its name more clear

test/run-k8s-integration-migration.sh
>
kind bug
> /kind design
> /kind flake
Same as https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/748 which missed a file.
Fixes #
```release-note
NONE
```
=> Fix migration test.

pkg/metrics/metrics.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Log component metric version

test/k8s-integration/main.go, test/run-k8s-integration-ci.sh, test/run-k8s-integration.sh
>
> /kind bug
> /kind design
/kind feature
> /kind flake
CSIMigrationGCE can be enabled in GKE Test env now. This PR will let us add Prow configs to run migration tests on GKE.
Fixes #
```release-note
NONE
```
=> Enable migration tests to run on GKE clusters.

test/run-k8s-integration-ci.sh, test/run-k8s-integration.sh
>
kind bug
> /kind design
> /kind flake
Migration on GKE tests failed because test focus is not quoted.
Fixes #
```release-note
NONE
```
=> Add single quotes around migration test focus.

test/k8s-integration/cluster.go, test/k8s-integration/main.go
/kind bug
Fixes #745
```release-note
None
```
=> Use --test-version correctly with kubetest2

Makefile
Add BUILDPLATFOMR build args in some linux build
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Fix build issue for Linux images

CHANGELOG/CHANGELOG-1.2.md
/kind feature
```release-note
None
```
/assign @cpanato
=> release notes for v1.2.2 patch release

CHANGELOG/CHANGELOG-1.2.md, pkg/metrics/metrics.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Cherrypick #757  to release-1.2
Fixes #
```release-note
NONE
```
=> Cherry-pick #757 to release-1.2

CHANGELOG/CHANGELOG-1.2.md
=> Changelog from 1.2.2 release

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml
Upgrade csi sidecar to the latest version except csi-snapshotter.
=> Update csi sidecar versions on staging rc

deploy/kubernetes/images/stable-master/image.yaml
Upgrade csi sidecar version to latest on stable-master
/release-note-none
/assign @mattcary
=> Update csi sidecar versions on stable

test/e2e/tests/single_zone_e2e_test.go
>
> /kind bug
> /kind design
> /kind flake
/kind feature
Add an e2e test for storage location param.
Fixes #
There are some duplicate code for snapshot testing. If we are adding anything new there we might want to extract common code as helper functions.
```release-note
NONE
```
=> Add e2e test for snapshot storage location parameter.

README.md
/assign @annapendleton
Clarify release process (for googlers only).
```release-note
None
```
=> add link to release doc

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
/kind cleanup
```release-note
None
```
=> stage v1.3.0-rc1

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
I neglected to update the image repo :-(
/kind bug
```release-note
None
```
=> fix image repo

test/k8s-integration/cluster.go
/kind bug
cherry-pick of #805 
```release-note
None
```
=> Fix kubectl parsing

README.md, deploy/kubernetes/images/stable-master/image.yaml
Cherry-pick of release-1.3 cut details./
kind cleanup
```release-note
None
```
=> release-1.3 cut details

CHANGELOG/CHANGELOG-1.3.md
Update changelog for v1.3.1 release.
```release-note
None
```
=> v1.3.1 changelog

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
/kind bug
```release-note
None
```
=> use stable-master image as base for prow-gke-release-staging-rc-master

Dockerfile
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
removed the symlink creation as it already exists in 1.9.0 (```failed to create symbolic link '/usr/sbin/rm': File exists```)
```release-note
Update debian base image to 1.9.0
```
=> Update debian base image to 1.9.0

CHANGELOG/CHANGELOG-1.0.md
=> 1.0.3 notes

CHANGELOG/CHANGELOG-1.0.md
=> v1.0.4 notes

Dockerfile
/kind bug
```release-note
Update debian images to buster-v1.9.0
```
=> Update debian images to buster-v1.9.0

CHANGELOG/CHANGELOG-1.2.md
=> changelog for v1.2.3

CHANGELOG/CHANGELOG-1.3.md
=> Changelog for 1.3.2

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
/kind cleanup
```release-note
None
```
=> Really correct staging image for 1.3.2-rc1

CHANGELOG/CHANGELOG-1.4.md
Release notes for upcoming 1.4.0 release
Fixes #
N/A
```release-note
NONE
```
=> Add changelog for release 1.4.0

Dockerfile.arm64
> /kind bug
This PR adds back in building an additional mad_hacks version then copying over scsi_id into the actual version. 
```release-note
NONE
```
=> add back in copy from mad-hack version for arm64

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
/kind cleanup
stage v1.4.0-rc2 as a step of v1.4.0 release
```release-note
None
```
=> stage v1.4.0-rc2

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
/kind cleanup
Cherry pick stage v1.4.0-rc2 #888 to release 1.4
```release-note
None
```
=> Cherry pick stage v1.4.0-rc2 #888 to release 1.4

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
/kind bug
Cherry pick  Fix repo #896 to release-1.4
Fixes #
```release-note
None
```
=> Cherry pick  Fix repo #896 to release-1.4

test/run-windows-k8s-integration.sh, test/run-windows-k8s-migration.sh
>
/kind bug
Add missing unbound variable teardown_driver in the `test/run-windows*` scripts
```release-note
NONE
```
/cc @jingxu97 @mattcary
=> Add missing unbound variable teardown_driver

README.md, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml, deploy/kubernetes/images/stable-master/image.yaml
/kind cleanup
Docs & overlays for v1.4.0 release
```release-note
None
```
=> v1.4.0 image and readme

CHANGELOG/CHANGELOG-1.3.md, Dockerfile
=> Bump buster version and make 1.3.5

CHANGELOG/CHANGELOG-1.2.md, Dockerfile
/kind cleanup
And update changelog for 1.2.5 release.
```release-note
None
```
=> Bump debian image for 1.2 release.

CHANGELOG/CHANGELOG-1.2.md, CHANGELOG/CHANGELOG-1.3.md
=> Pull v1.2.5 and v1.3.5 changelog to master

OWNERS
```release-note
None
```
/triage accepted
/kind cleanup
=> Remove verult from OWNERS files

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
/kind cleanup
```release-note
None
```
=> Promote release 1.4.0 to prow staging test

CHANGELOG/CHANGELOG-1.2.md
**What this PR does / why we need it**: Changelog for patch release 1.2.6
**Does this PR introduce a user-facing change?**: No
```release-note
NONE
```
=> Add changelog for 1.2.6

pkg/gce-pd-csi-driver/controller.go
/kind bug
Cherry-pick of #943
```release-note
Fix #942 that can cause attacher to think a disk has been attached even if the attach failed.
```
=> Return error when queued

CHANGELOG/CHANGELOG-1.4.md
**What this PR does / why we need it**: Changelog for patch release 1.4.1
**Does this PR introduce a user-facing change?**: No
```release-note
NONE
```
=> Add changelog for 1.4.1

pkg/gce-cloud-provider/compute/cloud-disk.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go, test/e2e/tests/single_zone_e2e_test.go, test/k8s-integration/config/image-volumesnapshotclass.yaml, test/k8s-integration/config/test-config-template.in, test/k8s-integration/driver-config.go, test/k8s-integration/main.go, test/run-k8s-integration-ci.sh, test/run-k8s-integration-local.sh, test/run-k8s-integration.sh, test/run-windows-k8s-integration.sh, test/run-windows-k8s-migration.sh
/kind bug
```release-note
Fix bug in original disk-image implementation that was fixed in test PR
```
=> Cherry-pick of #929

CHANGELOG/CHANGELOG-1.5.md
=> v1.5.1 release notes

test/run-k8s-integration-ci.sh
=> disable disk image testing to avoid timeout

CHANGELOG/CHANGELOG-1.6.md
Changelog for minor release 1.6.0
**Does this PR introduce a user-facing change?**: No
```release-note
NONE
```
=> Add Changelog for v1.6.0

test/k8s-integration/main.go
The original test skip from #883 was too broad
/assign @amacaskill 
> /kind flake
Fixes #
```release-note
```
=> only skip cloning tests, not all snapshot tests

manifest_osversion.sh
/kind cleanup
CI for Windows was recently broken, adding a debugging statement to check the contents of the manifest, ref https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/982
```release-note
NONE
```
=> Debugging statement to check the transformed manifest

deploy/kubernetes/images/stable-1-22/image.yaml, deploy/kubernetes/images/stable-1-23/image.yaml, deploy/kubernetes/overlays/stable-1-22/kustomization.yaml
/kind bug
> /kind design
> /kind flake
Fixes #992
```release-note
None
```
=> fix 1.22 and 1.23 image repositories

CHANGELOG/CHANGELOG-1.6.md
=> Cherry-pick release v1.6.0 changelog to master, with note about bug

CHANGELOG/CHANGELOG-1.6.md
=> Discourage 1.6 branch

deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
NONE
```
=> update prow rc image with 1.7.0-rc1 candidate

deploy/kubernetes/wait-for-driver.sh
Fixes #1006 
```release-note
None
```
=> increase deploy driver timeout

CHANGELOG/CHANGELOG-1.7.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
CHANGELOG for 1.7.1
```
=> add 1.7.1 changelog

README.md, deploy/kubernetes/images/stable-1-22/image.yaml, deploy/kubernetes/images/stable-1-23/image.yaml, deploy/kubernetes/images/stable-1-24/image.yaml, deploy/kubernetes/images/stable-master/image.yaml
/kind feature
What this PR does / why we need it:
Put 1.7.1 release into stable-master, and stable-1-22,1-23,1-24 .
```release-note
None
```
=> update overlays for 1.7.1

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
we are cutting 1.7.2 release
Fixes #
```release-note
NONE
```
=> update stable master and README reference to 1.7.2

CHANGELOG/README.md
/kind cleanup
```release-note
None
```
=> Point changelog to master branch

CHANGELOG/CHANGELOG-1.3.md
=> 1.3.8 changelog

Dockerfile.debug
/kind bug
```release-note
None
```
/assign @mauriciopoppe
=> Update debug dockerfile for go1.19

deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> update prow rc image with 1.8.0-rc1 candidate

test/k8s-integration/cluster.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
The last PR introduces the logic to enable the GKE service in e2e tests. However, the GKE service URL includes the prefix "https://" and suffix "/", which will fail the `gcloud services enable` command. This PR removes the URL prefix and suffix to fix the issue.
Fixes #
```release-note
NONE
```
=> Fix the "gcloud services enable" logic

test/k8s-integration/cluster.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
Seem like the Prow service account `gob-prow@gob-prow.iam.gserviceaccount.com` does not have the permission to run `gcloud services enable` command. Reverting all the related logic to unblock the test grid.
Fixes #
```release-note
NONE
```
=> Revert all the new service enable logic

pkg/gce-cloud-provider/compute/gce-compute.go
Cherry pick of #1050 on release-1.7.
#1050: list out regional PD in listDisk Call
```release-note
Fixed issue where Regional disks are repeatedly queued for re-attaching and consuming api quota
```
=> Automated cherry pick of #1050: list out regional PD in listDisk Call

Dockerfile, Dockerfile.Windows, Dockerfile.debug
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Update to go 1.19.4 to pick up fixes.
Fixes #
```release-note
Update to go 1.19.4
```
=> Update go version to the latest

Dockerfile, Dockerfile.Windows
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Update golang to 1.18.9 to pickup fixes.
Fixes #
```release-note
Update golang to 1.18.9
```
=> release-1.7: Update golang to 1.18.9

docs/kubernetes/development.md
The updated documentation includes all the subtleties required to get e2e tests running locally.
```release-note
None
```
=> Document edge cases for local e2e tests

CHANGELOG/CHANGELOG-1.8.md, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Update changelog and prow tag

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
The previous stable was 1.7.2 instead of 1.8.1. Is there a specific reason for this, or was it just not updated? Is it safe to update now?
```release-note
NONE
```
=> Update readme and stable image

pkg/gce-pd-csi-driver/controller.go
/kind cleanup
Should not print stack in production
Fixes #
```release-note
NONE
```
=> Remove debug.PrintStack()

deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
/kind cleanup
rc3 has more fixes: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/compare/master...release-1.9
Fixes #
```release-note
NONE
```
=> Use v1.9.0-rc3

CHANGELOG/CHANGELOG-1.9.md, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
rc4 has the up to date sidecar versions
Fixes #
Bake in https://k8s-testgrid.appspot.com/provider-gcp-compute-persistent-disk-csi-driver#Kubernetes%20Master%20Driver%20Latest%20Release%20Candidate
```release-note
None
```
=> Update rc image to v1.9.0-rc4

Dockerfile, Dockerfile.Windows, Dockerfile.debug
>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
go version updates
```
=> go version updates

pkg/common/parameters.go, pkg/common/utils.go, pkg/common/utils_test.go
/kind cleanup
Add more tests to clarify use case, clean up test format.
Fixes #
```release-note
NONE
```
=> Add more unit tests for hyperdisk feature

CHANGELOG/CHANGELOG-1.9.md, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Security updates and fixing multiarch build
Fixes #
Bake in https://k8s-testgrid.appspot.com/provider-gcp-compute-persistent-disk-csi-driver#Kubernetes%20Master%20Driver%20Latest%20Release%20Candidate
```release-note
NONE
```
=> Update rc image to 1.9.1-rc1

README.md, deploy/kubernetes/images/stable-master/image.yaml
/kind feature
Fixes #
Success run: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-gcp-compute-persistent-disk-csi-driver-release-staging-k8s-master-integration/1632839701293436928
```release-note
NONE
```
=> release-1.9 cut details for v1.9.1

README.md, deploy/kubernetes/images/stable-master/image.yaml
Put 1.9.2 release into stable-master. 
Test run in: https://k8s-testgrid.appspot.com/provider-gcp-compute-persistent-disk-csi-driver#Kubernetes%20Master%20Driver%20Latest%20Release%20Candidate
Fixes #
```release-note
NONE
```
=> release-1.9 cut details for v1.9.2

Dockerfile, go.mod
/kind cleanup
Update go version to match k/k 1.27: https://github.com/kubernetes/kubernetes/blob/master/.go-version
Fixes #
```release-note
Update go version to 1.20.2 for k/k 1.27
```
=> Update go version to 1.20

CHANGELOG/CHANGELOG-1.10.md, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Adds  changelog for 1.10 
```release-note
NONE
```
=> add changelog for 1.10

CHANGELOG/CHANGELOG-1.8.md, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Adds changelog for 1.8.3
Fixes #
```release-note
None
```
=> add changelog for 1.8.3

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Put 1.10.0 release into stable-master. Note this does not update [prow-stable-sidecar-rc-master/image.yaml](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/release-1.8/deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml) to match because there are ongoing patch releases that need to bake using this. 
Fixes # …
=> release-1.10 cut details for v1.10.0

CHANGELOG/CHANGELOG-1.7.md, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Adds changelog for 1.7.5 release 
Fixes #
```release-note
None
```
=> add changelog for 1.7.5

OWNERS
Add sunnylovestiramisu as approver
Fixes #
```release-note
NONE
```
=> Add sunnylovestiramisu as reviewer and approver

CHANGELOG/CHANGELOG-1.7.md, CHANGELOG/CHANGELOG-1.8.md, CHANGELOG/CHANGELOG-1.9.md
>
> /kind bug
> /kind design
> /kind flake
Add changelog for 1.9.3. Also fixes errors in 1.8 and 1.7 changelog that the PR author is incorrect for some changes. 
Fixes #
```release-note
None
```
=> Add changelog for 1.9.3

Dockerfile.Windows, Dockerfile.debug
/kind cleanup
Fixes #
```release-note
Update go version to 1.20.3 and base image url in Dockerfile.debug and windows
```
=> Update go version and base image url in Dockerfile.debug and windows

CHANGELOG/CHANGELOG-1.10.md, CHANGELOG/CHANGELOG-1.7.md, CHANGELOG/CHANGELOG-1.8.md, CHANGELOG/CHANGELOG-1.9.md, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Add changelog for 1.10.1, 1.9.4, 1.8.5, 1.7.7  for patch releases for cherry pick of [PR 1204](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1204) back to all release branches.
Fixes #
```release-note
None
```
=> Add changelog for 1.10.1, 1.9.4, 1.8.5, 1.7.7 

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Update docs and stable image to reference new release 1.10.1
Fixes #
```release-note
None
```
=> Update docs and stable image to reference new release 1.10.1

cmd/gce-pd-csi-driver/main.go, pkg/common/utils.go, pkg/common/utils_test.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/utils.go, pkg/gce-pd-csi-driver/utils_test.go, pkg/metrics/metrics.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
It adds an CSI server side error count metric for PDCSI and Hyperdisk volumes
Fixes #
```release-note
NONE
```
=> Add metrics for CSI server side error count

pkg/gce-pd-csi-driver/node.go
/kind bug
Fixes #1146
```release-note
Use correct file path for disable device
```
=> Eval symlinks for disable device call

CHANGELOG/CHANGELOG-1.9.md
=> 1.9.5 changelog

CHANGELOG/CHANGELOG-1.10.md
=> v1.10.2 release notes

Dockerfile
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Update debian base image to latest version to fix `CVE-2023-2650`.
Fixes #
```release-note
None
```
=> Update debian base image to latest version for CVE fixes

deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
```release-note
None
```
/assign @pwschuurman
=> Use v1.10.3 as RC

Dockerfile
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Address fixes for CVE-2023-29405, CVE-2023-29404, CVE-2023-29402, CVE-2023-24540, CVE-2023-24539, CVE-2023-29403, CVE-2023-29400
Fixes #
```release-note
Update go version to 1.20.5 to address CVE fixes
```
=> Update go version to 1.20.5 to address CVE fixes

Dockerfile.Windows
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
update Dockerfile.windows go version to 1.20.5
```
=> update Dockerfile.windows go version to 1.20.5

Dockerfile, Dockerfile.Windows
>
> /kind bug
kind cleanup
> /kind design
> /kind flake
Address CVE-2023-29404, CVE-2023-24540, CVE-2023-29405, CVE-2023-29402, CVE-2023-24538, CVE-2023-29400, CVE-2023-24539, CVE-2023-24536, CVE-2023-24534, CVE-2023-24537, CVE-2023-29403, CVE-2023-24532
Fixes #
```release-note
update go version to 1.19.10
```
=> [release-1.8] update go version to 1.19.10

Dockerfile.Windows
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
[release-1.10] Update Docker.Windows to 1.20.5
```
=> [release-1.10] Update Docker.Windows to 1.20.5

CHANGELOG/CHANGELOG-1.10.md
=> v1.10.3 release notes

CHANGELOG/CHANGELOG-1.10.md
Add changelog for 1.10.4
```release-note
None
```
=> Add Changelog for 1.10.4

CHANGELOG/CHANGELOG-1.7.md
Add changelog for 1.7.9
```release-note
None
```
=> Add Changelog for 1.7.9

cmd/gce-pd-csi-driver/main.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go, pkg/gce-pd-csi-driver/utils_linux.go, pkg/gce-pd-csi-driver/utils_windows.go, test/e2e/utils/utils.go
/kind bug
Cherry-pick #1294
```release-note
Add option for serializing formatAndMount, including fsck as well as mkfs.
```
=> Cherrypick #1294

CHANGELOG/CHANGELOG-1.7.md
Fixes #
```release-note
NONE
```
=> Add change log for v1.7.10

pkg/gce-pd-csi-driver/controller.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
We recently made a change to [Filter out GCE operation error codes caused by user errors ](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1261), but I found that this was only working for errors returned from DetachDisk, and not errors returned from AttachDisk. This is because when AttachDisk is called , it never calls LoggedError, and instead [returns an Internal error code](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk …
=> Always call LoggedError for errors returned from CloudProvider methods

OWNERS
Cherry pick of #1354 on release-1.7.
#1354: Add pwschuurman@ as reviewer/approver to
```release-note
NONE
```
=> Automated cherry pick of #1354: Add pwschuurman as reviewer/approver to

CHANGELOG/CHANGELOG-1.9.md
>
> /kind bug
> /kind design
> /kind flake
CHANGELOG was missing for [#972 ]
Fixes #
```release-note
NONE
```
=> Add missing CHANGELOG

Makefile, README.md
/kind feature
kops deploys this component and it fails on arm64 nodes
Fixes #
```release-note
build and publish arm64 images
```
=> Build and publish arm64 images

deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Update overlay to test latest 1.8 rc release

OWNERS
>
> /kind bug
> /kind design
> /kind flake
Add tyuchn to owner and reviewer list
Fixes #
```release-note
N/A
```
=> Add tyuchn to owner and reviewer list

CHANGELOG/CHANGLOG-1.12.MD, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
N/A
```
=> 1.12 CHANGELOG, update rc image

Dockerfile
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
N/A
```
=> Bump go version to 1.20.8 in release-1.7

Dockerfile
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
N/A
```
=> Bump go version to 1.20.8 in release-1.8

Dockerfile, Dockerfile.Windows, Dockerfile.debug
>
/kind cleanup
Fixes #
```release-note
N/A
```
=> Bump go version to 1.20.10

Dockerfile, Dockerfile.Windows, Dockerfile.debug
/kind bug
Bump Golang Builder version to 1.20.11
Fixes #
```release-note
Bump Golang Builder version to 1.20.11
```
=> Bump Golang Builder version to 1.20.11

go.mod, go.sum, vendor/google.golang.org/grpc/internal/transport/http2_server.go, vendor/google.golang.org/grpc/server.go, vendor/google.golang.org/grpc/version.go, vendor/modules.txt
/kind bug
Bump [google.golang.org/grpc](http://google.golang.org/grpc) from v1.56.2 to v1.56.3 to fix [CVE-2023-44487](https://github.com/advisories/GHSA-qppj-fm5r-hxr3).
Fixes #
```release-note
Bump google.golang.org/grpc from v1.56.2 to v1.56.3 to fix CVE-2023-44487.
```
=> Bump google.golang.org/grpc to fix CVE-2023-44487

pkg/gce-pd-csi-driver/controller.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Adds enable_storage_pools label to the OperationErrorMetric so we can track CSI operation error rates when storage pools is used. 
Fixes #
```release-note
Adds enable_storage_pools label to the OperationErrorMetric so we can track CSI operation error rates when storage pools is used. 
```
=> add enable_storage_pools label to OperationErrorMetric

Dockerfile, Dockerfile.Windows, Dockerfile.debug
/kind cleanup
Fixes #
```release-note
Update golang builder to 1.20.12
```
=> [release-1.12] Update golang builder to 1.20.12

CHANGELOG/CHANGELOG-1.10.md, CHANGELOG/CHANGELOG-1.11.md, CHANGELOG/CHANGELOG-1.12.md, CHANGELOG/CHANGELOG-1.7.md, CHANGELOG/CHANGELOG-1.9.md
For CVE-2023-48795
Fixes #
```release-note
NONE
```
=> Add changelog for 1.12.6, 1.11.8, 1.10.13, 1.9.15, 1.7.20

CHANGELOG/CHANGELOG-1.13.md, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
/kind test
```release-note
None
```
=> release 1.13 testing and changelog

README.md, deploy/kubernetes/images/stable-master/image.yaml
=> Release 1.13 doc and image update

CHANGELOG/CHANGELOG-1.12.md
=> Add changelog for 1.12.7

CHANGELOG/CHANGELOG-1.8.md, CHANGELOG/CHANGELOG-1.9.md
=> v1.9.16 and v1.8.19 Changelog

pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go
A manual cherry pick after a minor merge conflict.
/kind bug
```release-note
None
```
=> Cherry-pick #1558 to release-1.8

CHANGELOG/CHANGELOG-1.10.md, CHANGELOG/CHANGELOG-1.11.md, CHANGELOG/CHANGELOG-1.12.md, CHANGELOG/CHANGELOG-1.8.md, CHANGELOG/CHANGELOG-1.9.md
For recent releases
```release-note
None
```
/assign @pwschuurman
=> Changelog updates

CHANGELOG/CHANGELOG-1.13.md, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Change log update. 
Fixes #
```release-note
NONE
```
=> Add changelog for 1.13.1

README.md, deploy/kubernetes/images/stable-master/image.yaml
/kind feature
Put 1.13.1 release into stable-master. 
RC passing testgrid (visible google internal only): https://testgrid.k8s.io/provider-gcp-compute-persistent-disk-csi-driver#Kubernetes%20Master%20Driver%20Latest%20Release%20Candidate
```release-note
NONE
```
=> Update stable-master with v1.13.1

CHANGELOG/CHANGELOG-1.13.md, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Add 1.13.2 Changelog and update rc image to 1.13.2-rc1
Fixes #
```release-note
NONE
```
=> Add 1.13.2 Changelog, update rc image

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Put 1.13.2 release into stable-master
Fixes #
```release-note
NONE
```
=> release-1.13 cut details for 1.13.2

CHANGELOG/CHANGELOG-1.13.md, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Add 1.13.3 Changelog and update rc image to 1.13.3-rc1
Fixes #
```release-note
NONE
```
=> Add 1.13.3 Changelog, update rc image to v1.13.3-rc1

CHANGELOG/CHANGELOG-1.13.md
=> Update CHANGELOG-1.13.md for v1.13.4

README.md
>
> /kind bug
> /kind design
> /kind flake
Add link to Hyperdisk documentation for provisioned-throughput-on-create
Fixes #
```release-note
NONE
```
=> Add link to Hyperdisk documentation for provisioned-throughput-on-create

Dockerfile, initialize-driver.sh
>
/kind bug
> /kind design
> /kind flake
Updates the LVM configuration steps in the Dockerfile to support running in read only FS. To achieve this, it updates the entrypoint of the container.
Fixes #
```release-note
NONE 
```
=> Update docker file to get lvm configuration

Dockerfile, Dockerfile.Windows, Dockerfile.debug
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
fix CVE-2024-24790 , CVE-2024-24789
Fixes #
```release-note
Fix CVE-2024-24790 , CVE-2024-24789
```
=> Address CVE fixes for CVE-2024-24790 , CVE-2024-24789

Dockerfile, test/e2e/tests/single_zone_e2e_test.go
>
> /kind bug
Updates the go version to 1.22.4 to fix some CVEs and updates a test.
Fixes #
```release-note
Updates go version to 1.22.4 to fix some CVEs.
```
=> Fix Go CVEs and update flaky test

cmd/gce-pd-csi-driver/main.go, deploy/kubernetes/base/controller/cluster_setup.yaml, deploy/kubernetes/base/node_linux/node.yaml
>
> /kind bug
> /kind design
> /kind flake
Restricts the data caching to be setup only on node pools labelled for data cache
Fixes #
```release-note
NONE
```
=> Restrict data caching setup to labelled node pool

go.mod, go.sum, vendor/github.com/emicklei/go-restful/.gitignore, vendor/github.com/emicklei/go-restful/.travis.yml, vendor/github.com/emicklei/go-restful/CHANGES.md, vendor/github.com/emicklei/go-restful/Makefile, vendor/github.com/emicklei/go-restful/README.md, vendor/github.com/emicklei/go-restful/container.go, vendor/github.com/emicklei/go-restful/cors_filter.go, vendor/github.com/emicklei/go-restful/curly.go, vendor/github.com/emicklei/go-restful/custom_verb.go, vendor/github.com/emicklei/go-restful/jsr311.go, vendor/github.com/emicklei/go-restful/parameter.go, vendor/github.com/emicklei/go-restful/path_processor.go, vendor/github.com/emicklei/go-restful/request.go, vendor/github.com/emicklei/go-restful/response.go, vendor/github.com/emicklei/go-restful/route.go, vendor/github.com/emicklei/go-restful/route_builder.go, vendor/github.com/emicklei/go-restful/route_reader.go, vendor/github.com/emicklei/go-restful/service_error.go, vendor/github.com/emicklei/go-restful/web_service.go, vendor/k8s.io/mount-utils/mount_linux.go, vendor/modules.txt
>
> /kind bug
> /kind design
> /kind flake
Bump up library version to `github.com/emicklei/go-restful: v2.16.0+incompatible` to fix CVE-2022-1996. This also needed a vendor update which modified a bunch of files.
Fixes #
```release-note
NONE
```
=> Bump library version to fix CVE-2022-1996

cmd/gce-pd-csi-driver/main.go, pkg/common/constants.go, pkg/common/parameters.go, pkg/gce-pd-csi-driver/cache.go, test/e2e/utils/utils.go
>
/kind bug
The Cache size wasn't correctly parsed during LVM caching setup 
Fixes #
```release-note
NONE
```
=> Fix cachesize parsing and setup logic

deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Update prow stable rc master image to v1.15.0-rc1

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This PR bumps the latest stable image from v1.13.2 to v1.15.0.
Fixes #
```release-note
None
```
=> Upgrade latest stable image from v1.13.2 to v1.15.0

Dockerfile
>
/kind bug
> /kind design
> /kind flake
To fix hack/verify-docker-deps.sh stuck at `make validate-container-linux-arm64` step `RUN /print-missing-deps.sh`
Fixes #
```release-note
NONE
```
=> Update base image to bookworm-v1.0.4-gke.2

deploy/kubernetes/overlays/prow-stable-sidecar-rc-master/driver-args.yaml, deploy/kubernetes/overlays/prow-stable-sidecar-rc-master/kustomization.yaml, test/k8s-integration/config/sc-balanced-no-labels.yaml, test/k8s-integration/main.go, test/run-k8s-integration-ci.sh, test/run-k8s-integration.sh
>
> /kind bug
> /kind design
> /kind flake
This PR modifies the run-k8s-integration-ci.sh script to fix the test focuses and machine types when running modify_volume tests.
Fixes #
A run of the failing tests can be seen [here](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-gcp-compute-persistent-disk-csi-driver-release-staging-k8s-master-integration/1836730271865507840). …
=> Fix ci tests

CHANGELOG/CHANGELOG-1.14.md
=> Add CHANGELOG-1.14 for v1.14.0

deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> 1.15.2 update rc image

deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> 1.15.2-rc2 update rc image

deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
None
```
=> Update release candidate image to 1.15.2-rc3

deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
prow test soak with the latest release candidate
Fixes #
```release-note
None
```
=> update prow rc with 1.15.3-rc1 release candidate

deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Make a new release candidate with 1.15.3
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Update prow rc candidate prow jobs to use v1.15.3-rc2
Fixes #
```release-note
None
```
=> create new rc for 1.15.3

CHANGELOG/CHANGELOG-1.15.md, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
NONE
```
=> 1.15.4 CHANGELOG, update rc image 

deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
>
Point test to the new v1.16.0-rc1 version.
Fixes #
```release-note
NONE
```
=> Update RC image for 1.16.

Dockerfile
>
/kind bug
> /kind design
> /kind flake
Fix CVE-2024-0727  and CVE-2023-5678 
Fixes #
```release-note
None
```
=> Bump base image version to bookworm-v1.0.4-gke.3

Dockerfile, Dockerfile.debug
>
/kind bug
> /kind design
> /kind flake
Bumps up debian image to fix CVE-2025-0395
Fixes #
Bumps up debian image to fix CVE-2025-0395
```release-note
Bump up debian base image to fix CVE-2025-0395
```
=> update debian image to fix CVE

pkg/common/constants.go, pkg/common/utils.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go
/kind bug
Fixes # https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/1819
```release-note
Add Attach Limit for Hyperdisk + Gen4 VMs
```
/assign @mattcary
=> Add Attach Limit for Hyperdisk + Gen4 VMs

OWNERS
>
According to [go/gke-stateful-repo-reviewer-approver-process](http://goto.google.com/gke-stateful-repo-reviewer-approver-process), add myself to reviewers list.
Fixes #
```release-note
NONE
```
=> Add tonyzhc to owners.

pkg/gce-pd-csi-driver/controller.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> Clean up unused func pickRandAndConsecutive

test/k8s-integration/cluster.go
>
> /kind bug
> /kind design
> /kind flake
Tests on the extended channel are currently failing because "No valid versions with the prefix "1.28" found".  Those are no longer available outside of the extended channel.  Thus, I reasoned that the extended channel variable was not being set.
When I looked in the clusterUp golang logic, I found logic that wouldn't set the release channel if a version was specified.  There is now a special case for the extended channel. …
=> Set cluster version on the extended channel

pkg/gce-pd-csi-driver/cache.go
>
> /kind bug
> /kind design
> /kind flake
remove no-op log statement in reduceVolumeGroup for master branch.
Fixes #
```release-note
NONE
```
=> remove no-op log statement in reduceVolumeGroup for master branch.

OWNERS
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
According to [go/gke-stateful-repo-reviewer-approver-process](http://goto.google.com/gke-stateful-repo-reviewer-approver-process), add myself to reviewers list.
Fixes #
```release-note
None
```
=> Update OWNERS to include juliankatz

deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml, deploy/kubernetes/images/stable-master/image.yaml
>
/kind cleanup
Upgrade image tags to latest for each container in our prow tests. The goal of these tests is to test the latest upstream versions against the latest pdcsi driver version. 
Fixes #
```release-note
None
```
=> Upgrade images

pkg/gce-pd-csi-driver/node_test.go
/kind cleanup
Add more test coverage.
Fixes #
```release-note
NONE
```
=> Add Gen4 Lssd VM Test
