kubernetes-sigs/gcp-compute-persistent-disk-csi-driver

deploy/kubernetes/README.md, deploy/kubernetes/delete-driver.sh, deploy/kubernetes/deploy-driver.sh, deploy/setup-project.sh, test/run-tests.sh
Added some cleanup to project setup scripts, corrected role and added TODO for IAM scope reduction.
Feel free to use updated scripts for yourself too
=> Fixed project setup scripts

deploy/kubernetes/delete-driver.sh, deploy/kubernetes/deploy-driver.sh
=> Make deploy scripts use absolute paths instead of relative paths

Dockerfile, Makefile, cmd/main.go, deploy/kubernetes/delete-driver.sh, deploy/kubernetes/deploy-driver.sh, pkg/gce-cloud-provider/fake-gce.go, pkg/gce-cloud-provider/gce-compute.go, pkg/gce-csi-driver/controller.go, pkg/gce-csi-driver/controller_test.go, pkg/gce-csi-driver/gce-driver.go, pkg/gce-csi-driver/node.go, test/e2e/gce_pd_e2e_test.go, test/remote/remote/e2e.go, test/remote/remote/ssh.go, test/remote/run_remote/run_remote.go, test/run-tests.sh, test/sanity/sanity_test.go
=> E2E Testing Framework Changes for PROW Pre-Submits

deploy/setup-project.sh
Stops project creation from failing when file doesn't exist, or service account doesn't exist.
Expand service account roles as necessary for functionality of driver.
=> Improve setup-project.sh to be more robust

hack/update-gofmt.sh, hack/verify-all.sh, hack/verify-gofmt.sh, hack/verify-govet.sh, pkg/gce-csi-driver/controller_test.go, pkg/gce-csi-driver/identity.go, test/remote/run_remote/run_remote.go
Fixes #33
Add some simple go verification scripts like gofmt and govet.
Entrypoint is `hack/verify-all`. More verification scripts can be added later
test-infra change: https://github.com/kubernetes/test-infra/pull/8500
/assign @msau42 @krzyzacy
=> Simple go verification scripts

pkg/gce-cloud-provider/fake-gce.go, pkg/gce-cloud-provider/gce-compute.go, pkg/gce-cloud-provider/gce.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go
Fixes: #43 
There is an issue where Attach and the Attach Op can return success/DONE but the volume may not actually be attached to the instance. This PR adds an extra check where we poll the disk object for the instances it is attached to before returning success.
=> Added a waitforattach verification at the end of ControllerPublishVolume

Dockerfile
=> Changed base image to audited Debian Base

pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, test/run-unit.sh
Part 1 of: #49 
Part 2 will be adding run-unit.sh to the test-infra config
=> Add unit test runner script. Fixed some errors caught by unit tests

test/remote/remote/ssh.go, test/remote/run_remote/run_remote.go
This might help #42 
It seems like the e2e test is throwing too many errors when trying to bring up the instance.
=> Lessen severity of waiting loop errors to warnings

test/remote/run_remote/run_remote.go
Fixes: #42 
Trying to fix the flake. Got a couple theories, gonna try them out
=> Fix for E2E test Flake

Dockerfile, Makefile, cmd/main.go, pkg/gce-cloud-provider/gce.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, pkg/gce-pd-csi-driver/identity.go, pkg/gce-pd-csi-driver/identity_test.go, test/e2e/gce_pd_e2e_test.go, test/run-e2e-local.sh, test/sanity/sanity_test.go
Added unit tests. In the process found out the GetPluginInfo was missing vendor version so it was fixed to return the vendor version now.
vendor version is: The version of the driver as declared by the vendor (driver author)
so it makes sense to be a const and not a flag
Fixes: #47
=> Added unit tests for identity server, fixed small spec inconsistency

pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/gce-pd-driver_test.go, pkg/gce-pd-csi-driver/identity_test.go, test/e2e/gce_pd_e2e_test.go
=> Added controller unit tests

Makefile, deploy/kubernetes/controller.yaml, deploy/kubernetes/node.yaml, pkg/gce-pd-csi-driver/controller_test.go
=> Changed deploy yamls to prod version of container

deploy/gcp-compute-persistent-disk-csi-driver-custom-role.yaml, deploy/setup-project.sh
Have the `setup-project.sh` script remove old policy bindings so that they can be recreated successfully.
Part of: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/73
=> Remove old policy bindings so that setup-project is reentrant

test/e2e/tests/multi_zone_e2e_test.go, test/e2e/tests/setup_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/utils/utils.go, test/remote/archiver.go, test/remote/client-wrappers.go, test/remote/instance.go, test/remote/runner.go, test/remote/setup-teardown.go, test/remote/ssh.go
=> Refactored remote test framework for easy usage. Added teardown methods

README.md
Improved formatting.
Fixed the Parameters table, the `|` symbol was overloaded and cause table formatting issues.
=> Minor Docs Fixes

pkg/gce-pd-csi-driver/controller.go
No need to support FS Type parameter, it is already supported as a first class field in CSI through volume capabilities.
This PR just removes the TODO
Fixes: #93 
=> Don't FS Type Parameter

test/e2e/tests/multi_zone_e2e_test.go, test/e2e/tests/setup_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go, test/remote/instance.go, test/remote/setup-teardown.go
=> Test contexts are now initialized once on startup in parallel instead of per-test, Chose a better boot disk image. 

pkg/common/utils.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/node.go, pkg/mount-manager/device-utils.go, test/run-e2e-local.sh
=> Resolve disk name collisions for attached regional disks

Makefile, README.md, deploy/kubernetes/dev/controller.yaml, deploy/kubernetes/dev/node.yaml, examples/kubernetes/demo-regional-sc.yaml, examples/kubernetes/demo-zonal-sc.yaml
Fixes: #116 
Fixes: #92 
Turns on Kubelet Registration which is required for interop with Kubernetes 1.12+
=> Bump CSI External Components to v0.3.0+ and turn on Kubelet Registration

.dockerignore, .gitignore, Makefile, pkg/gce-pd-csi-driver/controller.go, test/e2e/utils/utils.go, test/k8s-integration/.dockerized-kube-version-defs, test/k8s-integration/main.go, test/run-e2e-local.sh, test/run-k8s-integration-local.sh, test/run-k8s-integration.sh
Fixes: #22
This PR adds a full integration test framework. It is ready for review.
Couple WIP items:
/kind feature
=> Adding Kubernetes Integration Test Framework

pkg/common/constants.go, pkg/gce-pd-csi-driver/node.go
Fixes: #83 
Tested with Kubernetes and it works.
The deployment yamls used:
https://gist.github.com/davidz627/ae1d3071913eda1f6dacfe59779073cf
=> Support partitions in VolumeAttributes

cmd/main.go, pkg/common/constants.go, pkg/common/utils.go, pkg/gce-cloud-provider/compute/cloud-disk.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/gce-pd-driver_test.go, test/e2e/tests/single_zone_e2e_test.go, test/sanity/sanity_test.go
When using Kubernetes does migration it may not have access to zone or region of the disk when translating to CSI. This is because k8s GCE PD object uniquely (sort of) identifies disks by PD Name only. We need to support this functionality so in case of an unspecified zone the driver will try to find out where it is by querying all zones.
In the case that the same PD Name is defined in multiple zones, the behavior is undefined. This is consistent with behavior inside Kubernetes and so is sufficient for Migration.
The driver name must also be a well-known name.
/cc @saad-ali
=> Support UNSPECIFIED zone and project in volume ID. Static driver name. To prep for migration

README.md, deploy/kubernetes/dev/controller.yaml, deploy/kubernetes/dev/node.yaml, deploy/kubernetes/dev/setup-cluster.yaml, examples/kubernetes/demo-defaultsnapshotclass.yaml, examples/kubernetes/demo-restore-snapshot.yaml, examples/kubernetes/demo-snapshot.yaml
Add the snapshotter deployment support and example
=> Add snapshot deployment support

pkg/gce-cloud-provider/compute/cloud-disk.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go
This PR adds the logic to pass the snapshot source when creating the
volume so that volume can be restored from snapshot if specified.
=> Pass snapshot source when creating volumes

Makefile, README.md, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/overlays/dev/controller_images.yaml, deploy/kubernetes/overlays/dev/node_images.yaml, deploy/kubernetes/overlays/stable/controller_images.yaml, deploy/kubernetes/overlays/stable/node_images.yaml
/hold
until https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/172 goes in and soaks for a while
and release images are cut for all external components and GCE PD Driver
=> v0.3.0 Release Docs and YAML updates

deploy/kubernetes/base/node.yaml
Kubernetes/kubernetes PR #70494 changed the kubelet plugin watcher
directory from #70494 `{kubelet_root_dir}/plugins/` to
`{kubelet_root_dir}/plugins_registry/`. This PR fixes the deployment
manifests for the GCE PD CSI Driver.
=> Fix kubelet socket path

deploy/kubernetes/base/node.yaml
Kubernetes/kubernetes PR #70494 changed the kubelet plugin watcher
directory from #70494 `{kubelet_root_dir}/plugins/` to
`{kubelet_root_dir}/plugins_registry/`. This PR fixes the deployment
manifests for the GCE PD CSI Driver.
=> [Cherry-Pick] Fix kubelet socket path

test/k8s-integration/main.go
Prow will pick up the test logs and parse them and make them available.
Also enable block tests now that the feature is beta.
=> Pass ARTIFACTS to k8s e2e

deploy/kubernetes/overlays/dev/controller_images.yaml, deploy/kubernetes/overlays/dev/node_images.yaml, deploy/kubernetes/overlays/prow-gke-head/node_images.yaml, deploy/kubernetes/overlays/prow-head-template/controller_images.yaml, deploy/kubernetes/overlays/prow-head-template/node_images.yaml, deploy/kubernetes/overlays/stable/controller_images.yaml, deploy/kubernetes/overlays/stable/node_images.yaml
/cc @verult 
should be cherrypicked to release-0.3.0 branch
=> Bump image versions for prod and tests

test/remote/instance.go
Technically we already do a `GET` before the insert, but looks like its possible that someone may insert a firewall rule in between or something and its possible to get an insert error.
=> Don't fail firewall rule insert if rule already exists

deploy/common.sh, deploy/kubernetes/delete-driver.sh, deploy/kubernetes/deploy-driver.sh, test/k8s-integration/main.go, test/run-k8s-integration.sh
=> Use bundled tar kubectl for integration tests. Add log verbosity args.

pkg/gce-cloud-provider/metadata/fake.go, pkg/gce-cloud-provider/metadata/metadata.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go, test/e2e/tests/single_zone_e2e_test.go
Fixed: [#19](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/19)
Get volume limits by sending HTTP request to Google metadata server
Tested for several different machine types. But don't know how to integrate it into the current e2e test, and don't know if it is necessary.
@davidz627 @msau42
=> Set MaxVolumesPerNode in NodeGetInfo

pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go
Fixes issue #48 
The test cases cover valid and invalid arguments, but don't know how to test internal errors.
=> Add unit test for Node

pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go, pkg/gce-pd-csi-driver/utils.go, pkg/gce-pd-csi-driver/utils_test.go
Fixes: #94
```release-note
BREAKING CHANGE: The driver now enforces AccessMode validation for all calls, supported access modes are SINGLE_NODE_WRITER, SINGLE_NODE_READER_ONLY, MULTI_NODE_READER_ONLY
```
=> Statically validate volume capabilities for CreateVolume, ControllerPublish, NodeStage, NodePublish

test/k8s-integration/config/sc-standard.yaml, test/k8s-integration/config/test-config-template.in, test/k8s-integration/driver-config.go, test/k8s-integration/main.go, test/run-k8s-integration-local.sh, test/run-k8s-integration.sh
=> Use K8s external-storage test framework

test/run-k8s-integration.sh
So that we can run a k8s 1.13 test with 0.4 version of the driver
=> [Cherry-pick] Make integration test kube version configurable

.gitignore, test/k8s-integration/main.go, test/run-k8s-integration-migration-local.sh, test/run-k8s-integration-migration.sh
Depends on: https://github.com/kubernetes/kubernetes/pull/77101
Adds a test config and local test config for CSI Migration testing. Brings up a cluster with migration flags, gce provider and zone, then runs the test with the `storage.migratedPlugins` flag. This will run all in-tree gcepd driver tests with the Migrated driver.
=> Add test config for testing CSI Migration with PD Driver

test/run-k8s-integration-migration.sh
Pre-provisioned tests hardcode some things to do with volume source and therefore are failing for migration for now. We should reennable them after figuring out whats going on there.
=> Only run Dynamic Provisioning tests for migration for now

test/run-k8s-integration-migration-local.sh, test/run-k8s-integration-migration.sh
Added all reasonable PD tests to the migration test set.
I've added TODO's for the remaining tests as more investigation is required. Those tests are not failing because of the PD driver, there is something going on in the tests themselves which tries to create a PV with an invalid spec so I would prefer not to muddy our "signal" for now.
=> Expand test focus of migration tests

Gopkg.lock, cmd/main.go, pkg/gce-cloud-provider/compute/gce.go, pkg/gce-cloud-provider/compute/token_source.go, vendor/gopkg.in/gcfg.v1/LICENSE, vendor/gopkg.in/gcfg.v1/doc.go, vendor/gopkg.in/gcfg.v1/errors.go, vendor/gopkg.in/gcfg.v1/read.go, vendor/gopkg.in/gcfg.v1/scanner/errors.go, vendor/gopkg.in/gcfg.v1/scanner/scanner.go, vendor/gopkg.in/gcfg.v1/set.go, vendor/gopkg.in/gcfg.v1/token/position.go, vendor/gopkg.in/gcfg.v1/token/serialize.go, vendor/gopkg.in/gcfg.v1/token/token.go, vendor/gopkg.in/gcfg.v1/types/bool.go, vendor/gopkg.in/gcfg.v1/types/doc.go, vendor/gopkg.in/gcfg.v1/types/enum.go, vendor/gopkg.in/gcfg.v1/types/int.go, vendor/gopkg.in/gcfg.v1/types/scan.go, vendor/gopkg.in/warnings.v0/LICENSE, vendor/gopkg.in/warnings.v0/warnings.go
This PR introduces parsing logic for GCE cloud config file. In particular, it extracts information for:
* An AltTokenSource for authenticating with GCP
* ID of the project in which the driver runs.
In adding token source integration, I used the following as reference:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/gce/gce.go
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/gce/token_source.go
/assign @davidz627 @mikedanese
=> Integration with GCE cloud config

deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/alpha/controller_add_snapshotter.yaml, deploy/kubernetes/overlays/dev/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml
gcr.io/gke-releases is only available in the US, while gke.gcr.io is available in multiple regions.
/assign @davidz627 
/cc @msau42
=> Updating image paths to gke.gcr.io

pkg/gce-pd-csi-driver/utils.go, pkg/gce-pd-csi-driver/utils_test.go
Needs to be cherry-picked to release-0.5.0 and new release version to be cut.
Also we should identify why none of the tests specify more than one access mode...
=> Remove cross validation of access modes, multiple access modes can be specified that represent all the capabilities of the volume

test/k8s-integration/main.go, test/run-k8s-integration-local.sh, test/run-k8s-integration.sh
Adds the following flags to `k8s-integration-test`:
- `deployment-strategy`: If a cluster needs to be booted up, choose if it is done on GCE through the `kube-ip.sh` script or GKE through the `gcloud` utility. The GKE option is incompatible with the migration test and must use a cluster version supported by GKE. Feature gates cannot be turned on when GKE is used. The default value is "gce", and GKE can be turned on by setting it to "gke".
- `gke-cluster-version`: If GKE is used, this flag can be set to an available cluster version, which can be checked with `gcloud container get-server-config`. Also accepted values are "latest" and "stable". The deault value is "latest".
=> add ability to use gcloud to boot a gke cluster for e2e integration

pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/utils.go, pkg/gce-pd-csi-driver/utils_test.go, test/k8s-integration/config/test-config-template.in
Fixes: #64 
Add support for Raw Block devices.
Enable the external driver tests for block.
=> Add support for raw block devices and enable block device tests on external k8s testing

README.md, deploy/kubernetes/overlays/stable/kustomization.yaml
=> Release v0.5.1 of the driver as stable

Gopkg.lock, Gopkg.toml, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, test/sanity/sanity_test.go, vendor/github.com/kubernetes-csi/csi-test/.travis.yml, vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/cleanup.go, vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/controller.go, vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/identity.go, vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/node.go, vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/sanity.go, vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/tests.go, vendor/github.com/kubernetes-csi/csi-test/release-tools/LICENSE, vendor/github.com/kubernetes-csi/csi-test/utils/grpcutil.go
/kind bug
/kind cleanup
Bumps CSI Sanity to newest version. Fixes some CreateVolume validation to check for snapshot existence.
/assign @msau42 @jingxu97 
```release-note
CreateVolume will now fail with NOT_FOUND error when VolumeContentSource SnapshotId does not refer to a snapshot that can be found
```
=> Update CSI Sanity to v2.0.1 and fix compatibility errors

pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go, pkg/mount-manager/fake-safe-mounter.go
An alternate approach to #302, but just returns an error if it finds that another operation with that volume ID already exists.
=> return an error if the volume ID already in use

test/k8s-integration/main.go, test/run-k8s-integration-local.sh, test/run-k8s-integration.sh
allows the user to boot a specific cluster version on gke when running integration tests
```release-note
NONE
```
=> Cherry-Pick: GKE Integration Support into Release-0.5.X

test/k8s-integration/main.go, test/run-k8s-integration-local.sh, test/run-k8s-integration.sh
Reverts kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#314
Accidentally merged unfinished work.
/assign @hantaowang @msau42 
```release-note
NONE
```
=> Revert "Cherry-Pick: GKE Integration Support into Release-0.5.X"

deploy/kubernetes/overlays/stable/kustomization.yaml
/kind feature
Pick up changes in v1.2.0 attacher
https://github.com/kubernetes-csi/external-attacher/releases/tag/v1.2.0
```release-note
Bump csi-attacher to v1.2.0 and csi-provisioner to v1.2.1 picking up support for inline volume migration and some fixes for backward compatible access modes for migration
```
=> Bump attacher to v1.2.0 to stable and provisioner v1.2.1

deploy/kubernetes/install-kustomize.sh
/kind bug
```release-note
Driver deployment script now replaces temporary Kustomize binary if it is not the correct pinned version
```
=> Cherry pick change to check installed kustomize version and replace with pinned version

test/k8s-integration/main.go, test/run-k8s-integration-local.sh, test/run-k8s-integration.sh
Per #319, break up the PR into small ones. This one builds onto #322 and adds the test-version flag. It also separates k8s building and cluster booting, so that you can boot a cluster without having to build k8s. The rules for how flags can be used together is defined here:
- test-version is used to determine the k8s version to test with. 
- kube-version and gke-cluster-version is used to determine the cluster version to boot, depeonding on the deployment strategy.
- local-k8s-dir points to a rebuilt kubernetes directory. If this flag is set, then neither kube-version nor test-version should be because the local version is used for both cluster and tests.
- if using GKE: either set (gke-cluster-version and test-version) or (gke-cluster-version and local-k8s-dir)
- if using GCE: either set …
=> Separate test k8s

test/k8s-integration/main.go
I accidentally removed the function call in the integration tests that actually runs all the tests. This brings it back.
```release-note
None
```
=> bring back the handle call

hack/update-gofmt.sh
=> update gofmt to not search unnecessary places and report files changed

test/run-k8s-integration-migration-local.sh, test/run-k8s-integration-migration.sh
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/323/files
added new flags for the test framework. This PR updates to use those flags for the migration tests.
/assign @msau42 @hantaowang 
```release-note
NONE
```
=> Use new deployment strategy and version flags for k8s integration migration tests

pkg/common/utils.go, pkg/common/volume_lock.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, pkg/gce-pd-csi-driver/gce-pd-driver_test.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go, pkg/mount-manager/fake-safe-mounter.go, test/sanity/sanity_test.go
Per Issue [307](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/307) using logic similar to #303 
Fixes: #307 
```release-note
Operations in the controller driver on a volume already being operated on now return an error.
```
=> Add volume level serialization for controller operations

Gopkg.lock, README.md, deploy/kubernetes/overlays/alpha/controller_add_resizer.yaml, deploy/kubernetes/overlays/alpha/kustomization.yaml, deploy/kubernetes/overlays/alpha/rbac_add_resizer.yaml, docs/kubernetes/user-guides/resize.md, pkg/gce-cloud-provider/compute/cloud-disk.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, pkg/gce-pd-csi-driver/identity.go, pkg/gce-pd-csi-driver/identity_test.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go.orig, pkg/mount-manager/fake-safe-mounter.go, test/e2e/tests/multi_zone_e2e_test.go, test/e2e/tests/resize_e2e_test.go, test/e2e/utils/utils.go, test/remote/client-wrappers.go, vendor/k8s.io/kubernetes/pkg/util/resizefs/resizefs_linux.go, vendor/k8s.io/kubernetes/pkg/util/resizefs/resizefs_unsupported.go
/kind feature
Fixes #227
/cc @gnufied
```release-note
Adds support for ControllerExpandVolume and NodeExpandVolume
```
=> Add support for Resize (Expand Volume) on the driver

README.md, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, test/e2e/tests/single_zone_e2e_test.go, test/remote/client-wrappers.go
/kind cleanup
For `Id -> ID` see: https://github.com/golang/go/wiki/CodeReviewComments#initialisms
Fixes a bunch of random lint errors because its late and I don't want to think but I'm waiting for a ride.
```release-note
NONE
```
=> LOW PRIORITY Fix random lint errors

test/run-k8s-integration-migration.sh
Allow migration tests to do resize through CSI.
```release-note
NONE
```
=> Enable ExpandCSIVolumes feature flag on migration tests to test migration path of resize

test/k8s-integration/driver.go, test/k8s-integration/main.go
On some tests, containers are still creating after 10 seconds but we move right onto running the test. Also, builds Ginkgo in the test directory.
```release-note
None
```
=> increase wait time until driver is deployed and build ginkgo

test/k8s-integration/main.go
When booting the cluster on GKE, we use a seprate k8s build that only builds the e2e tests and ginkgo. However this does not require docker, so its just build without using docker and thus the output location is different from a docker build (`_output/bin` vs `_output/dockerized/bin/linux/amd64`). Before this fix, the integration test always looks for ginkgo at `_output/dockerized/bin/linux/amd64` which causes it to not be able to find it.
This must be cherry-picked along with all GKE integration test support into release-0.5.X per #337 
```release-note
None
```
=> update the bin path if not using docker to build for test k8s

test/k8s-integration/main.go
Is this too many logs? Maybe. But also it would help with my current debugging...
```release-note
NONE
```
=> Update the test runner to spit out logs at level 10 for debuggability

test/k8s-integration/cluster.go, test/k8s-integration/main.go, test/run-k8s-integration-local.sh, test/run-k8s-integration-migration-local.sh, test/run-k8s-integration-migration.sh, test/run-k8s-integration.sh
/kind flake
For some reason some migration tests get skipped every once in a while because "number of nodes is not enough" when it only needs 2. For some reason the "num-nodes" variable in the e2e binary that's supposed to be dynamically gathered is showing `-1` (indicating failure to dynamically get the read/schedulable nodes from api server sometimes) so to solve I provide the num nodes flag every time.
I'm currently looking into why the e2e binary is not auto-setting this variable sometimes but that might be a larger fix
/cc @hantaowang 
```release-note
NONE
```
=> Add forced variable num-nodes so that we can give it to kubetest to force tests to run that have high node requirements

test/k8s-integration/config/test-config-template.in
Fixes: #263
/kind cleanup
```release-note
NONE
```
=> Add SupportedMountOptions to external pd test config to start mount options tests

test/k8s-integration/main.go, test/run-k8s-integration-local.sh, test/run-k8s-integration-migration-local.sh
/kind cleanup
/assign @msau42 @hantaowang 
Alright this should just fix a bunch of stuff. Once it's done and stable I think there are a bunch of flags we can probably remove that were put in to work around the fact we weren't using kubetest :(
```release-note
NONE
```
=> Migrate to k8s integration tests to kubetest

test/run-k8s-integration-migration.sh
I'm pretty sure with the `kubetest` change and some other fixes i've been working on most of the in-line volume tests will start to go green.
Time to activate them all.
/cc @ddebroy @leakingtapan 
/kind cleanup
```release-note
NONE
```
=> Activate ALL in-tree GCE PD tests for Migration (modulo disruptive/serial/other skipped on purpose tests)

test/k8s-integration/main.go
/assign @hantaowang 
/cc @msau42 
```release-note
NONE
```
=> Run tests from always existing kubernetes directory that contains the tests, not the gce build k8s directory

test/k8s-integration/cluster.go
Increases the default machine type for GKe to be the same as GCE: n1-standard-2
Drivers are sometimes not able to schedule on the node with the controller due to insufficient CPU. This causes flaky tests on GKE clusters. 
@davidz627 @jingxu97 
```release-note
None
```
=> increase node size for gke

test/k8s-integration/cluster.go
I made a mistake in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/353 and this fixes it.
Fixes #
```release-note
None
```
=> move gke create machine type from GKE down to GKE up

test/k8s-integration/cluster.go
Hopefully fixes flakes for 0.5.1 on gke 
Fixes #
@davidz627 @jingxu97 
```release-note
None
```
=> increase node size for 0.5.1 on gke

test/k8s-integration/cluster.go, test/k8s-integration/main.go
Our new testing framework kubetest does not work out of the box with GKE.
Fixes #
/assign @davidz627 @jingxu97 
```release-note
None
```
=> add functionality to use gke with kubetest

pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go, test/e2e/tests/single_zone_e2e_test.go
Parent: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/361
/assign @jsafrane @msau42 
```release-note
Reduces node attach limits by 1 since the node boot disk is considered an attachable disk
```
=> [Cherry-Pick] Amend volume limits returned by the driver to documented-1 since node boot disk is attachable disk

test/k8s-integration/main.go
We previous had a PR to export the kubectl path https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/352 that was closed in favor of another PR https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/358, but oddly the kubectl path fix was never actually included in that second PR. This adds the fix.
Fixes #
```release-note
None
```
=> Export kubectl path to test

Gopkg.lock, Gopkg.toml, pkg/common/utils.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/node.go, test/sanity/sanity_test.go, vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/cleanup.go, vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/controller.go, vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/identity.go, vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/node.go, vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/sanity.go, vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/util.go
Fixes: #367 
/assign @msau42 @jsafrane 
/cc @jingxu97 
/kind bug
/kind cleanup
```release-note
ControllerUnpublishVolume now returns success when the Node is GCE API NotFound.
Invalid format VolumeID is now GRPC InvalidArgument error instead of GRPC NotFound.
Underspecified disks not found in any zone now return GRPC NotFound.
```
=> Wrap all GRPC errors in status, fix semantics of NotFound errors

deploy/kubernetes/overlays/stable/kustomization.yaml
/kind bug
Hope this might actually fix some flakes in the tests :)
```release-note
Updated CSI Attacher to v1.2.1 to stop ignoring errors from ControllerUnpublish
```
=> Update csi-attacher to v.1.2.1 for fix to not ignore ControllerUnpublishErrors

docs/kubernetes/user-guides/basic.md
AFAIK the closest thing currently to a list of StorageClass parameters is the list of CreateVolume parameters. k8s users may not understand CSI lingo, so it's nice to explicitly call out StorageClass parameters separately.
```release-note
NONE
```
=> Adding k8s-specific documentation around storageclass fields

test/k8s-integration/cluster.go, test/k8s-integration/config/test-config-template.in, test/k8s-integration/main.go
/kind feature
Adds an option to bringup GKE regional clusters
Part of #261
```release-note
NONE
```
=> Add gke regional cluster support to k8s-integration test

test/k8s-integration/config/test-config-template.in
Because of change: https://github.com/kubernetes/kubernetes/pull/78306
```release-note
NONE
```
=> Add Supported size range to driver info config

test/k8s-integration/main.go
=> Bypass unmaintained hack/e2e.go for kubetest binary

README.md, deploy/kubernetes/overlays/stable/kustomization.yaml
Sidecar images are available in gcr.io/gke-release.
```release-note
NONE
```
/assign @davidz627 @msau42
=> Bumping all images to latest versions for 0.6.0 stable release

deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/base/setup-cluster.yaml, deploy/kubernetes/overlays/alpha/kustomization.yaml, deploy/kubernetes/overlays/alpha/rbac_add_resizer.yaml, deploy/kubernetes/overlays/alpha/rbac_add_snapshotter.yaml
/kind cleanup
**Which issue(s) this PR fixes**: 
Fixes #373
Prefix follows the convention established by controller and node deployment names.
```release-note
BREAKING CHANGE: All deployment objects in setup-cluster.yaml have been renamed. When deleting the deployment using ./delete-driver.sh, make sure to use specs from your previous deployment version to ensure the correct objects are cleaned up.
```
=> Prefix object names to disambiguate with other CSI drivers

pkg/gce-cloud-provider/compute/cloud-disk.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce.go, test/e2e/tests/multi_zone_e2e_test.go, test/e2e/tests/setup_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go, test/remote/instance.go
Could probably refactor out `CloudDisk` as well as that was an artifact of having different objects of disks from different APIs. We could probably also consolidate a lot of the zonal/regional codepaths now that we don't need to use entirely different compute APIs.
However, I've refrained from making large changes here in the interest of stability. Also I think theres a possibility we'd need to use different APIs again in the future so I've left the option for that open.
Fixes: #213 
/kind cleanup
```release-note
NONE
```
=> Move all RePD compute API calls to v1 from v1beta

cmd/main.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/identity.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/utils.go, pkg/mount-manager/device-utils.go
/kind cleanup
Fixes: #309 
```release-note
Improve driver logs to log success in all paths as well as logging additional useful information
```
=> Clean up all logging for the driver, log successes in all cases

test/k8s-integration/cluster.go, test/k8s-integration/cluster_test.go, test/k8s-integration/main.go
=> Add test skipping based on cluster version since some tests added are fixing bugs in newer versions

Gopkg.lock, Gopkg.toml, deploy/kubernetes/overlays/dev/kustomization.yaml, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, test/e2e/tests/single_zone_e2e_test.go, test/remote/client-wrappers.go, test/remote/instance.go, vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/controller.go, vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/sanity.go
/kind feature
```release-note
Adds LIST_VOLUMES and LIST_VOLUMES_PUBLISHED_NODES capabilities with respective functionality
```
=> Add ListVolumes with PublishedNodes

deploy/kubernetes/overlays/alpha/controller_add_snapshotter.yaml
/kind bug
Should we bump versions in previous releases too?
Fixes #432 
```release-note
Bump external-snapshotter version to v1.2.2 for fix of CVE-2019-11255
```
=> Bump snapshotter to v1.2.2 for CVE fix

deploy/kubernetes/overlays/alpha/controller_add_resizer.yaml, deploy/kubernetes/overlays/alpha/controller_add_snapshotter.yaml
… https://groups.google.com/g/kubernetes-security-announce/c/aXiYN0q4uIw
/kind bug
Fixes #432 
/cc @verult 
```release-note
Bump external-snapshotter to v1.2.2 and external-resizer to v0.3.0 to pick up fixes for CVE CVE-2019-11255
```
=> Bump versions of external-resizer and external-snapshotter for CVE fix

deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
/kind bug
/cc @saad-ali @hilliao
Fixes #421 
```release-note
Changed deployment of Controller and Node components to use hostNetwork for compatibility with GKE Workload Identity
```
=> Enable hostNetwork for workload identity

deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
/kind bug
/cc @saad-ali
#421 
```release-note
Changed deployment of Controller and Node components to use hostNetwork for compatibility with GKE Workload Identity
```
=> [Cherry-pick] Deploy driver with hostNetwork to fix interaction with GKE Workload Identity

deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml
Use the public canary quay images until we redo our CI pipeline for latest testing
Fixes #
```release-note
NONE
```
=> Use canary quay images to test latest sidecars

deploy/kubernetes/base/setup-cluster.yaml
/kind feature
In case of a cluster with `PodSecurityPolicies` enabled using kustomization base will not be enough to deploy `csi-gce-pd-node` and we have to also create the psp resource with local manifests. This PR is adding the missing psp that we used to deploy `csi-gce-pd-node`.
Since `podsecuritypolicy` is a kube resource available to all clusters regardless if the feature is enabled or not this will not impact users that do not use policies.
Users that patch psps locally will have to drop their patches and use the base, others shall not be affected.
```release-note
remove existing local podsecuritypolicies manifests for `csi-gce-pd-node
```
=> Add psp to allow deploying csi-gce-pd-node

Dockerfile, test/k8s-integration/cluster.go, test/k8s-integration/config/test-config-template.in, test/k8s-integration/main.go
Could not figure out how to bring up a GCE Ubuntu environment so I've put that on the backburner for now. We can get the signal we need from GKE tests.
Fixes: #306 
Fixes: #305 
/kind feature
```release-note
Add support for formatting and mounting an XFS filesystem
```
=> Add XFS utils and configuration to test on GKE with ubuntu image type

pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go
/kind bug
/kind cleanup
Fixes #445 
```release-note
Set volume limits to 15 only for machine-types: "f1-micro", "g1-small", "e2-micro", "e2-small", "e2-medium". Limit is 127 for all others
```
=> Update volume limits for new machine types: https://cloud.google.com/compute/docs/machine-types

Dockerfile, cmd/main.go, pkg/gce-pd-csi-driver/node.go, pkg/mount-manager/device-utils.go, pkg/mount-manager/fake-device-utils.go, test/e2e/tests/setup_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/utils/utils.go
TODO:
/kind bug
Fixes #376 
`/lib/udev/scsi_id` was pointing to the binary on the host due to the `/lib/udev` hostPath. This was causing weird package dynamically linked library finding issues (couldn't find the right version of dynamic libs). The solution is to use the `/lib/udev/scsi_id` from the container by copying it into a special directory. Thanks @msau42 for pointing out that `/lib/udev` was coming from the host
```release-note
During NodeStageVolume run udevadm --trigger to fix device symlinks if device path is not found or device path points to the wrong device
```
=> Update VerifyDevicePath logic to run udevadm --trigger to fix scenarios where disk is not found or is wrong device

pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/node.go
/kind bug
/assign @msau42 @gnufied
Fixes #433 
```release-note
Fixed bug where ControllerExpandVolume was returning incorrect size when disk was already the requested size or larger
```
=> Fix Resize call to return size in Gi as expected when disk is already the request size or larger

cmd/main.go, pkg/gce-cloud-provider/compute/gce.go, pkg/gce-pd-csi-driver/controller.go
/kind cleanup
We thread contexts through so that cancelled contexts will cancel cloud provider calls in the driver.
```release-note
NONE
```
=> Thread contexts into all appropriate functions in non-test code

test/k8s-integration/config/test-config-template.in, test/run-k8s-integration-local.sh
/kind cleanup
Fixes #261 
We already have regional tests in GKE CI. This change enables the remaining topology tests.
```release-note
NONE
```
=> Add TopologyKey to driver info so that topology tests run in multizone clusters

CHANGELOG-0.6.md, Dockerfile, deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml
/kind bug
After release we should:
```release-note
NONE
```
=> Bump debian-base-amd64 version for fix of CVE-2017-14062

Makefile, cmd/main.go, deploy/kubernetes/base/controller.yaml, docs/kubernetes/user-guides/driver-install.md, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce.go, pkg/gce-cloud-provider/metadata/fake.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, pkg/gce-pd-csi-driver/gce-pd-driver_test.go, pkg/gce-pd-csi-driver/identity_test.go, pkg/gce-pd-csi-driver/node_test.go, test/sanity/sanity_test.go
/kind feature
This PR adds the new `zone` field to the GCE cloud config and makes the controller server independent of the GCE metadata service if both `project-id` and `zone` are present in the config.
Also, it adds two new command line flags `run-controller-service` and `run-node-service` (both default to `true`) which allow to particularly disable individual services if not required.
This enables the use-case of running the CSI controllers (csi-provisioner, csi-attacher, etc., + the driver controller) separately outside of the cluster, and not necessarily on an GCE compute instance.
```release-note
It is now possible to disable the controller service by setting …
```
=> Allow disabling particular driver services

pkg/common/constants.go, pkg/common/parameters.go, pkg/common/parameters_test.go, pkg/gce-cloud-provider/compute/cloud-disk.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go
TODO: 
/kind cleanup
/kind feature
/assign @msau42 @misterikkit 
Partially does #384 (Still need to do `Node` side validation in a seperate PR)
Fixes #162 
```release-note
ValidateVolumeCapabilities validates that the given volume conforms to all capabilities in the request. Validation of existing volumes during inserts also improved to check all parameters.
```
=> Implement ValidateVolumeCapabilities and refactor parameter handling for more comprehensive validation of existing disks in all cloud calls

deploy/kubernetes/overlays/prow-gke-release-staging-rc/enable_sidecar_metrics.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
/kind feature
**What this PR does / why we need it**: Qualify external-attacher 2.1.1 in RC staging; enable Prometheus metrics in attacher, provisioner, and resizer
```release-note
NONE
```
=> Qualify external-attacher 2.1.1 in RC staging; enable Prometheus metrics in attacher, provisioner, and resizer

deploy/kubernetes/base/node.yaml, deploy/kubernetes/base/setup-cluster.yaml
/kind cleanup
**What this PR does / why we need it**: 
The DaemonSet will fail if its replicas are scheduled on Windows nodes.
The new RBAC rule is added in anticipation of this change: https://github.com/kubernetes-csi/external-attacher/pull/200/files#diff-59021f01acbcbd85d054c17acc3e26c8R37
```release-note
NONE
```
=> Adding linux node selector; adding new volumeattachment RBAC rule

pkg/gce-pd-csi-driver/node.go, pkg/mount-manager/device-utils.go, test/e2e/tests/multi_zone_e2e_test.go
/kind bug
Fixes #476 
Good news is this was not broken in any actual releases. The bug was introduced when fixing the `udevadm` stuff a couple of weeks ago and was not caught because of the silent failure of the test.
```release-note
NONE
```
=> Stop regional PD test from failing silently and fix verification path to use correct name

deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
/kind cleanup
**What this PR does / why we need it**: Make sure latest sidecar releases remain compatible with the PD CSI driver.
```release-note
NONE
```
/assign @msau42 @saad-ali
=> Staging RC overlay: Bump all sidecar versions to latest

Dockerfile.Windows, Makefile, init-buildx.sh
Add build rule for windows container. Here we try to enable buildx for
buiding windows container image on a linux VM
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Adds new build rules using docker buildx feature for allowing to build windows container image on either windows or linux node.
```
=> Add build rule for Windows container

deploy/common.sh
>
/kind bug
> /kind design
> /kind flake
Fixes a syntax issue on the `deploy/common.sh` script when checking for unset variables.
Fixes #493 
```release-note
NONE
```
=> Fix syntax error on the common script

test/k8s-integration/cluster.go, test/k8s-integration/main.go
/kind bug
Backport test skip to 0.6 release for pre-1.16 clusters.
```release-note
NONE
```
=> Backport test skip from master

test/k8s-integration/main.go
/kind bug
Adds logging code to the k8s-integration driver to debug why test skips aren't happening as expected.
```release-note
None
```
=> Add logging to debug why test skip isn't effective

test/k8s-integration/config/pd-volumesnapshotclass.yaml, test/k8s-integration/config/test-config-template.in, test/k8s-integration/driver-config.go, test/k8s-integration/main.go, test/run-k8s-integration-local.sh, test/run-k8s-integration.sh
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Summary of changes:
1. Added a snapshot-class option to pass VolumeSnapshotClass.
2. Added a default VolumeSnapshotClass definition, which uses PD CSI as a snapshot driver.
3. Remove “Feature:” tag from skipString, since snapshot tests have a [Feature:VolumeSnapshotDataSource] tag.
4. Prevent snapshot tests from running pre 1.17 kubernetes version.
5. Allow snapshot tests run only in release-staging-head and release-staging-rc overlays, since the snapshotter is not …
=> Provide optional flags to run PD CSI driver snapshot tests

README.md, docs/kubernetes/user-guides/snapshots.md, examples/kubernetes/snapshot/default-volumesnapshotclass.yaml, examples/kubernetes/snapshot/snapshot.yaml
>
> /kind bug
> /kind design
> /kind flake
Update the documentation and user guides for beta snapshotter feature.
Fixes #457 
```release-note
Update documentation and user guides for beta snapshotter
```
=> Update documentation and user guides for beta snapshotter

deploy/kubernetes/overlays/prow-gke-release-staging-rc/enable-leader-election.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/leader-election-rbac.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/statefulset-to-deployment.yaml
/kind feature
First step in releasing change for #516
```release-note
NONE
```
/cc ffilippopoulos
=> Adding leader election to controllers in staging rc

deploy/kubernetes/base/controller/cluster_setup.yaml, deploy/kubernetes/base/controller/controller.yaml, deploy/kubernetes/base/controller/kustomization.yaml, deploy/kubernetes/base/kustomization.yaml, deploy/kubernetes/base/node_linux/kustomization.yaml, deploy/kubernetes/base/node_linux/node.yaml, deploy/kubernetes/base/node_linux/psp.yaml, deploy/kubernetes/base/node_windows/kustomization.yaml, deploy/kubernetes/base/node_windows/node.yaml, deploy/kubernetes/base/node_windows/psp.yaml, deploy/kubernetes/deploy-driver.sh, deploy/kubernetes/images/alpha/image.yaml, deploy/kubernetes/images/alpha/kustomization.yaml, deploy/kubernetes/images/dev/image.yaml, deploy/kubernetes/images/dev/kustomization.yaml, deploy/kubernetes/images/prow-gke-release-staging-head/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-head/kustomization.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc/kustomization.yaml, deploy/kubernetes/images/stable/image.yaml, deploy/kubernetes/images/stable/kustomization.yaml, deploy/kubernetes/install-kustomize.sh, deploy/kubernetes/overlays/alpha/kustomization.yaml, deploy/kubernetes/overlays/dev/controller_always_pull.yaml, deploy/kubernetes/overlays/dev/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml
This can work for both linux and windows.
The current structure for kustomization is as follows
-  base: it contains the setup that is common to different driver versions.
*    controller_setup: includes cluster setup and controller yaml files
*    node_setup:
*  Linux: includes node yaml file and related setting that is only applicable for Linux
*  Windows: includes node yaml file and related setting that is only applicable for Windows
- images: it has a list of images for different versions
*   stable: currently has only image list for Linux stable version
*   alpha: besides image list in stable, also add windows image updates
*   dev: based on alpha, and also contains user's image
*   prow-xxx: image list used for prow tests. Linux only right now.
-  overlays: it has the version …
=> New kustomization for pd driver

test/k8s-integration/cluster.go, test/k8s-integration/main.go, test/k8s-integration/utils.go, test/k8s-integration/version.go, test/k8s-integration/version_test.go, test/run-k8s-integration-local.sh, test/run-k8s-integration.sh
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Add hook to deploy GKE with GCE PD CSI driver, and run kubernetes e2e tests against the managed driver.
Summary of changes:
1. Add a new hook to pass release-channel for GKE cluster deployment.
2. Add a new hook to deploy GKE managed PD CSI driver.
3. Added a version comparision util with supporting UTs.
Fixes #511 
```release-note
Add hook to …
```
=> Add option to deploy GKE managed PD CSI driver for integration tests

pkg/gce-cloud-provider/compute/cloud-disk.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go
>
/kind bug
> /kind design
> /kind flake
In PD CSI Driver CreateVolume call, wait for disk to reach a READY status, before returning success to caller.
Fixes #526
```release-note
In GCE PersistentDisk CSI Driver CreateVolume call, wait for disk to reach a READY status, before returning success to caller.
```
=> Return success in CreateVolume when disk is READY

test/k8s-integration/cluster.go
>
/kind bug
> /kind design
> /kind flake
Honor image-type in GKE cluster deploy. (Fix the bug introduced in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/515)
Fixes #535 
```release-note
Honor image-type in GKE cluster deploy
```
=> Honor image type option in GKE cluster deploy

deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-head/volume-inuse-error-handler.yaml
>
> /kind bug
> /kind design
> /kind flake
Disable the optional capability to handle volume in user errors for staging-head PD driver.
Fixes #539 
Tested with local build of resizer with the fix of https://github.com/kubernetes-csi/external-resizer/pull/89
```release-note
Disable the optional capability to handle volume in user errors for staging-head PD driver.
```
=> Disable VolumeInUse Error handler in CSI Resizer

Dockerfile.Windows, Makefile, deploy/kubernetes/base/controller/cluster_setup.yaml, deploy/kubernetes/images/alpha/image.yaml, deploy/kubernetes/overlays/alpha/kustomization.yaml, test/k8s-integration/config/sc-windows.yaml, test/k8s-integration/config/test-config-template.in, test/k8s-integration/driver-config.go, test/k8s-integration/driver.go, test/k8s-integration/main.go, test/run-windows-k8s-integration.sh
This PR adds e2e CI tests for Windows.
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Add e2e CI tests for Windows

deploy/kubernetes/overlays/prow-gke-release-staging-head/increase-sidecar-operation-timeout.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/increase-sidecar-operation-timeout.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #541 
```release-note
Increase provisioner and attacher op timeout to reduce retries
```
=> Increase PD CSI sidecar operation timeout

test/k8s-integration/driver.go, test/k8s-integration/main.go, test/run-windows-k8s-integration.sh
update ci test configuration
Fix windows integration script
remove env virable GCE_PD_DO_DRIVER_BUILD direct setting
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Update CI test configuration

init-buildx.sh
fix issues in init-buildx.sh
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Update windows test script

pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce-compute_test.go
/kind bug
This PR fixes the issue where provisioning of GCE PDs with CMEK used to sometimes fails with `disk already exists with same name` error.
Fixes #558
Added unit test to prevent future regression.
Manually verified by setting csi-provisioner timeout to 1 seconds:
```
Type     Reason                 Age                From                                                                                                 Message
----     ------                 ----               ----                                                                                                 -------
Normal   ExternalProvisioning   32s (x2 over 34s) …
```
=> Fix Random CMEK Disk Creation Failure (disk already exists)

deploy/kubernetes/overlays/prow-gke-release-staging-rc/csi-driver.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
>
> /kind bug
> /kind design
> /kind flake
This PR adds CSIDriver object into the deployment script.
Fixes #564 
```release-note
NONE
```
/cc @saad-ali 
/cc @verult
=> Add CSIDriver object into driver deployment script

deploy/kubernetes/overlays/prow-gke-release-staging-head/enable-extra-create-metadata.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml, pkg/common/parameters.go, pkg/common/parameters_test.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go, test/e2e/tests/single_zone_e2e_test.go
>
/kind feature
In-tree GCE PD "tags" a disk with information about which PVC/PV the disk was created for.
These tags are stored as JSON in the disk Description field.
This PR archives feature-parity with that behavior using https://github.com/kubernetes-csi/external-provisioner/pull/399
Added automated tests and did manual tests to verify new behavior:
Example disk Description field provisioned by in-tree GCE PD plugin:
```
{"kubernetes.io/created-for/pv/name":"pvc-4ffe59ed-8ee0-11e7-a29f-42010a800002","kubernetes.io/created-for/pvc/name":"myclaim","kubernetes.io/created-for/pvc/namespace":"default"} …
```
=> Add metadata info in tag on PD

pkg/gce-pd-csi-driver/node.go
>
/kind bug
Fixes #372
```release-note
Skip NodeExpandVolume for block volumes. 
```
=> Skip NodeExpandVolume for block volumes

deploy/kubernetes/base/controller/csidriver_info.yaml, deploy/kubernetes/base/controller/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/csi-driver.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
>
> /kind bug
> /kind design
> /kind flake
Promote CSIDriver object deployment to GA
Fixes #
```release-note
Install CSIDriver object as part of driver deployment.
```
/cc @saad-ali 
/cc @verult 
/cc @saikat-royc
=> Promote CSIDriver deployment to stable

deploy/kubernetes/base/controller/controller.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-head/enable-extra-create-metadata.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml
>
/kind cleanup
This PR moves the PD tagging functionality introduced in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/570 to all deployments including stable.
Since the stable version has not yet been cut, the new test introduced in that PR will fail until a new release is cut and stable version is updated.
Fixes #
```release-note
None
```
=> Move extra-create-metadata to stable

deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml, deploy/kubernetes/images/stable/image.yaml
>
/kind cleanup
Follow up on https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/572
Update stable image to v1.0.0
This will cause stable to fail until the 1.0.0 release is actually cut and published.
Fixes #
```release-note
None
```
=> Update stable image to v1.0.0

deploy/kubernetes/README.md
Based on https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/520#issue-428022606
```release-note
NONE
```
/assign @jingxu97 @msau42
=> Adding Kustomize structure in deployment README

test/k8s-integration/driver-config.go, test/k8s-integration/main.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #583 
```release-note
Enable volume expansion test for GKE managed driver
```
=> Enable Volume expansion test for GKE PDCSI driver

deploy/setup-project.sh
…project.
/kind feature
The project setup script will now run `gcloud projects add-iam-policy-binding "${PROJECT}" --member serviceAccount:"service-${PROJECT_NUMBER}@compute-system.iam.gserviceaccount.com" --role "roles/cloudkms.cryptoKeyEncrypterDecrypter"`.
This is important because it authorizes GCE to use Cloud KMS encryption keys. Without this grant usage to Cloud KMS will be blocked and tests will fail with,
```
Should create CMEK key, go through volume lifecycle, validate behavior on key revoke and restore [It]
/usr/local/google/home/jeremyedwards/github/src/sigs.k8s.io/gcp-compute-persistent-disk-csi-driver/test/e2e/tests/single_zone_e2e_test.go:347
CreateVolume failed with error: rpc error: code = Internal desc …
```
=> Project setup script authorizes GCE to use Cloud KMS keys on the dev project.

release-tools/.prow.sh, release-tools/CONTRIBUTING.md, release-tools/LICENSE, release-tools/OWNERS, release-tools/README.md, release-tools/RELEASE.md, release-tools/SECURITY_CONTACTS, release-tools/SIDECAR_RELEASE_PROCESS.md, release-tools/build.make, release-tools/cloudbuild.sh, release-tools/cloudbuild.yaml, release-tools/code-of-conduct.md, release-tools/filter-junit.go, release-tools/go-get-kubernetes.sh, release-tools/prow.sh, release-tools/travis.yml, release-tools/update-vendor.sh, release-tools/util.sh, release-tools/verify-go-version.sh, release-tools/verify-shellcheck.sh, release-tools/verify-subtree.sh, release-tools/verify-vendor.sh
/kind feature
Imports the kubernetes-csi/csi-release-tools repository to align the build with other CSI projects.
This PR simply adds the repository, it does not modify the current `Makefile`, that'll be done in a future PR.
#585
I have done limited testing some things are currently broken but that's expected. Notably the e2e tests.
```release-note
NONE
```
=> Import the kubernetes-csi/csi-release-tools subtree.

test/k8s-integration/main.go
/kind cleanup
The change to test multiple storage classes used the full storageclass filename for the test output directory. Feedback came that it was confusing for a directory to end in .yaml; this PR strips that suffix.
```release-note
NONE
```
=> Strip .yaml from test output dirs

Dockerfile
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Changes driver's Docker base image to `k8s.gcr.io/build-image/debian-base-amd64:v2.1.3` (previously `gcr.io/google-containers/debian-base-amd64:v2.0.0`) to address CVEs.
Fixes #
```release-note
Update GCE PD CSI Driver Docker base image to `k8s.gcr.io/build-image/debian-base-amd64:v2.1.3` (previously …
```
=> Update debian base image version to 2.1.3

Dockerfile
/kind cleanup
Cherry pick https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/596 to release-1.0
Fixes #
```release-note
Update GCE PD CSI Driver Docker base image to `k8s.gcr.io/build-image/debian-base-amd64:v2.1.3` (previously `gcr.io/google-containers/debian-base-amd64:v2.0.0`) to address CVEs.
```
=> Cherry-pick #596 to `release-1.0` (Update debian base image version to 2.1.3)

pkg/common/parameters_test.go
Fix this problem. 
```bash
go version
go version go1.14.4 linux/amd64
go test ./pkg/...
--- FAIL: TestExtractAndDefaultParameters (0.00s)
--- FAIL: TestExtractAndDefaultParameters/real_values,_checking_balanced_pd (0.00s)
parameters_test.go:109: ExtractAndDefaultParameters(map[disk-encryption-kms-key:foo/key replication-type:regional-pd type:pd-balanced]) = {pd-balanced regional-pd foo/key map[]}; expected params: {pd-balanced regional-pd foo/key map[]}
FAIL
FAIL    sigs.k8s.io/gcp-compute-persistent-disk-csi-driver/pkg/common   0.003s
ok      sigs.k8s.io/gcp-compute-persistent-disk-csi-driver/pkg/gce-cloud-provider/compute       (cached)
? …
```
=> Fix TestExtractAndDefaultParameters test.

Makefile, cmd/gce-pd-csi-driver/main.go
/kind cleanup
This renames the `vendorVersion` ldflag to `version` since that's what `release-tools/build.make` accepts for building CSI binaries.
Partial fix for #585
```release-note
NONE
```
=> Rename vendorVersion to version to comply with build.make.

deploy/kubernetes/install-kustomize.sh
The latest version of kustomize does not work for image tag transfer
This PR use a fixed version 3.8.0
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Use a fixed version of kustomization

test/k8s-integration/cluster.go, test/k8s-integration/main.go, test/run-k8s-integration-ci.sh, test/run-k8s-integration.sh
For GKE clusters, node-version flag can be provided during cluster
creation to specify worker node k8s version. This change is needed
to test node and master version skew combinations.
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
PD CSI e2e test infra should take GKE node version as an optional input argument.
```
=> e2e test should take GKE node version as an input

test/k8s-integration/driver.go, test/k8s-integration/main.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
Collect managed pd csi driver logs from node
```
=> Collect managed pd csi driver logs from node

deploy/kubernetes/wait-for-driver.sh, test/k8s-integration/driver.go
/kind bug
Fixes #614 
Note that I don't think this addresses the "prepull imageset" part of the issue, I'm not sure I understand that part?
```release-note
NONE
```
=> Wait on driver deployment rather than sleep

test/k8s-integration/main.go, test/k8s-integration/prepull-image.sh
/kind bug
**Which issue(s) this PR fixes**: 
Fixes #614
```release-note
NONE
```
=> Wait for windows prepull images rather than sleeping

deploy/kubernetes/base/controller/cluster_setup.yaml, deploy/kubernetes/base/controller/kustomization.yaml, deploy/kubernetes/base/controller/psp.yaml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Adds PSP for the controller Deployment. Without it, clusters with default PSP having basic permissions, the controller will not be allowed to run.
Fixes #
No
```release-note
NONE
```
=> Add PSP for the controller Deployment

test/run-k8s-integration-ci.sh
Using this new knob, intree plugin and csi tests can be run together
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
Provide a knob to run intree and csi plugin tests
```
=> Provide a knob to run intree and csi plugin tests

cmd/gce-pd-csi-driver/main.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/utils_windows.go, pkg/mount-manager/statter_linux.go, pkg/mount-manager/statter_windows.go
add support for getting volume stats for windows. Tested on Windows node with following and it is working.
note: Inode is not available for windows.
invoke-webrequest http://localhost:10255/metrics -outfile metrics
>
> /kind bug
> /kind design
> /kind flake
Fixes #628
```release-note
NONE
```
=> Add VolumeStats for Windows

test/k8s-integration/cluster.go, test/k8s-integration/config/sc-regional.yaml, test/k8s-integration/config/test-config-template.in, test/k8s-integration/driver-config.go, test/k8s-integration/main.go, test/run-k8s-integration-ci.sh
/kind cleanup
Add regional PD to tests.
Fixes #408 
```release-note
NONE
```
=> Add test support for regional PD

deploy/kubernetes/base/controller/cluster_setup.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/sidecar-upgrade.yaml
>
> /kind bug
> /kind design
> /kind flake
Upgrade csi sidecars to newest versions on staging rc for tests
Fixes #
```release-note
NONE
```
/cc @saad-ali 
/cc @verult 
/cc @saikat-royc
=> Upgrade csi sidecars to newest versions on rc

pkg/gce-pd-csi-driver/utils_windows.go, pkg/mount-manager/safe-mounter_windows.go
Add logic to dismount volume using csi-proxy during nodeUnstageVolume
for Windows
DismountVolume in csi-proxy will call writeVolumeCache to flush data
before unmount
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Modify NodeUnstageVolume call for Windows

test/k8s-integration/main.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
Capturing the flow here: 
This patch uses kubetest --dump flag instead of directly setting up --report-dir flag. If dump flag is provided, kubetest will setup report-dir [here](https://github.com/kubernetes/test-infra/blob/master/kubetest/e2e.go#L40). Also using dump flag, enables kubetest to call DumpClusterLogs for both GCE and GKE deployments. For GKE, the function will setup the …
=> Enable dump GKE node logs

test/k8s-integration/driver.go
Build multi-arch container image takes much longer time than only
building linux container image. This PR changes back to only build linux
container image for linux tests to avoid timeout issue
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Build only linux container image for tests on Linux

pkg/gce-pd-csi-driver/utils_windows.go
Add defensive check for Windows. GCE PD CSI driver only support ntfs for
Windows. If other fstype is passed, return error.
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Add fstype check for Windows

CHANGELOG/CHANGELOG-1.1.md, README.md
>
> /kind bug
> /kind design
> /kind flake
Release notes for upcoming 1.1.0 release
N/A
```release-note
NONE
```
=> Add release notes for 1.1.0 release

CHANGELOG/CHANGELOG-1.1.md, README.md, deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml, deploy/kubernetes/install-kustomize.sh
>
> /kind bug
> /kind design
> /kind flake
Cherrypick #647 from `master` to `release-1.1`: Update kustomizer to 3.8.6
Cherrypick #644 from `master` to `release-1.1`: Add release notes for 1.1.0 release
Cherrypick #652 from `master` to `release-1.1`: Update staging RC to use new 1.1.0 RC build
```release-note
None
```
/assign @jingxu97 
=> Cherrypick #644, #647, #652 from `master` to `release-1.1`

test/k8s-integration/driver-config.go, test/k8s-integration/driver.go, test/k8s-integration/main.go
/kind bug
Since https://github.com/kubernetes/kubernetes/pull/95527 enables XFS on COS in the e2e tests, the PD CSI tests need to selectively disable it when the test on GKE versions without newer COS versions.
```release-note
NONE
```
=> Enable XFS selectively for GKE clusters with proper COS support

test/run-k8s-integration-ci.sh
/kind bug
Add run-k8s-integration-ci.sh that the prow driver now expects to be in each release.
Fixes #651
```release-note
NONE
```
=> Add run-k8s-integration-ci.sh

test/k8s-integration/driver-config.go, test/k8s-integration/main.go
/kind bug
Use node version when detecting XFS compatibility for testing on GKE
```release-note
NONE
```
=> Use node version on GKE when detecting XFS compatibility

deploy/kubernetes/overlays/dev/kustomization.yaml, deploy/kubernetes/overlays/noauth/kustomization.yaml
After PR https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/610 change, in current dev overlay, kustomization will not work well with image
setting (overwriting)
Modify the structure to fix it.
>
> /kind bug
> /kind design
> /kind flake
Fixes #650
Fixes #649
```release-note
NONE
```
=> Update dev overlay so that image overwrite can work

pkg/gce-cloud-provider/compute/cloud-disk.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce-compute_test.go, pkg/gce-cloud-provider/compute/gce.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go
/kind cleanup
The only Disk feature that required an alpha API (multiwriter) is now in beta.
We keep the infrastructure to be able to swap API versions, but it has been simplified to reduce code duplication.
Builds on top of #642
```release-note
NONE
```
=> Migrate from alpha to beta compute APIs

pkg/gce-pd-csi-driver/node.go, pkg/mount-manager/safe-mounter_windows.go
NodeStageVolume
The logic for checking volume is mounted or not during NodePublishVolume
has issues. It might not handle failures well.
This issue was discovered by https://github.com/kubernetes/kubernetes/pull/88759 which cause windows tests fail.
>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Fix check volume is mounted logic during NodePublishVolume and

test/run-windows-k8s-integration.sh
Remove ntfs keyword from test focus so that more tests will be triggered
(snapshottable)
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Modify integration test focus for Windows

test/k8s-integration/main.go
Some intree tests create disks with names which is a combination of
cluster name + UUID, and exceeds the 63 chars limit of disk resources
>
> /kind bug
> /kind design
> /kind flake
Fix in-tree tests run on GKE clusters
Fixes #
For reference of how the pd name is created: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/providers/gce/gce.go#L208
Without this fix, the disk resource name is something like this …
=> Shorten the GKE cluster name

pkg/mount-manager/safe-mounter_windows.go
Add string array length check on returned volumeIds to avoid panic issue
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Add check on returned volumeIds

README.md, docs/kubernetes/user-guides/basic.md, docs/kubernetes/user-guides/windows.md, examples/kubernetes/demo-windows.yaml, examples/kubernetes/demo-zonal-sc.yaml
add doc for csi windows support
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> Add CSI Windows Support Doc

deploy/kubernetes/wait-for-driver.sh
print out pods description if driver is failed to install
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Add pod desciption if driver daemonset fails to install

test/k8s-integration/cluster.go, test/k8s-integration/version.go
>
> /kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: 1.18 driver tests are failing when an overlay is used in a GKE deployment because the GKE deployment is enabled by default. This PR explicitly disables it.
Fixes #
```release-note
NONE
```
=> disable gke deployment for clusters with installation by default if GKE deployment is not requested

test/k8s-integration/main.go
>
> /kind bug
> /kind design
> /kind flake
volume expansion feature is beta in k8s 1.16. for the node skew tests on regular channel, we ended up with a master in 1.16 and node in 1.15. This caused the kubelet in the node to skip the NodeExpandVolume CSI calls to the driver, since the codepath is feature gated. [ExpandCSIVolumes](https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go#L97)
Fixes #
**Does this PR …
=> Skip volume expansion test for node skew tests

pkg/common/utils.go, pkg/common/utils_test.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go, test/e2e/utils/utils.go
/kind bug
Currently if we create a PVC of size 1.5Gi, the pdcsi driver will convert it to 1Gi but the provisioner will say it is 2Gi[1]. And both of them are not accurate. From the CSI spec, we know that we should provide size larger than the requested size. So if user ask for 1.5Gi, we should give them at least 1.5Gi. 
This PR changes the RoundDown behavior of CreateVolume to RoundUp. This is to align with the CreateVolume CSI spec that when the required_bytes is set, the driver should provision something bigger.
[1] https://github.com/kubernetes-csi/external-provisioner/issues/199
Fixes # …
=> Round up pdcsi driver size in CreateVolume

README.md
The dev overlay no longer works on pre-1.17 versions due to CSINode needing to be v1 for the recent sidecars used now in master.
```release-note
NONE
```
=> Change supported dev version to 1.17+ only, due to CSINode v1 version

Dockerfile.Windows, Makefile, manifest_osversion.sh
/kind feature
Newer versions of Kubernetes will support Windows Server 2004 and 20H2.
This PR also adds the support to pick a specific tag within a release band so that builds across CI runs can be consistent.
Lastly, this PR also changes the tagging for the OS specific images in the multi-arch build. There's a small chance this can cause some disruption but it's low. This change was necessary because of the `20H2` version suffix. The capital H is rejected in the image name but ok for tag. This change does reduce the image repository count so there's a benefit to moving the OS suffix from the image name to the tag.
Fixes #690
This change needs to go …
=> Windows Server 20H2 and 2004 support, configurable base layer versions.

Dockerfile.Windows, Makefile, manifest_osversion.sh
Cherry pick of #691 on release-1.2.
#691: Add Windows 2004 and 20H2 support and ability to specify a
=> Automated cherry pick of #691: Add Windows 2004 and 20H2 support and ability to specify a

test/k8s-integration/main.go
For integration test for Windows, there is issue during tainting the
linux node. Add log and use "overwrite=true" option in case taint is
already on the node.
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Fix issue for taint linux nodes for Windows tests

deploy/kubernetes/base/node_linux/node.yaml, deploy/kubernetes/base/node_windows/node.yaml, deploy/kubernetes/images/alpha/image.yaml, deploy/kubernetes/images/stable/image.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, test/run-windows-k8s-integration.sh
move Windows pd csi deployent to stable overlay
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Move Windows deployment to stable overlay

deploy/kubernetes/base/node_windows/node.yaml
/kind bug
Removes a flag introduced in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/701/files# to the wrong container (it should only be in `gce-pd-driver`)
Fixes #
```release-note
NONE
```
=> Remove csi-driver-registrar flag

hack/verify-coverage.sh
/kind feature
Add a coverage script to hack/. In addition to making it easier to manually verify code coverage, this will enable automated tooling to produce coverage reports.
Running it looks like
```
$ ./hack/verify-coverage.sh 
Verifying coverage
ok  	sigs.k8s.io/gcp-compute-persistent-disk-csi-driver/pkg/common	0.095s	coverage: 66.7% of statements
ok  	sigs.k8s.io/gcp-compute-persistent-disk-csi-driver/pkg/gce-cloud-provider/compute	0.134s	coverage: 3.4% of statements
ok  	sigs.k8s.io/gcp-compute-persistent-disk-csi-driver/pkg/gce-pd-csi-driver	0.212s	coverage: 58.6% of statements
```
(gce-cloud-provider looks pretty sad... it's possible we'll want to exclude it from coverage if it's not unit-testable. This can be …
=> Add hack/verify-coverage.sh

docs/release/overlays.md
>
> /kind bug
> /kind design
> /kind flake
With new overlays introduced as part of #704 , this patch captures the related documentation for overlays.
The final update to the README.md will be done once we finish merging windows changes to appropriate stable-* overlays
Fixes #
```release-note
Documentation for overlays
```
=> Documentation for overlays (part 1)

deploy/kubernetes/images/prow-gke-release-staging-rc-1-16/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc-1-18/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc-1-19/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc-master/kustomization.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
1. Bump staging images to use latest 1.2.0-gke.8 driver image
2. Enable windows driver components
Fixes #
```release-note
NONE
```
=> Enable windows driver components for k8s minor staging overlays

test/k8s-integration/main.go, test/run-k8s-windows-migration.sh
Fix issues for Windows CSI migration test
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Fix issues in Windows migration test

docs/kubernetes/user-guides/basic.md
Add documentation to clarify the fact that regional PDs can be used in zonal clusters and shows such an example.
Fixes #
**Does this PR introduce a user-facing change?**: NONE
```release-note
```
=> Add usage of regiona PD in zonal clusters to user guide

pkg/gce-pd-csi-driver/utils.go
This is especially useful when we have a livenessprobe sidecar
The log can be spamed with all the probe logs if we record them
This PR removes probe logging for pd driver. Since it can provide huge noise to the entire logging if we enable livenessprobe
Fixes #
```release-note
Remove probe logging to reduce noise
```
=> Remove Probe logging

deploy/kubernetes/README.md, deploy/kubernetes/delete-driver.sh, deploy/kubernetes/deploy-driver.sh, deploy/kubernetes/images/alpha/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml, test/run-k8s-integration-ci.sh, test/run-k8s-integration-migration.sh, test/run-k8s-integration.sh
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This patch will switch the existing presubmit and CI jobs to use stable-master instead of stable.
Fixes #
Please let me know if I missed out on any prow job configs.
So far I checked
1. internal GKE test grids
2. https://k8s-testgrid.appspot.com/provider-gcp-compute-persistent-disk-csi-driver
3. Configs for presubmits defined [here](https://github.com/kubernetes/test-infra/blob/master/config/jobs/ku …
=> Switch the integration scripts and deploy driver scripts default overlays

test/k8s-integration/cluster.go, test/k8s-integration/main.go, test/run-k8s-integration-ci.sh, test/run-k8s-integration-migration.sh, test/run-k8s-integration.sh, test/run-k8s-windows-migration.sh, test/run-windows-k8s-integration.sh
Engprod plans to end kubetest support. This diff adds a --use-kubetest2 flag to the
integration test driver.
Next step:
1. Add kubetest2 installation to test scripts.
2. Add a canary test config to validate kubetest2.
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Migrate to the latest test-infra supported test runner. Immediate benefits include reducing ssh-related flakiness in kubetest.
Fixes # …
=> Add a mode to run e2e tests using kubetest2.

README.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Update README for overlays
```
=> Update README for overlays

test/k8s-integration/.dockerized-kube-version-defs, test/k8s-integration/cluster.go
/kind bug
Fixes #721 
This is a more complete change compare with #722.
See the comment in the change for the details of how the git clone is done for the master branch.
Pulling a specific version is unchanged (the k/k release archive is still used).
```release-note
```
=> Make a clone of k8s master instead of using archive

test/k8s-integration/cluster.go
**What this PR does / why we need it**: Prow tests are failing with the latest kubekins image because in the latest gcloud version, `gcloud container clusters list --filter name=<cluster_name>` prints one line of warning instead of returning empty, which makes the k8s-integration binary to proceed to cluster deletion, and fail when the cluster doesn't actually exist.
This PR is a short term solution. Long term solution would be moving to the cloud SDK (#680).
```release-note
None
```
=> Fix cluster list parsing for latest gcloud version

test/k8s-integration/main.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Make GKE cluster names more or less unique to avoid conflicts where the same boskos project was used.
Fixes #
```release-note
NONE
```
=> Add random suffix to GKE cluster name to avoid conflict.

Dockerfile, Dockerfile.Windows, cloudbuild.yaml
/kind feature
As part of the effort described in this [issue](https://github.com/kubernetes/k8s.io/issues/1525) we are deprecating the `gcr.io/gke-release` and the image `gcr.io/gke-release/gcp-compute-persistent-disk-csi-driver` does not exist in other registries. So we need to build that and push to a new registry.
We will use `gcr.io/k8s-staging-cloud-provider-gcp` to push the images and This PR add the cloudbuild to generate and push the image.
for more context see the slack 🧵  https://kubernetes.slack.com/archives/C09QZFCE5/p1615563067038600bump
- Also bump the go version to the lastest 1.13 available
`k/test-infra` PR to add the prow job: TBC
/assign @spiffxp @msau42 @mattcary  …
=> Add cloudbuild config to build gcp-compute-persistent-disk-csi-driver image

test/k8s-integration/config/sc-standard-no-labels.yaml, test/run-k8s-integration-ci.sh
/kind bug
Until the managed driver on platforms like GKE catch up their driver version in test environments, the label testing needs to have an option for disabling. See also #727.
```release-note
NONE
```
=> Add option to test without labels

test/k8s-integration/main.go
Since we now use a random suffix for GKE clusters, we need another
flag for existing cluster names.
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This PR adds a new flag to the test binary so we can specify the name of an existing GKE cluster.
Fixes #
```release-note
NONE
```
=> Add a param for full GKE cluster name.

Dockerfile, Dockerfile.Windows, cloudbuild.yaml
/kind feature
To build the image `gcr.io/k8s-staging-cloud-provider-gcp/gcp-compute-persistent-disk-csi-drive,` we need to cherry-pick the changes made in the main branch to the release-1.2 branch.
Because when the RC1 tag was generated (https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/releases/tag/v1.2.1-rc1), the prow job to build the image for the tag/release branch failed: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-gcp-compute-persistent-disk-csi-driver-push-images/1375144655808630784 because there is no cloudbuild in the branch.
this PR is a cherry-pick of
- https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/724 …
=> Add cloudbuild for gcp-compute-persistent-disk-csi-drive - cherry pick #724

CHANGELOG/CHANGELOG-1.2.md, README.md, deploy/kubernetes/images/stable-1-15/image.yaml, deploy/kubernetes/images/stable-1-16/image.yaml, deploy/kubernetes/images/stable-1-17/image.yaml, deploy/kubernetes/images/stable-1-18/image.yaml, deploy/kubernetes/images/stable-1-19/image.yaml, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
The internal prow tests for prow-staging-rc-{k8minor} with image v1.2.1-rc1 looks good. Hence submitting this PR to create a new release v1.2.1 for the driver image binary
.This PR updates the stable overlays driver manifest to use the yet to be release v1.2.1-gke.0 image, and the necessary changelogs/readme updates.
Link to the test grid: https://testgrid.corp.google.com/gcp-compute-persistent-disk-csi-driver 
Fixes #
**Special notes …
=> Update Stable overlay and Changelogs for 1.2.1 driver image

CHANGELOG/CHANGELOG-1.2.md, README.md, deploy/kubernetes/images/stable/image.yaml
>
> /kind bug
> /kind design
> /kind flake
cherrypick #735 with stable overlay image update and readme docs update.
This is the final cherrypick before creating v1.2.1 release tag on release-1.2 branch. 
Fixes #
Note the original PR had changes to stable-{k8s minor} overlays. However those overlays are not available in release-1.2. Hence I did a manual update of the stable overlay in this PR …
=> Update Stable images and readme (Cherrypick of #735 )

deploy/kubernetes/install-kustomize.sh
/kind bug
Fixes #743
/release-note-none
=> Improve kustomize downloading

Dockerfile, Makefile
We can use buildx, which is already set up in the Makefile, to
simultaneously build a multi-arch Docker image for this component for
ARM64 and AMD64, such that the image will work for both architectures.
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
We can publish an image that is multi-arch across X86 and ARM64.
Fixes #
```release-note
```
=> Build multi-arch images for ARM64 and AMD64 at the same time

test/run-k8s-windows-migration.sh, test/run-windows-k8s-integration.sh
Need to build driver before installing kubetest2.
>
kind bug
> /kind design
> /kind flake
Migration tests are failing. Need to build driver before installing kubetest2. 
Fixes #
```release-note
NONE
```
=> Fix migration tests

Dockerfile
Update driver base image to pick up vulnerability fixes.
```release-note
None
```
=> update linux base image to debian buster 1.5.0

deploy/kubernetes/wait-for-driver.sh
/kind bug
If driver deployment on the master fails, deploy/kubernetes/wait-for-driver.sh continues successfully. This is causing many spurious error messages in tests when there are problems with the deployment.
```release-note
None
```
=> exit if driver master deployment fails

deploy/kubernetes/overlays/prow-gke-release-staging-rc-master/disk_labels.yaml
/kind bug
The staging overlay has a bad command-line patch which tests the label command line.
```release-note
None
```
=> Fix label test used in staging

Makefile
The Dockerfile uses commands in Linux, which require the correct binfmt
for the architecture we build for. Therefore we need to configure Docker
to use QEMU userspace emulation to build images whose arches are
different from the host machine.
>
/kind bug
> /kind design
> /kind flake
This is a follow-up to #741. We need to configure Docker buildx correctly for the changes in #741 to work.
Fixes # …
=> Configure QEMU userspace emulation for Linux build

Dockerfile, Makefile, cloudbuild.yaml
/kind bug
When we built the image `k8s.gcr.io/cloud-provider-gcp/gcp-compute-persistent-disk-csi-driver:v1.2.1` we missed one parameter that needs to be set during the compilation process
This PR fix that, making it similar to how we build the image for windows.
built on my gcp account and now we can run the image without the error we saw before
```
$ docker run -it k8s.gcr.io/cloud-provider-gcp/gcp-compute-persistent-disk-csi-driver:v1.2.1
F0421 13:50:23.955027       1 main.go:71] version must be set at compile time
$ docker run -it gcr.io/cpanato-general/gcp-compute-persistent-disk-csi-driver:v99.99.99
W0421 13:50:31.576613       1 gce.go:137] GOOGLE_APPLICATION_CREDENTIALS env var not set
F0421 13:50:31.576650       1 …
```
=> fix missing variable when building the image on cloudbuild

test/k8s-integration/main.go
>
kind bug
> /kind design
> /kind flake
Use the --artifacts parameter in kubetest2 to save test logs. We were using the wrong one which results in logs from different storage classes overwriting each other.
Fixes #
```release-note
NONE
```
=> Use the correct log dump parameter for kubetest2.

test/k8s-integration/main.go
>
kind bug
> /kind design
> /kind flake
Add windows ginkgo params to kubetest2.
Also cleaned up an unused variable.
Fixes #
```release-note
NONE
```
=> Fix windows param for kubetest2.

test/run-k8s-integration-ci.sh
>
kind bug
> /kind design
> /kind flake
Migration tests shouldn't have a storage class file param.
Hopefully this is the last change to get migration+GKE tests going. 
Fixes #
```release-note
NONE
```
=> Remove storage class param for migration tests.

Dockerfile, Makefile
This appears to be necessary to get docker build to work, when BUILDPLATFORM is manually passed in rather than through the magic of buildx.
```release-note
None
```
=> Move ARG decls to top of Dockerfile

test/k8s-integration/version.go, test/k8s-integration/version_test.go
>
kind bug
> /kind design
> /kind flake
Allow tests to use GKE versions of the format X.Y, i.e. latest available for a minor version. 
Fixes https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/771
```release-note
NONE
```
=> Allow using minor version format for GKE

test/k8s-integration/main.go
Current parallel setting to 25 is too high for Windows. Every node will
have about 8-10 disks are being attached and fomatted around the same
time. For Windows Disk format time could reach about 4 mins which makes
the whole pod start time exceeds 5 mins and timeout.
Set parallel to 6 for Windows
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Update parallel setting for in integration test

test/run-k8s-integration-migration.sh, test/run-k8s-windows-migration.sh
Due to kubetest2 issue, provider is not passing correctly which are
checked by in-tree test cases. For now
change back to use kubetest for migration test.
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Use kubetest instead of kubetest2 for CSI migration test

Makefile
/kind bug
```release-note
None
```
=>  put GCFLAGS back in Makefile for debug builds

pkg/common/utils.go, pkg/common/utils_test.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/utils_linux.go, pkg/gce-pd-csi-driver/utils_windows.go, test/e2e/tests/single_zone_e2e_test.go
/kind feature
This PR allows using CSI snapshots across projects.
This feature enables GKE users to create VolumeSnapshots in a project FOO and import them in a project BAR.
This enhancement simplifies the migration process from between projects and improves the user experience with tools like Velero.
Fixes https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/781
```release-note
- It is now possible to access snapshots and volumes across different projects.
```
=> Allow cross project snapshots and volumes

test/k8s-integration/main.go
>
> /kind bug
> /kind design
> /kind flake
Reduce kubetest2 ginkgo parallelism until https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/789 is resolved.
Fixes #
```release-note
NONE
```
=> Reduce kubetest2 parallel tests

pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/utils.go
/kind bug
By default, XFS does not allow mounting two devices that have the same UUID of the XFS filesystem. Therefore it's not possible to mount a volume + its restored snapshot.
Therefore disable UUID check in XFS using a mount option.
Since https://github.com/kubernetes/kubernetes/pull/102538 was merged, all pull-kubernetes-e2e-gce-storage-slow tests fail in Kubernetes, e.g. https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/102690/pull-kubernetes-e2e-gce-storage-slow/1402241210831081472/
```release-note
It is now possible to mount a volume with XFS filesystem and its restored snapshot.
```
=> Disable uuid checks on XFS

README.md, docs/kubernetes/user-guides/snapshots.md
/kind cleanup
The release `v1.2.1` is out and the image `gcr.io/k8s-staging-cloud-provider-gcp/gcp-compute-persistent-disk-csi-driver:v1.2.1` is available in the staging registry and was promoted to the production registry (see https://github.com/kubernetes/k8s.io/pull/1854)
Update the docs to reflect the latest stable location
/assign @msau42 @mattcary 
Fixes #
```release-note
NONE
```
=> update image registry location

docs/kubernetes/user-guides/snapshots.md, examples/kubernetes/snapshot/volumesnapshotclass-storage-locations.yaml, pkg/common/parameters.go, pkg/common/parameters_test.go, pkg/common/utils.go, pkg/common/utils_test.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go
Use a comma separated string, for example "us-central1,us-west1"
as the "snapshot-locations" field of snapshot class parameters.
See the PR for detailed examples.
>
> /kind bug
> /kind design
> /kind flake
/kind feature
Allow users to set storage locations[1] for their PD snapshots by specifying them in the snapshot class. For example:
```yaml
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
name: snapshot-class-with-storage-locations
parameters:
storage-locations: us-central1 …
```
=> Allow users to specify "storage-locations" for snapshots.

release-tools/SIDECAR_RELEASE_PROCESS.md
Needed for https://github.com/kubernetes/k8s.io/issues/1597
Needed for https://github.com/kubernetes/k8s.io/issues/1597
=> Rename master to main

README.md
The documentation implies that only pd-standard or pd-ssd can be used, when in fact any pd type is possible.
```release-note
None
```
=> update documentation to show that any PD disk type can be used

CHANGELOG/CHANGELOG-1.3.md
v1.3 changelog
```release-note
None
```
=> CHANGELOG-1.3

test/k8s-integration/cluster.go
/kind bug
kubectl output has changed and our version parsing needs to be updated.
```release-note
None
```
=> Fix kubectl parsing

README.md, deploy/kubernetes/images/stable-master/image.yaml
/kind feature
Put 1.3.0 release into stable-master.
RC passing testgrid (visible google internal only): https://prow-gob.gcpnode.com/view/gcs/gob-prow/logs/periodic-gcp-pd-csi-driver-k8s-integration-staging/1417971893247414272
```release-note
None
```
=> release-1.3 cut details

pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/gce-pd-driver.go
/kind bug
when controller is not in the same zone as nodes, DiskList don't list out disks attached in other zones, thus reconciler will force controllerPublishVolume to reprocess them, causing excessive api calls breaking customer clusters' quotas.
Fixes https://github.com/kubernetes-csi/external-attacher/issues/291
No comment still from arcus team so chose this implementation over `aggregatedList` due to concerns over it being potentially slow for projects with PVs in lots of regions.
```release-note
NONE
```
=> list volumes in cluster's region instead of zone

pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/gce-pd-driver.go
Cherry-pick #813 to release-1.3
Fixes #
```release-note
Fixes issue where `ControllerPublishVolume` is called repeatly if gke nodes are in different cloud zones than the gke controller
```
=> Cherry-pick #813 to release-1.3

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
/kind cleanup
The build is slowly appearing at https://pantheon.corp.google.com/gcr/images/k8s-staging-cloud-provider-gcp/global/gcp-compute-persistent-disk-csi-driver (the windows builds make take a while).
I think we can submit this now, and the build will probably be finished by the time the job kicks off. It will save some time probably, so I can finalize the release tomorrow.
```release-note
None
```
=> Stage v1.3.1-rc1

README.md, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml, deploy/kubernetes/images/stable-master/image.yaml
v1.3.1-rc1 image has passed staging tests, pushing the release now which are appearing in the [repo](https://pantheon.corp.google.com/gcr/images/k8s-staging-cloud-provider-gcp/global/gcp-compute-persistent-disk-csi-driver).
```release-note
None
```
=> Push v1.3.1 release

CHANGELOG/CHANGELOG-1.0.md
=> v1.0.2 release notes

pkg/gce-pd-csi-driver/utils_linux.go, pkg/gce-pd-csi-driver/utils_windows.go, pkg/mount-manager/safe-mounter_linux.go, pkg/mount-manager/safe-mounter_windows.go, pkg/mount-manager/statter_windows.go
/kind bug
Some go versions (at least 1.16) require the legacy +build comments in addition to the new go:build commands. At least, without this change the following error happens when running make with go1.16:
```
go build -mod=vendor -ldflags "-X main.vendorVersion=v1.0.2-0-g5d19516" -o bin/gce-pd-csi-driver ./cmd/
cmd/main.go:28:2: //go:build comment without // +build comment
pkg/gce-pd-csi-driver/gce-pd-driver.go:28:2: //go:build comment without // +build comment
make: *** [gce-pd-driver] Error 1
Makefile:29: recipe for target 'gce-pd-driver' failed
```
/release-note-none
=> Add legacy build directives necessary for some go versions

deploy/kubernetes/images/prow-gke-release-staging-head/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-15/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-16/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml
/kind cleanup
Follow up https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/724
deprecate the `gcr.io/gke-release-staging` and use the images that is promoted to the k8s prod registry or use the images that are built in the staging project
/assign @spiffxp @mattcary 
Fixes #
```release-note
NONE
```
=> replace gcr.io/gke-release-staging to use k8s.gcr.io/cloud-provider-gcp

test/k8s-integration/main.go
Currently when there's version skew the test skip might not work correctly for Generic Ephemeral Volume tests.
Fixes #
```release-note
NONE
```
=> add test skip for Generic Ephemeral Volume tests

pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/utils.go, pkg/gce-pd-csi-driver/utils_linux.go, pkg/gce-pd-csi-driver/utils_windows.go, pkg/mount-manager/safe-mounter_linux.go, pkg/mount-manager/safe-mounter_windows.go, pkg/mount-manager/statter_windows.go, pkg/resizefs/resizefs_linux.go, pkg/resizefs/resizefs_windows.go
By default, XFS does not allow mounting two devices that have the same UUID
of the XFS filesystem. Therefore it's not possible to mount a volume + its
restored snapshot.
Therefore disable UUID check in XFS using a mount option.
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
It is now possible to mount a volume with XFS filesystem and its restored snapshot.
```
=> Cherry pick #788 to release-1.2

Dockerfile, pkg/gce-pd-csi-driver/utils_linux.go, pkg/gce-pd-csi-driver/utils_windows.go, pkg/mount-manager/safe-mounter-v1_windows.go, pkg/mount-manager/safe-mounter-v1beta_windows.go, pkg/mount-manager/safe-mounter_linux.go, pkg/mount-manager/safe-mounter_windows.go, pkg/mount-manager/statter_windows.go, pkg/resizefs/resizefs_linux.go, pkg/resizefs/resizefs_windows.go
/kind bug
```release-note
Update debian image to buster-1.9.0.
```
=> Update buster version to 1.9.0

test/k8s-integration/cluster.go
/kind cleanup
since managed pdcsi driver is out of beta it makes sense to remove the beta flag in `clusterUpGKE`
```release-note
NONE
```
=> removed beta because pdcsi is not only available in beta

deploy/kubernetes/base/node_linux/node.yaml, deploy/kubernetes/base/node_windows/node.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml, deploy/kubernetes/images/stable/image.yaml, deploy/kubernetes/overlays/stable-1-17/kustomization.yaml, deploy/kubernetes/overlays/stable-1-17/no-node-driver-registrar-probe.yaml, deploy/kubernetes/overlays/stable-1-18/kustomization.yaml, deploy/kubernetes/overlays/stable-1-18/no-node-driver-registrar-probe.yaml, deploy/kubernetes/overlays/stable-1-19/kustomization.yaml, deploy/kubernetes/overlays/stable-1-19/no-node-driver-registrar-probe.yaml, deploy/kubernetes/overlays/stable-master/kustomization.yaml, deploy/kubernetes/overlays/stable-master/no-node-driver-registrar-probe.yaml
/kind feature
Adds support for https://github.com/kubernetes-csi/node-driver-registrar/pull/152 on Windows & Linux nodes, I tried patching previous releases to remove the probe configuration because it was introduced in node-driver-registrar v2.3.0
The output for `kustomize build deploy/kubernetes/overlays/stable-1-19` is ok (liveness probe should be removed because the version is less than v2.3.0): 
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
name: csi-gce-pd-node-win
namespace: gce-pd-csi-driver
spec:
selector:
matchLabels:
app: gcp-compute-persistent-disk-csi-driver
template:
metadata: …
```
=> Enable kubelet-registration-probe mode in node-driver-registrar in Windows & Linux

pkg/gce-cloud-provider/compute/cloud-disk.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, test/k8s-integration/driver-config.go, test/k8s-integration/main.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
This PR implements volume cloning. 
Fixes #https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/161
```release-note
Enables volume cloning.
```
=> Volume cloning feature

Dockerfile, Dockerfile.arm64, Makefile
/kind feature
We are changing pdcsi driver to be built from distroless base image instead of debian. Distroless images are much smaller as they only contain your application and its runtime dependencies. Restricting what's in your runtime container is a best practice, and it improves the signal to noise of scanners (e.g. CVE). See [distroless](https://github.com/GoogleContainerTools/distroless) for more information. 
Fixes #
```release-note
NONE
```
=> Change to distroless base image

release-tools/README.md, release-tools/SECURITY_CONTACTS, release-tools/SIDECAR_RELEASE_PROCESS.md, release-tools/build.make, release-tools/cloudbuild.yaml, release-tools/go-get-kubernetes.sh, release-tools/prow.sh
Squashed 'release-tools/' changes from c0a4fb1d..a6a1a797
[a6a1a797](https://github.com/kubernetes-csi/csi-release-tools/commit/a6a1a797) Merge [pull request #176](https://github.com/kubernetes-csi/csi-release-tools/pull/176) from pohly/go-1.17.3
[0a2cf636](https://github.com/kubernetes-csi/csi-release-tools/commit/0a2cf636) prow.sh: bump Go to 1.17.3
[fc29fdde](https://github.com/kubernetes-csi/csi-release-tools/commit/fc29fdde) Merge [pull request #141](https://github.com/kubernetes-csi/csi-release-tools/pull/141) from pohly/prune-replace-optional
[5b9a1e06](https://github.com/kubernetes-csi/csi-release-tools/commit/5b9a1e06) Merge [pull request #175](https://github.com/kubernetes-csi/csi-release-tools/pull/175) from jimdaga/patch-1 …
=> master: update release-tools

pkg/gce-cloud-provider/compute/gce-compute.go
/kind bug
This PR logs operation id for each PD disk operations attempt in order to help debug attach/detach errors by making it more clear which retry attempt of the driver the error was part of. Logging the operation id in the driver helps map the audit, and the driver CSI call execution.
Fixes #
```release-note
NONE
```
=> Log operation id for attach and detach

deploy/kubernetes/images/alpha/image.yaml, deploy/kubernetes/images/alpha/kustomization.yaml, deploy/kubernetes/overlays/alpha/controller_readonly.yaml, deploy/kubernetes/overlays/alpha/kustomization.yaml, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/utils.go, pkg/gce-pd-csi-driver/utils_test.go
turn on controller-publish-readonly flag  and add validation in pd-csi driver for when readonly is on
if mounting a read-only ext3 or ext4 disk, use `noload` to prevent mount failure caused by journal replay 
/kind feature
when ROX accessMode is specified, csi.Readonly is currently not set. this PR fix that, and at the same time validate that a content source is set when readonly modes are specified at provision time.
Fixes #872
```release-note
Dynamically provisioning for Read only PVs will fail now unless a volume source (either restore from snapshot or volume cloning) is specified. 
```
=> pdcsi rox workflow fix

test/k8s-integration/config/test-config-template.in, test/k8s-integration/driver-config.go, test/k8s-integration/main.go
This PR enables the kubernetes e2e tests for volume cloning. We skipped the volume cloning tests previously because changes to the [kubernetes e2e tests](https://github.com/kubernetes/kubernetes/pull/106322) was necessary first.  
Fixes #161
```release-note
NONE
```
=> Enable Kubernetes e2e tests for volume cloning

test/k8s-integration/cluster.go, test/k8s-integration/main.go
Upstream binary and code archives have drifted from what we had been using. This fixes it.
```release-note
None
```
=> Update version download for current upstream capabilities

test/k8s-integration/main.go
The volume cloning tests are fixed in head, but we need these test skips until we backport them (see https://github.com/kubernetes/kubernetes/pull/106322).
I've tested this PR with a local integration test run.
```release-note
None
```
=> skip volume cloning tests until we backport

go.mod, go.sum, vendor/modules.txt
/kind feature
To support symlink validation for NVMe, we need the google_nvme_id scripts and rules from GCP guest configs repro. This PR is to add the guest configs repro as dependency. Will upload the script and rules to pd csi driver image in next PR.
=> Add guest-configs to go.mod

deploy/setup-project.sh
/kind cleanup
This adds a flag to deploy/setup-project.sh which skips creating SA keys. This is useful when setting up a project when using the noauth overlay, and creating SA keys is not necessary.
Fixes #639
N/A
```release-note
NONE
```
=> Add CREATE_SA_KEY flag to deploy/setup-project.sh

Dockerfile.arm64
post-gcp-compute-persistent-disk-csi-driver-push-images  test failed because the image build was not able to find "/lib/udev/scsi_id". 
```release-note
NONE
```
=> Cherry pick #884 to release-1.4

test/k8s-integration/fs.go, test/k8s-integration/main.go
>
/kind bug
When the kubetest2 flags are created it'll detect if we're trying to run the e2e test from master, if so then it'll assume that the cluster was created by compiling a kubernetes release or kubernetes master and that the binaries to use in the e2e tests should be the ones generated during the compilation.
Might help https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/892
```release-note
NONE
```
/cc @mattcary @jingxu97
=> Use the compiled kubernetes binaries in the e2e tests in CI

test/k8s-integration/cluster.go, test/k8s-integration/main.go, test/k8s-integration/utils.go, test/run-k8s-integration-ci.sh, test/run-k8s-integration.sh, test/run-windows-k8s-integration.sh, test/run-windows-k8s-migration.sh
/kind cleanup
/kind feature
Unifies the build/test strategy of OSS GCE PD CSI Driver for Linux and Windows
Implementation steps:
- Update the shell script for Windows CI runs setting `--kube-version=master --bringup-cluster=true --teardown-cluster=true`, that way the k8s-integration binary will download and compile the kubernetes codebase, bringup and teardown the cluster.
- Changes to k8s-integration
- Remove the condition to get a project from Boskos only for Linux, this should apply to Windows too
- During the cluster bootstrap add a variable to control the number of Windows nodes in addition to …
=> Unify the build/test strategy of OSS GCE PD CSI Driver for Linux and Windows

test/run-windows-k8s-integration.sh, test/run-windows-k8s-migration.sh
>
/kind bug
The CI scripts for Windows integration passed! However I saw that the migration job failed, I think we should run the k8s-integration-test binary without eval, hopefully this is the last PR about making both Linux and Windows build strategies to be the same.
```release-note
NONE
```
/cc @mattcary @jingxu97
=> Run the k8s-integration-test binary without eval

test/run-windows-k8s-migration.sh
>
/kind bug
Found out that `--kube-feature-gates` is not used anywhere in the test runner, instead the flag that runs the migration tests is `--migration-test=true`
Might probably need a followup PR to remove the flag `--kube-feature-gates` (which should be the env var KUBE_FEATURE_GATES).
Also the migration scripts for Linux and Windows are the same aside from the flags `--platform=windows --num-windows-nodes="${num_windows_nodes} --storageclass-files=sc-windows.yaml" and `export KUBE_BUILD_PLATFORMS=${KUBE_BUILD_PLATFORMS:-"linux/amd64 windows/amd64"}`, probably another followup PR is to have a …
=> Add missing --migration-test=true flag

pkg/common/cache.go, pkg/common/cache_test.go, pkg/common/utils.go, pkg/common/utils_test.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, pkg/gce-pd-csi-driver/gce-pd-driver_test.go, pkg/gce-pd-csi-driver/ops_manager.go, vendor/k8s.io/client-go/util/retry/OWNERS, vendor/k8s.io/client-go/util/retry/util.go, vendor/modules.txt
>
> /kind bug
> /kind design
/kind feature
> /kind flake
This PR changes the queuing behavior of ControllerPublish/Unpublish. The controller will try to ensure at max 1 attach or detach running operation for a given PD on a given instance. 
The Controller maintains two in-memory maps 
1. last known running attach detach ops for a disk on a given instance
2. last known running ops for an instance  (this map is needed to handle the driver restart scenario)
These maps are checked before initiating a new controller …
=> Ensure max one running attach/detach operation for a given disk on an instance

docs/kubernetes/user-guides/snapshots.md
>
> /kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: this fixes a documentation that doesn't accomplish the goal of creating a volume snapshot from an existing snapshot
**Which issue(s) this PR fixes**: Fixes #913 
Fixes #
**Does this PR introduce a user-facing change?**: NONE
```release-note
```
=> fixes kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#913

Dockerfile, Dockerfile.Windows, Dockerfile.arm64
/kind cleanup
Update golang version for building drivers.
```release-note
None
```
=> golang:1.17.8

pkg/common/parameters.go, pkg/common/parameters_test.go, pkg/common/utils.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go
/kind feature
fixes
Fixes https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/924
```release-note
Add parameters to VolumeSnapshotClass for disk image config.
```
=> Add disk image snapshot support

deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
/kind cleanup
Update staging with new sidecar versions. After the [staging prow](https://testgrid.corp.google.com/gcp-compute-persistent-disk-csi-driver#pd-master-sidecars-staging-k8s-master-on-gce) (internal google only), which was recently moved to the OSS testgrid [here](https://testgrid.k8s.io/provider-gcp-compute-persistent-disk-csi-driver#Kubernetes%20Master%20Driver%20Latest%20Canary%20Sidecars), is green. 
/assign @mattcary 
```release-note
None
```
=> Upgrade csi snapshotter to v4.1.1 in release testing

Dockerfile, Dockerfile.arm64, pkg/mount-manager/device-utils.go, pkg/mount-manager/device-utils_test.go, test/e2e/tests/setup_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/utils/utils.go, test/remote/instance.go
/kind feature
**What this PR does / why we need it**: This PR adds support for NVMe persistent disks to GCP PD CSI Driver. Currently only SCSI disks are supported.
```release-note
Add support for NVMe persistent disks
```
=> Add support for NVMe to NodePublishVolume

Dockerfile, Dockerfile.Windows
Cherry pick of #930 on release-1.2.
#930: golang:1.17.8
```release-note
None
```
=> Automated cherry pick of #930: golang:1.17.8

CHANGELOG/CHANGELOG-1.3.md
**What this PR does / why we need it**: Changelog for patch release 1.3.6
**Does this PR introduce a user-facing change?**: No
```release-note
NONE
```
=> Add changelog for 1.3.6

pkg/gce-pd-csi-driver/controller.go
Change-Id: Ia4933278dba561697abccff8a6e0bc8ab0b98cc4
>
> /kind bug
> /kind design
> /kind flake
This fix is needed in this feature testing branch to make the next set of changes for backoff logic fix
Fixes #
```release-note
NONE
```
=> cherrypick #943 - Return error when queued

pkg/gce-pd-csi-driver/controller.go
>
/kind bug
> /kind design
> /kind flake
Fix the error code during controllerunpublish backoff and use a local context when queuing a workitem.
Fixes #
```release-note
Fix ControllerUnpublish backoff
```
=> Fix ControllerUnpublish backoff

pkg/common/parameters.go, pkg/common/parameters_test.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, test/e2e/tests/single_zone_e2e_test.go
/kind feature
This PR adds metadata in the description field for Snapshots and Images created from the CreateSnapshot CSI method when the external-snapshotter is run with the `--extra-create-metadata` flag.
Fixes #695 
```release-note
Description field for Images and Snapshots will be filled with JSON encoded metadata containing the name and namespace of the VolumeSnapshot and the name of the VolumeSnapshot content.
```
=> Add support for extra-create-metadata when creating snapshots

pkg/gce-cloud-provider/compute/cloud-disk.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go, test/e2e/tests/single_zone_e2e_test.go, test/k8s-integration/config/image-volumesnapshotclass.yaml, test/k8s-integration/config/test-config-template.in, test/k8s-integration/driver-config.go, test/k8s-integration/main.go, test/run-k8s-integration-ci.sh, test/run-k8s-integration-local.sh, test/run-k8s-integration.sh, test/run-windows-k8s-integration.sh, test/run-windows-k8s-migration.sh
/kind feature
Fixes #924 
```release-note
N/A
```
=> Add e2e/integration tests for image snapshot

cmd/gce-pd-csi-driver/main.go, pkg/gce-cloud-provider/compute/gce-compute.go
/kind feature
Currently poll time for attach disk or global\regional\zonal operation is hard coded:
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/9681ab1fa79bce8e7a33ad308e2ae96dd388a088/pkg/gce-cloud-provider/compute/gce-compute.go#L781
For example, for attach disk it is hard coded to wait at least 5 seconds before checking if disk was attached.
For our [project](https://gitpod.io) we need to be able to attach disk as fast as possible, and usually it is attached extremely fast (less than 1 second). So we need to be able to poll faster.
This PR allows to do that via providing parameters as command line arguments that allow you to change how often we poll for changes.
Default parameters …
=> allow to specify wait time for attach disk operation

pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, pkg/gce-pd-csi-driver/ops_manager.go, pkg/gce-pd-csi-driver/utils.go, vendor/modules.txt
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This PR aims to simply the node backoff logic by removing the worker based backoff queue, to a simple map which tracks the active backoff condition per node. Removing the worker, removes dual sources of controller publish/unpublish calls (one from side car, one from the queue worker), and potential out of order execution of attach/detach disks operations.
Fixes #
Tested manually by running multiple …
=> Simplify the node backoff logic

pkg/gce-pd-csi-driver/node.go
/kind cleanup
Use existing error message format (common.VolumeOperationAlreadyExistsFmt) instead of duplicating its content.
```release-note
NONE
```
=> Use existing error message format

test/e2e/tests/setup_e2e_test.go, test/remote/instance.go, test/remote/setup-teardown.go
>
> /kind bug
kind cleanup
> /kind design
> /kind flake
Fixes #944 
```release-note
NONE
```
=> Add flags to specify zone/machine-type/OS image

test/k8s-integration/prepull.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Updates the agnhost image version to be the same one as the one used in the tests, the version was taken from https://github.com/kubernetes/kubernetes/blob/537941765fe1304dd096c1a2d4d4e70f10768218/test/utils/image/manifest.go#L234
Related with the CI issue https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/892 in the Windows e2e tests
```release-note
NONE …
```
=> Update agnhost image to match the one used in the tests

cmd/gce-pd-csi-driver/main.go
/kind bug
Fixes #968 
```release-note
Default to MAXPROCS=1 to improve memory usage on nodes with many CPUs.
```
=> override maxprocs, defaulting to 1

Makefile, test/e2e/tests/setup_e2e_test.go, test/remote/archiver.go, test/remote/instance.go, test/remote/setup-teardown.go, test/run-e2e-local.sh
>
> /kind bug
kind cleanup
> /kind design
> /kind flake
Fixes #944 
```release-note
NONE
```
=> Add functionality to make architecture specific builds

test/k8s-integration/driver-config.go, test/k8s-integration/main.go, test/run-k8s-integration-ci.sh
Running all snapshot classes with all storage class is causing timeouts. Running the snapshot tests with just one storageclass does not substantially reduce the test coverage.
```release-note
None
```
=> Run snapshot class tests separately from other tests

Makefile, test/k8s-integration/prepull-image.sh
>
> /kind bug
> /kind design
> /kind flake
Increases the agnhost image pull timeout from 15m to 30m, ref this comment https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/892#issuecomment-1117599792, it also fixes doing builds on the windows binary.
```release-note
NONE
```
/cc @mattcary @DW2022511
=> Increase prepull image timeout

test/k8s-integration/main.go
Improves #981
```release-note
None
```
=> really fix pvc.data.source skip

pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, pkg/gce-pd-csi-driver/gce-pd-driver_test.go, test/e2e/tests/single_zone_e2e_test.go
>
/kind bug
> /kind design
> /kind flake
This PR simplifies the node backoff logic and removes the backoff queue which processes requests asynchronously.
Instead in this PR, the node is marked with a backoff condition on any new error. Similarly any successful attach or detach disk op would clear the backoff condition.  The backoff behavior scenarios are captured in this [doc](https://docs.google.com/document/d/138UQqyIbuWQ3xc_3fCXaI7MzKX_veNJe1bdWZ1ZZIcg/edit?resourcekey=0-f3uGOrMCZcmsd-v6meapFQ) for …
=> Simplify node backoff logic for controller publish/unpublish op

CHANGELOG/CHANGELOG-1.7.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
CHANGELOG for 1.7
```
=> CHANGELOG for 1.7

manifest_osversion.sh
>
/kind bug
It looks like a recent version of docker in CI is adding `os.version` so the workaround to add it on our own is no longer needed, this was causing a double `os.version` to be added to the manifest as seen here:
```
I0512 18:36:46.423] {"Ref":"gcr.io/gce-cvm-upg-lat-1-3-ctl-skew/gcp-persistent-disk-csi-driver:d5486a25-280b-4d7e-a899-98a3f37b0818_ltsc2019","Descriptor":{"mediaType":"application/vnd.docker.distribution.manifest.v2+json","digest":"sha256:cb0b111aba51dfdfcf8fcdec778c20c3bf153c9180bcbaf597c7a5f58c886794","size":956,"platform":{"architecture":"amd64","os":"windows","os.version":" …
```
=> Remove workaround to add os.version to the manifest for Windows images

manifest_osversion.sh
Cherry pick of #986 on release-1.7.
#986: Remove workaround to add os.version to the manifest for
**Does this PR introduce a user-facing change?:**
```release-note
NONE
```
=> Automated cherry pick of #986: Remove workaround to add os.version to the manifest for

Dockerfile, Makefile, hack/print-missing-deps.sh, hack/verify-docker-deps.sh
/kind test
**What this PR does / why we need it**: This uses ldd on the target architecture (amd64/arm64) to validate if all direct and indirect dependencies of a program. The underlying logic leverages ldd to find dependencies that are "not found". This is helpful to catch in presubmit issues where all the runtime libs were not included. See #974 as an example of this.
```release-note
NONE
```
=> Add Makefile target that validates the Dockerfile images contain the correct shared library dependencies

pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go
Cherry pick of #999 on release-1.7.
#999: Add implicit ListVolumesResponse#Entry pagination limit
```release-note
Enforce implicit pagination limit of 500 of the ListVolumesResponse#Entry field when ListVolumesRequest#max_entries is not set
```
=> Automated cherry pick of #999: Add implicit ListVolumesResponse#Entry pagination limit

CHANGELOG/CHANGELOG-1.7.md, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> 1.7 CHANGELOG, update rc image and sidecar versions

cmd/gce-pd-csi-driver/main.go
Backport #969, which fixes memory issues (See #968).
/kind bug
```release-note
Backport of memory usage fix #969 for #968 (by setting go maxprocs to 1)
```
=> Backport maxprocs (#969)

test/run-k8s-integration-ci.sh, test/run-k8s-integration-migration.sh, test/run-k8s-integration.sh
Pin kubetest2 version, as recent changes break the version of ginkgo we're using.
/assign @leiyiz
=> Pin kubetest2 version

pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/gce-pd-driver.go
I'll create an issue on this repo and update this message to point to it.
/kind bug
Fixes #1029
```release-note
Improve backoff to be per-node and disk to avoid missing disks from blocking all operations
```
=> backoff per {node,disk} pair instead of just node}

deploy/kubernetes/base/node_linux/node.yaml, deploy/kubernetes/base/node_windows/node.yaml
>
/kind cleanup
The root cause for the kubelet registration issue was found in https://github.com/kubernetes/kubernetes/issues/104584, with that there's no need for this workaround.
```release-note
NONE
```
=> Remove livenessprobe from node-driver-registrar

pkg/common/parameters.go, pkg/common/parameters_test.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go
/kind feature
This PR adds support for adding labels to snapshots, similar how it can be done with disks via storage class parameters.
_Why is it needed?_
We use labels to calculate costs inside our GCP project, this PR allows us to set custom labels on snapshots to properly count them for cost calculations.
_How to test?_
Add `parameters` to your `VolumeSnapshotClass` like so:
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
name: csi-gce-pd-snapshot-class
parameters:
labels: cluster=preview,region=us,custom-label=awesome
driver: pd.csi.storage.gke.io
deletionPolicy: Delete
```
When snapshot is created, observe that labels were added to it in GCP console: …
=> add support for setting snapshot labels

test/k8s-integration/main.go
/assign @leiyiz 
```release-note
None
```
=> Skip node skew tests using ephemeral containers

Dockerfile
/kind cleanup
```release-note
Go builder updated from 1.17 to 1.18.4. This fixes several CVEs, CVE-2022-24675, CVE-2022-28327, CVE-2022-2068.
```
/assign @leiyiz
=> update go builder to 1.18.4

Dockerfile
Cherrypick of #1031
/kind cleanup
```release-note
Update golang to 1.18.4
```
=> Cherry-pick #1031: update go to 1.18

Dockerfile
/kind cleanup
Pick up 1.18.4 golang and update image to bullseye 1.4.1.
```release-note
Update to go1.18.4 and base image to bullseye-v1.4.1 to fix CVE-2022-1271, CVE-2022-1664, CVE-2022-24675, CVE-2022-34903, CVE-2018-25032, CVE-2022-28327, CVE-2021-43618
```
=> Update golang and base image

pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/node_test.go, test/k8s-integration/main.go, test/k8s-integration/version.go, test/k8s-integration/version_test.go
This fixes test failures in GKE stable.
/assign @amacaskill 
```release-note
None
```
=> Skip disk image tests before 1.21

Dockerfile
/kind cleanup
```release-note
Docker base image updated to k8s.gcr.io/build-image/debian-base:bullseye-v1.4.2
```
=> Update base to bullseye-1.4.2

test/run-windows-k8s-integration.sh, test/run-windows-k8s-migration.sh
Fixes the kubetest2 version in Windows tests just like the Linux tests.
Ref https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1024
Attempts to solve #880
```release-note
NONE
```
/cc @alexander-ding @mattcary
=> Fix the kubetest version to 0e09086b60c122e1084edd2368d3d27fe36f384f

pkg/gce-cloud-provider/compute/gce-compute.go
/kind bug
Currently regional disks are not being listed out when ListDisk is called. Causing them to all be queued for re-attach, potentially causing quota issues.
Fixes #
manually tested and confirmed that the disk is listed out: 
```
/csi.v1.Controller/ListVolumes returned with response: entries:<volume:<volume_id:"projects/leiyi-k8s-testing/regions/us-central1/disks/pvc-416d2e20-136d-4e7b-a332-2df2546d398d" > status:<published_node_ids:"projects/leiyi-k8s-testing/zones/us-central1-c/instances/gke-test-cluster-rapid-default-pool-8dc50175-s6hw" > > ...
```
```release-note
Fixed issue where Regional …
```
=> list out regional PD in listDisk Call

pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/utils_windows.go, pkg/mount-manager/device-utils.go, pkg/mount-manager/device-utils_linux.go, pkg/mount-manager/device-utils_windows.go, pkg/mount-manager/fake-device-utils.go
/kind bug
We have learned that not disabling a device before detaching it can lead to device and VM instability. 
```release-note
Disable devices in node unstage prior to detaching.
```
=> Disable device when unstaging

test/k8s-integration/cluster.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
To fix the PD CSI k8s-integration tests in staging2 env.
For some reason, the staging2 API `staging2-container.sandbox.googleapis.com` was not enabled in some of the Prow projects, which causes the test failures. Adding this logic to make sure the service API is enabled before the cluster creation starts.
Fixes #
For Google reviewer, see [b/254660690](b/254660690) for details.
**Does …
=> Enable GKE service API before the cluster creation

pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go, pkg/resizefs/resizefs_linux.go, test/e2e/tests/resize_e2e_test.go
/kind bug
Volume filesystem size is not expanded during clone if pvc data source is larger than original volume.
Similarly when restoring a snapshot to a pvc with larger size the filesystem is not expanded either.
This patch uses mount-utils to handle volume size check and resizing.
Fixes #784
Here is how I verified the patch manually.
BEFORE PATCH:
```
1.Create pvc with 1Gi/pod
2.Create clone pvc with 5Gi/pod
$ oc get pvc/clone-of-pvc-1 -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
annotations:
pv.kubernetes.io/bind-completed: "yes"
pv.kubernetes.io/bound-by-controller: "yes"
volume.beta.kubernetes.io/storage-provisioner: …
```
=> filesystem is not resized when restoring from snapshot/cloning to larger size than origin

pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, test/k8s-integration/config/image-volumesnapshotclass.yaml, test/k8s-integration/config/pd-volumesnapshotclass.yaml
/kind feature
We use labels to filter the GCP images.
Fixes #
Add parameters to your VolumeSnapshotClass like so:
```yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
name: csi-gce-pd-snapshot-class
parameters:
labels: cluster=preview,region=us,custom-label=awesome
snapshot-type: images
driver: pd.csi.storage.gke.io
deletionPolicy: Delete
```
```release-note
Support setting snapshot labels to Images
```
=> Support add the snapshot labels to images

pkg/mount-manager/device-utils.go
>
> /kind bug
> /kind design
> /kind flake
Debug log for the mapping of a PD name to /dev/* path.
N/A
Debug log to help triage issues
N/A
=> Add debugging log for the mapping of a PD name to /dev/* path

test/k8s-integration/version.go, test/k8s-integration/version_test.go
=> Update version parsing for beta prereleases

Dockerfile
/kind bug
Address the error message
```console
udevadmChangeToDrive: udevadm trigger failed for drive "/dev/sdh" with output : exec: "udevadm": executable file not found in $PATH.
```
Fixes #
The udevadm binary does not exist in the container image.
```release-note
Add udevadm binary in the container image.
```
=> Add udevadm binary to container image

cmd/gce-pd-csi-driver/main.go, pkg/gce-cloud-provider/compute/gce.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, test/e2e/tests/setup_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/utils/utils.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Adds ability to pick up compute endpoint from compute-endpoint flag rather than using hard-coded value. This is needed to achieve service regionalization
Fixes #
This is my first change so still working out which tests to run.
```release-note
NONE
```
=> Add compute-endpoint flag to pdcsi driver

pkg/gce-cloud-provider/compute/gce.go, test/e2e/tests/single_zone_e2e_test.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
This is a follow up to github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1077 which added a configurable compute endpoint to pdcsi driver. It adds the /compute/{beta/v1} suffix to the endpoint since we can't expect that from the caller.
Fixes #
```release-note
NONE
```
=> add beta/v1 suffix to passed-in compute endpoint

Dockerfile.debug
/kind bug
**What does the PR do?**
The Debug Dockerfile doesn't copy the built binary into the final image. Adding a single line to fix
```release-note
NONE
```
=> fix: copy compiled binary into final image

docs/kubernetes/development.md
>
> /kind bug
> /kind design
> /kind flake
Adds some basic instruction on how to run performance tests.
```release-note
NONE
```
/cc @mauriciopoppe 
/cc @mattcary
=> Add note about how to run performance test

cmd/gce-pd-csi-driver/main.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, pkg/gce-pd-csi-driver/gce-pd-driver_test.go, test/sanity/sanity_test.go
>
> /kind bug
> /kind design
> /kind flake
The [scenario of the failing test](https://github.com/kubernetes-csi/csi-test/blob/master/pkg/sanity/controller.go#L1001)  ("should fail when the volume is already published but is incompatible"):
1. We create a volume -> succeeds
2. We publish that volume -> succeeds
3. We re-publish that volume, expecting an error bc it was already published -> fails (and triggers backoff)
4. [Cleanup function](https://github.com/kubernetes-csi/csi-test/blob/e3d351ac3db771d36893f3ee7 …
=> Lower threshold on backoff for sanity tests

cmd/gce-pd-csi-driver/main.go, pkg/deviceutils/device-utils.go, pkg/deviceutils/device-utils_linux.go, pkg/deviceutils/device-utils_test.go, pkg/deviceutils/device-utils_windows.go, pkg/deviceutils/fake-device-utils.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go, test/e2e/tests/single_zone_e2e_test.go, test/sanity/sanity_test.go
>
> /kind bug
> /kind design
> /kind flake
Our sanity tests are currently failing 4 test cases: 1 because of go/pdcsi-oss-driver/issues/990 to be addressed in a follow up in another repo, and 3 others with the error:
```
Could not determine if filesystem \"/tmp/csi/stage\" needs to be resized: failed to parse size of device /dev/disk/fake-path
```
This PR fixes the latter 3 failures by mocking out the resize method.
Note this also required moving deviceutils into its own pkg to avoid a circular dependency from …
=> Fix resize-related sanity test failures

cmd/gce-pd-csi-driver/main.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, pkg/gce-pd-csi-driver/utils.go, test/sanity/sanity_test.go
/kind bug
ListVolume call generates tons of log items because by default the entirety of the grpc response body gets logged out. That consumes log space really fast and we want to limit how much can be logged in the same message.
This might impact some visibility into what's going on with ListVolume call.
Fixes #
didn't find obvious way to make the log limit configurable. Pls advise of otherwise
```release-note
Logging for gRPC call is now limited to 10000 char by default, and configurable with flag --grpc-log-char-cap
```
=> limit grpc logging info to a configurable character limit

pkg/common/parameters.go, pkg/common/parameters_test.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
The PR adds namespace and PVC names as labels to PVs
Fixes #1064
Yes
```release-note
Adding auto-stamped details like PV, PVC and namespace name from PV description as labels for the PVs/PDs
```
=> added labels for namespace and pvc names for a pv

test/sanity/sanity_test.go
>
> /kind bug
> /kind design
kind failing-test
> /kind flake
Lower threshold for backoff in pd sanity tests
This is a follow up to https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1087. It lowers the threshold for backoff in sanity tests even more since we were seeing flakes in some PR gating tests, namely https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1092.
I will run the sanity tests a few times in this CL before merging.
Fixes # …
=> Disable per volume backoff behavior for sanity tests

Dockerfile
Cherry pick of #1072 on release-1.7.
#1072: Add udevadm to container image
```release-note
Add udevadm binary in the container image.
```
=> Automated cherry pick of #1072: Add udevadm to container image

cmd/gce-pd-csi-driver/main.go
/kind bug
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1087 added a flag for max backoff threshold in ms but it converts it to microseconds rather than milliseconds. This fixes that.
Fixes #
```release-note
NONE
```
=> Fix micro > milli max backoff bug

test/k8s-integration/config/image-volumesnapshotclass.yaml, test/k8s-integration/config/pd-volumesnapshotclass.yaml
This is not supported by older versions and causes tests to fail on clusters not using the most recent driver which supports snapshot labels.
```release-note
None
```
=> Remove labels from test snapshot class

README.md, go.mod, go.sum, pkg/common/parameters.go, pkg/common/parameters_test.go, pkg/common/utils.go, pkg/common/utils_test.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller_test.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/tests/single_zone_pd_extreme_e2e_test.go, test/k8s-integration/config/sc-extreme.yaml, test/k8s-integration/driver-config.go, test/k8s-integration/main.go, vendor/k8s.io/cloud-provider/LICENSE, vendor/k8s.io/cloud-provider/volume/constants.go, vendor/k8s.io/cloud-provider/volume/helpers/rounding.go, vendor/k8s.io/cloud-provider/volume/helpers/zones.go, vendor/modules.txt
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Support pd-extreme with provisionedIops, please see [pd-extreme](https://cloud.google.com/compute/docs/disks/extreme-persistent-disk)
Fixes #
The current pd-extreme [restrictions](https://cloud.google.com/compute/docs/disks/extreme-persistent-disk):
* Extreme persistent disks are zonal only. You cannot create regional extreme persistent disks.
* You cannot attach multiple VM instances in read-only …
=> Add provisionedIops for pd-extreme

cmd/gce-pd-csi-driver/main.go, pkg/deviceutils/device-utils.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce.go, pkg/gce-cloud-provider/metadata/metadata.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/server.go, pkg/gce-pd-csi-driver/utils.go, pkg/gce-pd-csi-driver/utils_linux.go, pkg/gce-pd-csi-driver/utils_test.go, pkg/gce-pd-csi-driver/utils_windows.go, pkg/metrics/metrics.go, pkg/mount-manager/safe-mounter_windows.go, pkg/mount-manager/statter_linux.go, test/k8s-integration/cluster.go, test/remote/ssh.go, test/sanity/sanity_test.go
>
/kind bug
> /kind design
> /kind flake
Exclude user errors for googleapis from codes.internal errors for better error categorization
Conversation from https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1084
Fixes #
You are reviewing three different things:
1. fmt.Errorf should use %w for errors
2. logging should use %v for err, or err.Error() with err nil check
3. simplifying status.Error to status.Errorf to …
=> Separate user errors from internal errors

docs/kubernetes/user-guides/driver-install.md
Currently there is no `stable` overlay available, example in README should use [`stable-master`](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/tree/master/deploy/kubernetes/overlays/stable-master) instead.
>
> /kind bug
> /kind design
> /kind flake
Fixes incorrect documentation for installing the driver.
Fixes #
NONE
```release-note
```
=> Fix incorrect example in installation README

Dockerfile, Dockerfile.Windows, Dockerfile.debug
Cherry pick of #1103 on release-1.8.
#1103: Update go version to the latest
```release-note
```
=> Automated cherry pick of #1103: Update go version to the latest

README.md, pkg/common/parameters.go, pkg/common/parameters_test.go, pkg/common/utils.go, pkg/common/utils_test.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller_test.go, test/e2e/tests/setup_e2e_test.go, test/remote/instance.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Support hyperdisk-throughput  with provisionedThroughput
Fixes #
TBD for hyperdisk-throughput public documentation
```release-note
NONE
```
=> Add provisionedThroughput for hyperdisk-throughput 

test/e2e/tests/multi_zone_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/utils/utils.go, test/k8s-integration/cluster.go, test/k8s-integration/driver.go, test/k8s-integration/main.go, test/remote/archiver.go, test/remote/client-wrappers.go, test/remote/instance.go, test/remote/runner.go, test/remote/setup-teardown.go, test/remote/ssh.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Clean up error logging/unwrapping in test for potential test retries.
Fixes #
```release-note
NONE
```
=> Clean up error logging in test

cmd/gce-pd-csi-driver/main.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, pkg/gce-pd-csi-driver/gce-pd-driver_test.go, pkg/gce-pd-csi-driver/utils.go, test/sanity/sanity_test.go
>
> /kind bug
> /kind design
> /kind flake
cherry pick #1085 to be included in release-1.8
sanity tests are failing so picking #1087 and #1094 in as well.
Fixes #
```release-note
Logging for gRPC call is now limited to 10000 char by default, and configurable with flag --grpc-log-char-cap
```
=> cherry pick #1085 #1087 and #1094 to release-1.8

Makefile
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
If the binary is built on a machine with different ```ldd --version``` as the machine the binary is running on, you may run into issues with ```GLIBC_x.xx not found ```, building it statically resolve the issue.
Fixes #
```release-note
NONE
```
=> Build binary by statically linking go

deploy/setup-project.sh, docs/kubernetes/development.md
/kind cleanup
CMEK e2e tests fail if they are unable to destroy a KMS key. This PR adds a project setup flag to add the required SA permissions. With this change, I am now able to run local e2e test with zero failures.
🎉
```release-note
NONE
```
=> Fix kms permissions for local e2e tests

pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, test/e2e/tests/setup_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/tests/single_zone_pd_extreme_e2e_test.go, test/remote/instance.go
/kind bug
This PR specifically targets non-existent zonal disks with underspecified volume IDs. The case of missing nodes and missing PDs with fully specified volume IDs already succeeds the unpublish step.
- Add test case for fully specified, not found PDs during unpublish.
- Clean up the testing structure by introducing a backoffTestDriver generator, which can be reused by both publish and unpublish tests.
- Remove redundant comments from the test code.
Fixes #1108 
**Release note:**
```release-note
NONE
```
=> Succeed unpublish when a zonal, underspecified PD is not found

Makefile
>
/kind bug
> /kind design
> /kind flake
CI started failing for Windows in the `build-and-push-multi-arch` step, after looking into the logs it failed to build the linux/arm64 image, I'm removing it from the OSS Windows CI tests.
I think we might have problems building the linux/arm64 image internally the next time there's a release, just an FYI.
Relevant logs:
```
W0121 03:11:25.673] #14 [builder 4/4] RUN GOARCH=$(echo linux/amd64 | cut -f2 -d '/') …
```
=> Remove linux/arm64 from Windows multi-arch builds

Makefile
>
/kind bug
> /kind design
> /kind flake
There are a few lines that still need to be deleted, followup of #1124  
```release-note
NONE
```
/cc @mattcary
=> fix: remove linux/arm64 and windows/amd64 20h2 from multi-arch build

Makefile
>
> /kind bug
> /kind design
> /kind flake
Followup of #1124 and #1126. In https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-gce-pd-csi-driver-latest-k8s-master-windows-2019/1622984251899121664  `docker manifest create` is failing with 
```
I0207 11:50:07.220] DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create --amend gcr.io/e2e-gce-gci-ci-master/gcp-persistent-disk-csi-driver:ec610dec-b6e3-4e8e-b3ed-28dbf81dd659 gcr.io/e2e-gce-gci-ci-master/gcp-persistent-disk-csi-driver:ec610dec-b6e3-4e8e-b3ed-28db …
```
=> Pin the buildkit version to v0.10.6

CHANGELOG/CHANGELOG-1.9.md, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
For release-1.9
Fixes #
```release-note
NONE
```
=> Add change log for release-1.9

pkg/gce-pd-csi-driver/controller.go
Cherry pick of #1134 on release-1.9.
#1134: Remove debug.PrintStack()
```release-note
NONE
```
=> Automated cherry pick of #1134: Remove debug.PrintStack()

pkg/deviceutils/device-utils.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```
verification of path logic:
for a scsi device
if /dev/disk/by-id/* path exists:
-> eval symlnk (derives the /dev/sd/* or a /dev/nvme/*)
-> if serial number == disk name -> return success
->else run udevadm trigger
else:
-> run udevadm --trigger (this is expected to replay the kernel event and create the /dev/by-id path, and in the next wait poll retry round, it is expected to find the …
```
=> Improve logging for device path verification

pkg/mount-manager/device-utils.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
This is a manual unclean cherrypick because the device utils moved to a new location in 1.9+ branches
```release-note
Improve logging for verification of device path
```
=> Cherrypick #1138 - Improve logging for verification of device path

pkg/deviceutils/device-utils.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
These changes have been incorporated in the cherrypick PRS for [1.9](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1142) and [1.8](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1143)
Fixes #
```release-note
minor fixes on top of logging improvement for verify device paths
```
=> minor fixes on top of logging improvement

pkg/deviceutils/device-utils.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
Improve logging for device path verification
```
=> Cherrypick #1138 - Improve logging for device path verification

deploy/kubernetes/base/controller/kustomization.yaml, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml, deploy/kubernetes/overlays/prow-stable-sidecar-rc-master/default-fstype.yaml, deploy/kubernetes/overlays/prow-stable-sidecar-rc-master/kustomization.yaml, deploy/kubernetes/overlays/prow-stable-sidecar-rc-master/max-grpc-log-length.yaml
/kind cleanup
Update csi-attacher to https://github.com/kubernetes-csi/external-attacher/releases/tag/v4.2.0
Fixes #
* The rbac file hasn't changed for [3 years](https://github.com/kubernetes-csi/external-attacher/tree/master/deploy/kubernetes).
* Changelog from [3.5.0 to 4.2.0](https://github.com/kubernetes-csi/external-attacher/tree/master/CHANGELOG) shows that the added flag is: --max-grpc-log-length. In external-attacher it is [set to -1](https://github.com/kubernetes-csi/external-attacher/pull/411/files). But in the driver there is a [default 10000](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/commit/f7af69f3665cb77ee5 …
=> Update csi-attacher to v4.2.0

deploy/kubernetes/base/controller/kustomization.yaml, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml, deploy/kubernetes/overlays/prow-stable-sidecar-rc-master/default-fstype.yaml, deploy/kubernetes/overlays/prow-stable-sidecar-rc-master/kustomization.yaml, deploy/kubernetes/overlays/prow-stable-sidecar-rc-master/max-grpc-log-length.yaml
Cherry pick of #1144 on release-1.9.
#1144: Update csi-attacher to v4.2.0
```release-note
NONE
```
=> Automated cherry pick of #1144: Update csi-attacher to v4.2.0

CHANGELOG/CHANGELOG-1.8.md, CHANGELOG/CHANGELOG-1.9.md
Add some changes for 1.8 that were missing, and new changes for 1.9.
Fixes #
```release-note
None
```
=> Update change logs for 1.8 and 1.9

deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
/kind cleanup
Match internal sidecar versions:
- csi-snapshotter v6.1.0 [1. diff](https://github.com/kubernetes-csi/external-snapshotter/compare/v6.0.1...v6.1.0)  [2. change log](https://github.com/kubernetes-csi/external-snapshotter/tree/master/CHANGELOG)
- csi-provisioner v3.4.0 [1. diff](https://github.com/kubernetes-csi/external-provisioner/compare/v3.2.1...v3.4.0) [2. change log](https://github.com/kubernetes-csi/external-provisioner/tree/master/CHANGELOG)
Added --enable-pprof option but we are not using it.
- csi-resizer v1.7.0 [1. diff](https://github.com/kubernetes-csi/external-resizer/compare/v1.5.0...v1.7.0) [2. change log](https://github.com/kubernetes-csi/external-resizer/tree/master/CHANGELOG)
- csi-attacher …
=> Update sidecar based on internal versions

deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Cherry pick of #1154 on release-1.9.
#1154: Update sidecar based on internal versions
```release-note
None
```
=> Automated cherry pick of #1154: Update sidecar based on internal versions

README.md, deploy/kubernetes/images/stable-master/image.yaml, deploy/kubernetes/overlays/stable-master/default-fstype.yaml, deploy/kubernetes/overlays/stable-master/kustomization.yaml, deploy/kubernetes/overlays/stable-master/max-grpc-log-length.yaml
/kind feature
Put 1.9.0 release into stable-master. The sidecar update is based on [this](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1155/files).
RC passing testgrid since 02-22 20:08 PST (visible google internal only): https://k8s-testgrid.appspot.com/provider-gcp-compute-persistent-disk-csi-driver#Kubernetes%20Master%20Driver%20Latest%20Release%20Candidate
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-gcp-compute-persistent-disk-csi-driver-release-staging-k8s-master-integration/1628728505032249344 with newest sidecar change.
Refer to https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/804
```release-note
None
```
=> release-1.9 cut details for v1.9.0

README.md, deploy/kubernetes/images/stable-master/image.yaml, deploy/kubernetes/overlays/stable-master/default-fstype.yaml, deploy/kubernetes/overlays/stable-master/kustomization.yaml, deploy/kubernetes/overlays/stable-master/max-grpc-log-length.yaml
Cherry pick of #1153 on release-1.9.
#1153: release-1.9 cut details for v1.9.0
```release-note
NONE
```
=> Automated cherry pick of #1153: release-1.9 cut details for v1.9.0

Dockerfile, Dockerfile.Windows, Dockerfile.debug
Cherry pick of #1158 on release-1.9.
#1158: go version updates
```release-note
```
=> Automated cherry pick of #1158: go version updates

Dockerfile
/kind bug
Fix for CVE-2022-4450, CVE-2022-2097, CVE-2023-0286, CVE-2023-0215, CVE-2022-4304
Fixes #
Kubernetes stopped creating new buster images, they've all moved to bullseye now. The recommended update is:
[gcr.io/gke-release/debian-base:bullseye-v1.4.3-gke.0](http://gcr.io/gke-release/debian-base:bullseye-v1.4.3-gke.0)
or [gke.gcr.io/debian-base:bullseye-v1.4.3-gke.0](http://gke.gcr.io/debian-base:bullseye-v1.4.3-gke.0)
On buster it is ``/lib/x86_64-linux-gnu/libblkid.so.1`` but on bullseye is ``/usr/lib/x86_64-linux-gnu/libblkid.so.1``. See [release note](https://www.freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge/)
**Does this PR …
=> Fix for CVEs

Dockerfile
Cherry pick of #1162 on release-1.9.
#1162: Fix for CVEs
```release-note
```
=> Automated cherry pick of #1162: Fix for CVEs

Makefile
/kind bug
Multiarch build was failing with:
```
[builder 4/4] RUN GOARCH=$(echo linux/arm64 | cut -f2 -d '/') GCE_PD_CSI_STAGING_VERSION=v1.9.0-xxx make gce-pd-driver
21.78 # sigs.k8s.io/gcp-compute-persistent-disk-csi-driver/cmd/gce-pd-csi-driver
21.78 loadinternal: cannot find runtime/cgo
gi21.78 /usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
```
Fixes #
Ran the following without errors:
```
docker buildx build  . --file=Dockerfile \
--platform linux/arm64 \
--build-arg STAGINGVERSION=test \
--build-arg BUILDPLATFORM=linux/amd64 \
--build-arg TARGETPLATFORM=linux/arm64  \
--build-arg ARCH=arm64 
```
**Does this PR …
=> Fix multiarch build

Makefile
Cherry pick of #1164 on release-1.9.
#1164: Fix multiarch build
```release-note
```
=> Automated cherry pick of #1164: Fix multiarch build

pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, test/e2e/tests/single_zone_e2e_test.go
> /kind bug
[Flakey unit tests](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-gcp-compute-persistent-disk-csi-driver-unit) discovered an issue in the way volume cloning chooses the zone to clone the volume into. The test fails when the [random logic](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/pkg/gce-pd-csi-driver/controller.go#L1387) picks a source zone that does not satisfy [the volume cloning limitations](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/volume-cloning#limitations).
Volume cloning should satisfy the following topology requirements: 
1. For zonal->zonal cloning, the zone of the clone must match the zone of …
=> satisfy volume cloning topology requirements when choosing zone for CreateVolume 

pkg/common/parameters.go, pkg/common/parameters_test.go
/kind bug
Causing regression, revert https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1090
Fixes #1160
```release-note
Revert [#1090](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1090)
```
=> Revert PR#1090

CHANGELOG/CHANGELOG-1.9.md, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Change log for v1.9.2, bake in https://k8s-testgrid.appspot.com/provider-gcp-compute-persistent-disk-csi-driver#Kubernetes%20Master%20Driver%20Latest%20Release%20Candidate
Fixes #
[GCR image v1.9.2-rc1](https://pantheon.corp.google.com/gcr/images/k8s-staging-cloud-provider-gcp/global/gcp-compute-persistent-disk-csi-driver@sha256:952cdebb219295408e2ec3e84936fb2671ee4cdc4989b391978d272feb50711e/details?e=-13802955&jsmode=o&mods=logs_tg_prod)
```release-note
NONE
```
=> Add changelog for 1.9.2

Dockerfile
/kind bug
Some env may not have the required libedit.so.2, copy the lib by default.
Fixes #
```release-note
Fix missing libedit.so.2 error 
```
=> Fix xfs_io error while loading shared libraries: libedit.so.2

test/k8s-integration/main.go
Skip snapshot and restore test because test fix [PR#972](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/972) is not backported to 1.8-. The fix is only in 1.9+. This test is currently failing when I am trying to cherry pick CVE fixes back to 1.8 and 1.7. See [here](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1186#issuecomment-1508460418)
Fixes #
```release-note
Skips Snapshot and Restore test for …
```
=> Skip snapshot and restore test 

CHANGELOG/CHANGELOG-1.7.md, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Update changelog for 1.7.6, and update prow-stable-sidecar-rc image
Fixes #
```release-note
None
```
=> Update changelog for 1.7.6, and update prow-stable-sidecar-rc image

CHANGELOG/CHANGELOG-1.8.md, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Update changelog for 1.8.4, and update prow-stable-sidecar-rc image
Fixes #
```release-note
None
```
=> Update changelog for 1.8.4, and update prow-stable-sidecar-rc image

Dockerfile
/kind bug
Include libraries that are dependencies for xfs
Fixes #1203
```release-note
add libraries needed for determining XFS volume expansion
```
=> add libbsd and libmd

test/k8s-integration/config/sc-xfs.yaml, test/run-k8s-integration-ci.sh
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Add xfs storageclass to enable xfs volumeexpansion tests. This is a short term fix to make sure the PDCSI R12 release isn't missing any more packages after upgrading from buster to bullseye. The longer term fix is to add XFS to the expansion suite and other suites where we think filesystem type will matter in the upstream k8s test. 
Fixes # …
=> Add xfs storageclass to enable xfs volumeexpansion tests

Dockerfile
Cherry pick of #1204 on release-1.10.
#1204: add libbsd and libmd
```release-note
```
=> Automated cherry pick of #1204: add libbsd and libmd

test/k8s-integration/main.go
>
> /kind bug
> /kind design
> /kind flake
Skip mount options test until we fix the invalid mount options for xfs. The xfs tests are now being run because we added a xfs storageclass which enables all of the xfs tests: #1206 
Fixes #
```release-note
None
```
=> Skip mount options test until we fix the invalid mount options for xfs

cmd/gce-pd-csi-driver/main.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce.go, pkg/gce-cloud-provider/metadata/metadata.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/server.go, pkg/gce-pd-csi-driver/utils.go, pkg/gce-pd-csi-driver/utils_linux.go, pkg/gce-pd-csi-driver/utils_test.go, pkg/gce-pd-csi-driver/utils_windows.go, pkg/metrics/metrics.go, pkg/mount-manager/device-utils.go, pkg/mount-manager/safe-mounter_windows.go, pkg/mount-manager/statter_linux.go, test/k8s-integration/cluster.go, test/remote/ssh.go, test/sanity/sanity_test.go
Cherry pick of #1092 on release-1.7.
#1092: Separate user errors from internal errors
```release-note
Separate user errors from internal errors
```
=> Automated cherry pick of #1092: Separate user errors from internal errors

Makefile
This updates the buildkit version from 0.10.6 -> 0.11.3. Version 0.11.3 contains a caching fix, which appears to be contributing to failures of the integration test (https://github.com/moby/buildkit/releases/tag/v0.11.3).
Fixes #1217
```release-note
NONE
```
=> Update buildkit version from 0.10.6 -> 0.11.3

pkg/common/utils.go, pkg/common/utils_test.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go
/kind bug
On AttachDisk UNSUPPORTED_OPERATION failure (when a PD disk type is not supported by a VM family), the GCE API prints a non-intuitive error message:
```
"ControllerPublishVolume failed with error for disk projects/psch-gke-dev/zones/us-central1-c/disks/gcepd-csi-e2e-c3-d7397693-5097-4a70-9df0-b10204611053 on node projects/psch-gke-dev/zones/us-central1-c/instances/gce-pd-csi-e2e-us-central1-c: rpc error: code = Internal desc = '[pd-standard] features are not compatible for creating instance'
```
This PR changes the error message to the following:
```
"ControllerPublishVolume failed with error for disk projects/psch-gke-dev/zones/us-central1-c/disks/gcepd-csi-e2e-c3-39658ebc-95ad-434c-975a-e8e34b81fbbb on node …
```
=> Rewrite PD CSI error message when encountering diskType unsupported error

Makefile
Cherry pick of #1218 on release-1.10.
#1218: Update buildkit version from 0.10.6 -> 0.11.3
```release-note
NONE
```
=> Automated cherry pick of #1218: Update buildkit version from 0.10.6 -> 0.11.3

CHANGELOG/CHANGELOG-1.7.md
Backport exception has been approved.
```release-note
None
```
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/tree/v1.7.8
=> Add changelog for v1.7.8

pkg/gce-pd-csi-driver/utils.go, pkg/gce-pd-csi-driver/utils_test.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This filters out context errors from the SLO. Right now we are returning Internal error code for `context deadline exceeded` and `context canceled` errors which are returned from `waitForZonalOp` or `waitForRegionalOp`. We already did a similar thing in the Filestore CSI Driver [here](https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/pull/417). 
Here is an example of an error we will now return `DeadlineExceeded` instead of `Internal`: 
```
ERROR …
```
=> Return Canceled or DeadlineExceeded error code for context errors returned from polling

pkg/common/utils.go, pkg/common/utils_test.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go
Cherry pick of #1212 on release-1.9.
#1212: Rewrite PD CSI error message when encountering diskType
```release-note
Updates error message to be more user friendly when PD CSI Driver encounters an disk type UNSUPPORTED_OPERATION on ControllerPublishVolume
```
=> Automated cherry pick of #1212: Rewrite PD CSI error message when encountering diskType

pkg/gce-cloud-provider/compute/gce.go, pkg/gce-cloud-provider/compute/gce_test.go, pkg/gce-pd-csi-driver/utils.go, pkg/gce-pd-csi-driver/utils_test.go, test/remote/instance.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Use errors.As so we can detect wrapped errors, and check for existing error codes in CodesForError. Currently wrapped errors cannot be detected in IsGCEError. Also if we return a grpc error code that is not an error we filter out by LoggedError, it will get turned into an Internal error.  
Fixes #
```release-note
None
```
=> Use errors.As so we can detect wrapped errors, and check for existing error codes in CodesForError

docs/kubernetes/development.md, pkg/deviceutils/fake-device-utils.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go, test/sanity/sanity_test.go
>
/kind bug
> /kind design
> /kind flake
This is a follow up to https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/1088 which does 2 things:
1. Adds more fine grained testing for whether or not resize is attempted under certain scenarios during node stage.
2. Skips resize attempt if volume capability from request indicates readonly
Fixes #1088
```release-note …
```
=> Add tests for ROX mode during Node Stage 

test/k8s-integration/config/test-config-template.in
See https://github.com/kubernetes/cloud-provider-gcp/issues/557 and [this example of a failing test](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-gcp-compute-persistent-disk-csi-driver-release-k8s-master-integration/1665792101725507584).
It appears the nouid32 mount option is not supported by XFS.
I guess it works with ext4 --- but brief internet searching didn't find anything about it, so I don't know if it's something we need to support?
```release-note
None
```
=> Remove nouid32 which breaks xfs

test/k8s-integration/config/test-config-template.in
I pulled the trigger too quickly on #1252, we can use the noatime option instead which works on ext4 and xfs.
See also https://github.com/kubernetes/cloud-provider-gcp/issues/557
```release-note
None
```
=> Use noatime as test mount option

pkg/gce-pd-csi-driver/controller.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Filter out user errors from GetDisk error returned from ControllerPublishVolume. We are getting ControllerPublishVolume SLO violations because GetDisk returns a user error even though the error code is a 403 error. This is because we did not wrap the error with common.LoggedError in this spot. Examples of errors we are getting now, which will soon be replaced with proper grpc code: 
```
ERROR /csi.v1.Controller/ControllerPublishVolume returned with error: rpc error: …
```
=> Filter out user errors from GetDisk error returned from ControllerPublishVolume

pkg/common/parameters.go, pkg/common/parameters_test.go, pkg/common/utils.go, pkg/common/utils_test.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, test/e2e/tests/multi_zone_e2e_test.go, test/e2e/tests/resize_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/utils/utils.go, test/remote/client-wrappers.go, test/run-e2e-local.sh
/kind feature
This adds an alpha-level storage class parameter to always perform a force attach. This is only valid for RePD disks (although this is not validated --- using this parameter with zonal disks will cause attaches to fail).
This parameter is not guaranteed to have continued support or to be stable in any way. In addition, using this can cause data loss.
```release-note
Add alpha-level force attach storage class parameter.
```
=> Add force attach to storage class

test/k8s-integration/cluster.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
The node-skew regional tests for PDCSI managed driver are flaky because the nodes auto-upgrade occasionally in the middle of the test, causing random test cases to fail. I fixed this with the gcsfuse CSI driver, and I noticed PDCSI had the same problem. 
Fixes #
```release-note
None
```
=> fix flaky node-skew tests by disabling node autoupgrade

pkg/gce-pd-csi-driver/controller.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
The variable `diskTypeForMetric` is currently being overwritten when we check for existing disks in Create Volume calls. Removing the assignment for `diskTypeForMetric` in Create volume while validating existing disk. 
Fixes #
This is related to PR #1227
```release-note
Bugfix for empty disk type being registered in metric for Create volume …
```
=> Remove updating disk type for existing disks

pkg/common/utils_test.go, pkg/gce-cloud-provider/compute/gce-compute.go, test/e2e/tests/single_zone_e2e_test.go
/kind bug
The logic of passing in provisioned-iops-on-create is not at the right func. The tests picked the default value and the verification is passing.
Fixes #
```release-note
Fix provisioned-iops-on-create passing logic
```
=> Fix provisioned-iops-on-create passing logic

pkg/common/utils_test.go, pkg/gce-cloud-provider/compute/gce-compute.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/tests/single_zone_pd_extreme_e2e_test.go
This is a cherry-pick of #1278
```release-note
Fix provisioned-iops-on-create passing logic
```
=> [release-1.8] Fix provisioned-iops-on-create passing logic

pkg/common/utils_test.go, pkg/gce-cloud-provider/compute/gce-compute.go, test/e2e/tests/single_zone_e2e_test.go
This is a cherry-pick of #1278
```release-note
Fix provisioned-iops-on-create passing logic
```
=> [release-1.9]Fix provisioned-iops-on-create passing logic

CHANGELOG/CHANGELOG-1.8.md
Add changelog for 1.8.7
```release-note
None
```
=> Add Changelog for 1.8.7

pkg/gce-pd-csi-driver/controller.go, pkg/metrics/metrics.go
>
/kind bug
> /kind design
> /kind flake
The PR emits the metric `csidriver_operation_error` with disk type for success scenarios
Fixes #
This is related to [PR #1227](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1227)
```release-note
Add disk type for all operations metrics including success scenarios to have better comparison for received errors.
```
=> emit metrics even for success scenarios

pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce-compute_test.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Filter out GCE operation error codes caused by user errors. We are getting lots of errors counting against our SLO for GCE operation errors that are user errors. We have seen Internal errors returned from the following GCE operation error codes: `OPERATION_CANCELED_BY_USER`, `RESOURCE_NOT_FOUND`, `RESOURCE_IN_USE_BY_ANOTHER_RESOURCE`, `INVALID_USAGE`. I added a filtered out other error codes (quota error codes) which we haven't observed yet, but those are clearly user …
=> Filter out GCE operation error codes caused by user errors

cmd/gce-pd-csi-driver/main.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go, pkg/gce-pd-csi-driver/utils_linux.go, pkg/gce-pd-csi-driver/utils_windows.go, test/e2e/utils/utils.go
/kind bug
This a follow-on to #1168 and #1169. In addition to mkfs, we are now seeing reports from the field of fsck OOMing.
This change serializes formatAndMount in this driver. In parallel we will be extended mount-utils, and will remove this fix once the mount-utils release comes out (which releases every month or two).
```release-note
Add option for serializing formatAndMount, including fsck as well as mkfs.
```
/asssign @saikat-royc
=> Add option to serialize formatAndMount

pkg/common/utils.go, pkg/common/utils_test.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go
/kind cleanup
This will make it easier to filter errors property for alerting.
-->
```release-note
Use original error code when responding with a backoff error on publish or unpublish.
```
=> Use original error code when backing off

pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go
/kind bug
Fixes #1302
```release-note
Fix resource parsing when the gcp project name ends with alpha, beta or v1
```
=> Replace cleanSelfLink with getResourceId

pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go
Cherry-pick #1304 to release-1.9
/kind bug
```release-note
Fix resource parsing when the gcp project name ends with alpha, beta or v1
```
=> Cherry-pick #1304 to release-1.9

test/e2e/utils/utils.go
The e2e tests seems to have gotten a bit more flakey, and the serialization of fsck is the only recent change that seems plausibly a cause.
See also https://github.com/kubernetes/test-infra/pull/30158
-->
```release-note
None
```
=> Increase parallelism in e2e test

pkg/common/parameters.go, pkg/common/utils.go, pkg/common/utils_test.go, pkg/gce-cloud-provider/compute/cloud-disk.go, pkg/gce-cloud-provider/compute/cloud-disk_test.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
This PR adds support in PDCSI driver to create confidential hyperdisk storage on GCE.
Fixes #
This change has been tested manually as we cannot add e2e tests yet.
Scenarios tested:
1. Create a hyperdisk-balanced confidential disk with PDCSI driver.
2. Created a confidential disk from a non-confidential snapshot (Snapshot source disk type: pd-standard) …
=> Added support for confidential storage to disk parametrs and metric

CHANGELOG/CHANGELOG-1.10.md, CHANGELOG/CHANGELOG-1.8.md, CHANGELOG/CHANGELOG-1.9.md, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Fixes #
```release-note
NONE
```
=> Update CHANGELOG for 1.8, 1.9 and 1.10; update rc image versions

test/e2e/tests/setup_e2e_test.go
/kind cleanup
Hyperdisk disk types do not work with n1 machine and a more general working machine is n2.
Fixes #
```release-note
Change e2e test machine type to n2-standard-2 to include more Hyperdisk cases
```
=> Change e2e test machine type to n2-standard-2 to include more Hyperdisk cases

pkg/gce-cloud-provider/compute/gce.go, pkg/gce-cloud-provider/compute/gce_test.go, test/remote/instance.go
Cherry pick of #1232 on release-1.7.
#1232: Use errors.As so we can detect wrapped errors, and check for
```release-note
Use errors.As so we can detect wrapped errors, and check for existing error codes in CodesForError
```
=> Automated cherry pick of #1232: Use errors.As so we can detect wrapped errors, and check for

Dockerfile, Dockerfile.Windows, Dockerfile.debug
>
/kind bug
> /kind design
> /kind flake
Updates go version to 1.20.6 to fix CVEs
Fixes #
```release-note
Update go version to 1.20.6 to fix CVE-2023-29406
```
=> Update go version to 1.20.6 to fix CVE

Dockerfile, Dockerfile.Windows, Dockerfile.debug
Cherry pick of #1330 on release-1.10.
#1330: Update go version to 1.20.6 to fix CVE
```release-note
Update go version to 1.20.6 to fix CVE-2023-29406
```
=>  [release-1.10] Automated cherry pick of #1330: Update go version to 1.20.6 to fix CVE

Dockerfile, Dockerfile.Windows, Dockerfile.debug
Cherry pick of #1330 on release-1.9.
#1330: Update go version to 1.20.6 to fix CVE
```release-note
Update go version to 1.20.6 to fix CVE-2023-29406
```
=>  [release-1.9] Automated cherry pick of #1330: Update go version to 1.20.6 to fix CVE

test/e2e/tests/single_zone_e2e_test.go
The zone specification was mistakenly added, HdT is available in both the two test zones:
```
➜  ~ gcloud compute disk-types list --filter="zone:( us-east4-a)" --project xxxxxxx
NAME                  ZONE        VALID_DISK_SIZES
hyperdisk-extreme     us-east4-a  64GB-65536GB
hyperdisk-throughput  us-east4-a  2048GB-32768GB
local-ssd             us-east4-a  375GB-375GB
pd-balanced           us-east4-a  10GB-65536GB
pd-extreme            us-east4-a  500GB-65536GB
pd-ssd                us-east4-a  10GB-65536GB
pd-standard           us-east4-a  10GB-65536GB
➜  ~ gcloud compute disk-types list --filter="zone:( us-east4-c)" --project xxxxxxx
NAME                  ZONE        VALID_DISK_SIZES …
```
=> Fix zone specification in HdT tests

test/run-e2e.sh
/kind flake
The Prow job test timeout was updated in https://github.com/kubernetes/test-infra/pull/30158. This updates the corresponding script to use a go test timeout of 30 minutes.
```release-note
NONE
```
=> Update test/run-e2e.sh to match PROW configuration

test/k8s-integration/cluster.go, test/k8s-integration/main.go, test/k8s-integration/version.go, test/run-k8s-integration.sh
/kind cleanup
This adds an option to use a precompiled release of Kubernetes to the integration test, rather than using a github branch and building from source. The build step takes ~30 minutes in the prow integration test, which can lead to long submit times, and flaky tests (due to exceeding the 90 minute timeout).
```release-note
NONE
```
=> Use precompiled stable release of Kubernetes by default when running integration test

Dockerfile, Dockerfile.Windows, Dockerfile.debug
>
/kind bug
> /kind design
> /kind flake
Updates go version to 1.20.7 to fix CVEs CVE-2023-29409 CVE-2023-39533. Related PD #1346 
Fixes #
```release-note
Update go version to 1.20.7 to fix CVE-2023-29409 CVE-2023-39533
```
=> [release-1.11] Update go version to 1.20.7 to fix CVEs

pkg/gce-cloud-provider/compute/gce-compute.go, test/e2e/tests/single_zone_e2e_test.go
/kind cleanup
Fixes #
```release-note
Add pd-extreme e2e test case of defaulting to default iops when iops not set
```
=> Add pd-extreme e2e test case of defaulting to default iops when iops not set

OWNERS
Adds @pwschuurman to reviewers/approvers list
```release-note
NONE
```
=> Add pwschuurman as reviewer/approver to gcp-compute-persistent-disk-csi-driver repository

OWNERS
Cherry pick of #1354 on release-1.8.
#1354: Add pwschuurman@ as reviewer/approver to OWNERS
```release-note
NONE
```
=> Automated cherry pick of #1354: Add pwschuurman as reviewer/approver to

CHANGELOG/CHANGELOG-1.10.md, CHANGELOG/CHANGELOG-1.11.md, CHANGELOG/CHANGELOG-1.7.md, CHANGELOG/CHANGELOG-1.8.md, CHANGELOG/CHANGELOG-1.9.md
Update release specific changelog for recent gcp-compute-persistent-disk-csi-driver releases
```release-note
NONE
```
=> Updating changelog for release v1.11.0, v1.10.6, v1.9.8, v1.8.9 v1.7.11

go.mod, go.sum, vendor/google.golang.org/grpc/status/status.go, vendor/google.golang.org/grpc/version.go, vendor/modules.txt
Upgrade google.golang.org/grpc from v1.55.0 -> v1.55.1 to address https://github.com/grpc/grpc-go/issues/6373
/kind bug
Updates a grpc golang dependency patch version that had a bug which caused nil pointer exception.
```release-note
Fix bug caused by https://github.com/grpc/grpc-go/issues/6373 that results in driver binary crashes when parsing certain error grpc objects
```
=> Upgrade google.golang.org/grpc from v1.55.0 -> v1.55.1 to address https://github.com/grpc/grpc-go/issues/6373

CHANGELOG/CHANGELOG-1.10.md, CHANGELOG/CHANGELOG-1.11.md, CHANGELOG/CHANGELOG-1.7.md, CHANGELOG/CHANGELOG-1.8.md, CHANGELOG/CHANGELOG-1.9.md
Update release specific changelog for recent gcp-compute-persistent-disk-csi-driver releases
```release-note
NONE
```
=> Update changelog for release v1.11.1, v1.10.7, v1.9.9, v1.8.10, v1.7.12

go.mod, go.sum, vendor/google.golang.org/grpc/status/status.go, vendor/google.golang.org/grpc/version.go, vendor/modules.txt
Upgrade google.golang.org/grpc from v1.55.0 -> v1.55.1 to address https://github.com/grpc/grpc-go/issues/6373
/kind bug
Updates a grpc golang dependency patch version that had a bug which caused nil pointer exception.
```release-note
Fix bug caused by https://github.com/grpc/grpc-go/issues/6373 that results in driver binary crashes when parsing certain error grpc objects
```
=> Upgrade google.golang.org/grpc from v1.55.0 -> v1.55.1 to address grpc/grpc-go#6373

pkg/common/utils.go, pkg/common/utils_test.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go
Cherry pick of #1298 on release-1.8.
#1298: Use original error code when backing off
```release-note
Use original error code when responding with a backoff error on publish or unpublish.
```
=> [release-1.8] Automated cherry pick of #1298: Use original error code when backing off

Dockerfile, Dockerfile.Windows, Dockerfile.debug
>
> /kind bug
> /kind design
> /kind flake
bump go version to 1.20.8 to fix CVE-2023-39318, CVE-2023-39319
Fixes #
```release-note
N/A
```
=> Bump go version to 1.20.8 to fix CVE

CHANGELOG/CHANGELOG-1.7.md, CHANGELOG/CHANGELOG-1.8.md
Update release specific changelog for recent gcp-compute-persistent-disk-csi-driver releases
```release-note
NONE
```
=> Update changelog for release v1.8.11, v1.7.13

pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/identity.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Change Unavailable error codes that signal a problem with the driver to Internal error codes to Internal error codes in preparation for filtering out Unavailable from our SLO.  The error code Unavailable can refer to transient or self healing errors, and we should filter it out of our SLO: `Use Unavailable if the client can retry just the failing call`. If there are any errors that are currently Unavailable that we feel strongly about alerting on, we should move them …
=> Change Unavailable error codes that signal a problem with the driver to Internal error codes. 

pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/identity.go
Cherry pick of #1406 on release-1.11.
#1406: Change Unavailable error codes that signal a problem with the
```release-note
NONE
```
=> Automated cherry pick of #1406: Change Unavailable error codes that signal a problem with the

test/k8s-integration/main.go
Fixes CI Integration test that is failing: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-gcp-compute-persistent-disk-csi-driver-latest-k8s-master-integration/1712953895405228032
Test is failing with:
```
panic: flag logtostderr set at /usr/local/google/home/$USER/github_workspaces/gcp-compute-persistent-disk-csi-driver/test/k8s-integration/main.go:115 before being defined
```
The integration test runner sets a flag prior to defining the flag. The test is failing now that latest `gcr.io/k8s-staging-test-infra/kubekins-e2e` image is using go1.21.
```release-note
NONE
```
=> Initialize flags prior to setting --logtostderr in test/k8s-integration/main.go

Dockerfile, Dockerfile.Windows, Dockerfile.debug
>
/kind bug
Fix for CVE-2023-39323
Fixes #
```release-note
CVE fixes: CVE-2023-39323
```
=> Update go version to 1.20.9

docs/release/overlays.md, release-tools/SIDECAR_RELEASE_PROCESS.md
Testgrid dashboard link changed to testgrid.k8s.io
>
> /kind bug
> /kind design
> /kind flake
Changes the old testgrid dashboard links (appspot) to the new one (testgrid.k8s.io)
Please see https://github.com/kubernetes/test-infra/issues/30370
Fixes #
**Special notes for your reviewer**: N/A
**Does this PR introduce a user-facing change?**: 
```release-note
NONE
```
=> Update mentions of testgrid dashboard link

.github/dependabot.yml
/kind cleanup
Add groups and we can use [dependabot command like ignore](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates#managing-dependabot-pull-requests-for-grouped-version-updates-with-comment-commands) to exclude packages.
Fixes #
```release-note
NONE
```
=> Add Groups in Dependabot for the Rest Dependencies

pkg/gce-pd-csi-driver/node.go
/kind cleanup
```release-note
The benign error when DisableDevice is not effective is logged as a warning.
```
=> Change DisableDevice error to warning

pkg/gce-pd-csi-driver/controller.go
Cherry pick of #1338 on release-1.8.
#1338: Always call LoggedError for errors returned from
```release-note
None
```
=> Automated cherry pick of #1338: Always call LoggedError for errors returned from

go.mod, pkg/deviceutils/device-utils.go, pkg/deviceutils/device-utils_test.go, vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go, vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go, vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go, vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go, vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go, vendor/modules.txt
/kind bug
The current code that finds NVMe device paths looks for `/dev/nvme*`, which returns partition and device paths. The mount code is only concerned about drive/namespace paths, so the found paths should be restricted to these.
Fixes #1480
```release-note
```
=> Update nvme /dev/ device search path to only identify drive/namespace paths

go.mod, pkg/deviceutils/device-utils.go, pkg/deviceutils/device-utils_test.go, vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go, vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go, vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go, vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go, vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go, vendor/modules.txt
Cherry pick of #1485 on release-1.11.
```release-note
```
=> [release-1.11] Automated cherry pick of #1485: Update nvme /dev/ device search path to only identify

go.mod, pkg/deviceutils/device-utils.go, pkg/deviceutils/device-utils_test.go, vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go, vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go, vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go, vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go, vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go, vendor/modules.txt
Cherry pick of #1485 on release-1.12.
```release-note
```
=> [release-1.12] Automated cherry pick of #1485: Update nvme /dev/ device search path to only identify

Dockerfile, Dockerfile.Windows, Dockerfile.debug
/kind bug
Bump Golang Builder version to 1.20.11
Fixes #
```release-note
Bump Golang Builder version to 1.20.11
```
=> Bump Golang Builder version to 1.20.11

pkg/gce-pd-csi-driver/node_test.go, release-tools/filter-junit.go, test/k8s-integration/filter-junit.go, test/k8s-integration/utils.go, test/remote/archiver.go, test/remote/instance.go
"io/ioutil" has been deprecated since Go 1.19: As of Go 1.16
Fixes #
```release-note
NONE
```
=> chore: remove refs to deprecated io/ioutil

pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go
/kind bug
Errors from the GCE images.get API call are not properly wrapped. This prevents error messages from being transparently displayed on a VolumeSnapshotContent, results in driver nil-ptr dereference and can result in Kubernetes sidecars to also restart.
Fixes #1513
```release-note
Properly wrap error from GCE Images.Get() API call, to fix a potential nil-ptr dereference
```
=> Add error logging when error is encountered fetching a VolumeSnapshotContent source image

pkg/common/parameters.go, pkg/common/utils.go, pkg/gce-cloud-provider/compute/cloud-disk.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
The StoragePool field is only supported in the [GCE Alpha Disk API](https://pkg.go.dev/google.golang.org/api@v0.134.0/compute/v0.alpha#disk). This code can be removed once Storage  Pools is supported on v1/beta.  StoragePools only support zonal disks, so only insertZonalDisk has support for the alphaAPI. Only zonal disks are supported in Storage Pools. CreateVolume implementation for Storage Pools will come in a follow up PR.
Fixes # …
=> Use GCE Alpha API to create zonal disks when Storage Pools is enabled

README.md
Icon URL is not correct, resulting in a broken image icon.
```release-note
NONE
```
=> Fix Kubernetes Integration test status icon

cmd/gce-pd-csi-driver/main.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, pkg/gce-pd-csi-driver/gce-pd-driver_test.go, test/sanity/sanity_test.go
/kind bug
Fixes Regional Persistent Disk provisioning on GKE Autopilot clusters when there is only 0 or 1 zones available across nodes in the cluster.
Fixes #1531
This changes the behavior for Regional PD CreateVolume calls that have only one preferred topology. Previously, if a Regional PD was provisioned with a single preferredTopology (zone), and a list of requisite topologies (Zone), the secondary zone would be selected at random. This differed from the logic in [the external provisioner](https://github.com/kubernetes-csi/external-provisioner/blob/b02252374e59fb051258185805ed07fc97766d78/pkg/controller/topology.go#L253), which picks the secondary …
=> Add --fallback-requisite-zones command line argument

go.mod, pkg/deviceutils/device-utils.go, pkg/deviceutils/device-utils_test.go, vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go, vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go, vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go, vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go, vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go, vendor/modules.txt
Cherry pick of #1485 on release-1.10.
```release-note
```
=> [release-1.10] Automated cherry pick of #1485: Update nvme /dev/ device search path to only identify

test/e2e/tests/single_zone_e2e_test.go
Fixes GCP selfLink cleaning code, allowing for projects that end in "v1", "alpha" or "beta" to have their fully qualified links parsed correctly.
Fixes #1543
The production link cleaning code was fixed in #1302. This just improves the parsing logic for the test. In the production code, this functionality is a private method, and not exported to the test.
```release-note
NONE
```
=> Increase strictness of fully qualified GCP link cleaning in e2e test parsing code

CHANGELOG/CHANGELOG-1.10.md, CHANGELOG/CHANGELOG-1.11.md, CHANGELOG/CHANGELOG-1.12.md, CHANGELOG/CHANGELOG-1.7.md, CHANGELOG/CHANGELOG-1.8.md, CHANGELOG/CHANGELOG-1.9.md, hack/generate-patch-release-notes.sh
Fixes #
```release-note
NONE
```
=> Add changelogs for latest patch releases

pkg/common/utils.go, pkg/common/utils_test.go
/kind bug
User misconfiguration causing multiattach errors clouds up our SLO.
```release-note
Filter user misconfigured multiattach errors.
```
=> Filter multiattach errors

pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go
/kind bug
When we do CreateVolume, the csi provisioner expects either "final" or "temporary" errors, if we report final error when disk creation could be ongoing or the disk is already created, then a PVC deletion before successful volume creation could lead to disk leakage as DeleteVolume won't happen.
The temporary errors are defined here: https://github.com/kubernetes-csi/external-provisioner/blob/master/pkg/controller/controller.go#L1904
This PR changes all the GCE API calls in `CreateVolume` code path that potentially happens *AFTER* `insertDisk` API calls happened to report a non-final error.
Fixes # …
=> change GetDisk error reporting to temporary in CreateVolume codepath

cmd/gce-pd-csi-driver/main.go, pkg/common/parameters.go, pkg/common/parameters_test.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, pkg/gce-pd-csi-driver/gce-pd-driver_test.go, test/sanity/sanity_test.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Adds command line flag for enabling creating volumes in storage pools. This will allow us to control the rollout of the storage pools feature until we are ready to launch to customers.
Fixes #
```release-note
NONE
```
=> Add command line flag for enabling Storage Pools feature

go.mod, pkg/mount-manager/device-utils.go, pkg/mount-manager/device-utils_test.go, vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go, vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go, vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go, vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go, vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go, vendor/modules.txt
Cherry pick of #1485 on release-1.8.
```release-note
```
=> [release-1.8] Automated cherry pick of #1485: Update nvme /dev/ device search path to only identify

go.mod, pkg/deviceutils/device-utils.go, pkg/deviceutils/device-utils_test.go, vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go, vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go, vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go, vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go, vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go, vendor/modules.txt
Cherry pick of #1485 on release-1.9.
```release-note
```
=> [release-1.9] Automated cherry pick of #1485: Update nvme /dev/ device search path to only identify

pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce-compute_test.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This PR maps UNSUPPORTED_OPERATION GCE operation error codes to InvalidArgument. Right now, UNSUPPORTED_OPERATION return Internal error codes, which counts against our SLO, but this should not count. 
UNSUPPORTED_OPERATION would be returned with several different user errors. For example: 
- The requested PD disk type (READ_WRITE_ONLY)  is not supported for the requested machine type
- The requested Hyperdisk disk type (READ_WRITE_ONLY)  is not supported for the …
=> Map UNSUPPORTED_OPERATION GCE operation error codes to InvalidArgument

cmd/gce-pd-csi-driver/main.go, pkg/gce-cloud-provider/compute/gce.go, pkg/gce-cloud-provider/compute/gce_test.go, pkg/gce-pd-csi-driver/controller.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/utils/utils.go, test/remote/runner.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
The PR updates PDCSI driver to support GCE staging compute for internal testing.
Fixes #
NA
```release-note
NONE
```
=> Update driver to support compute staging

cmd/gce-pd-csi-driver/main.go, pkg/common/constants.go, pkg/common/utils.go, pkg/gce-cloud-provider/compute/cloud-disk.go, pkg/gce-cloud-provider/compute/cloud-disk_test.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, pkg/gce-pd-csi-driver/gce-pd-driver_test.go, test/e2e/tests/multi_zone_e2e_test.go, test/e2e/tests/resize_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/utils/utils.go, test/remote/client-wrappers.go, test/sanity/sanity_test.go
/kind feature
A pattern in Kubernetes Deployment workloads is to use a single ROX PV, in the pod volumes template. When running a Deployment that runs in multiple zones, a user may want to leverage content backed on a PD.  This PR adds support for "multi-zone" volumeHandles, allowing the PDCSI to interpret this as a placeholder the zone that a compute instance is running in.
Fixes #1591
```release-note
Add support for multi-zone volumeHandle
```
=> Add support for a multi-zone volumeHandle

cmd/gce-pd-csi-driver/main.go
>
/kind bug
> /kind design
> /kind flake
It fixes the pointer related issue from PR#1586
Fixes #
```release-note
NONE
```
=> fix pointer issue for GCE staging support

cmd/gce-pd-csi-driver/main.go, pkg/gce-cloud-provider/compute/gce.go, pkg/gce-cloud-provider/compute/gce_test.go, pkg/gce-pd-csi-driver/controller.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/utils/utils.go
Reverts kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#1614
```release-note
NONE
```
=> Revert "Automated cherry pick of #1586: update driver to support staging compute#1609: fix pointer issue for GCE staging support"

cmd/gce-pd-csi-driver/main.go, pkg/common/constants.go, pkg/common/utils.go, pkg/gce-cloud-provider/compute/cloud-disk.go, pkg/gce-cloud-provider/compute/cloud-disk_test.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, pkg/gce-pd-csi-driver/gce-pd-driver_test.go, test/e2e/tests/multi_zone_e2e_test.go, test/e2e/tests/resize_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/utils/utils.go, test/remote/client-wrappers.go, test/sanity/sanity_test.go
Cherry pick of #1593 on release-1.13.
#1593: Add support for a multi-zone volumeHandle
```release-note
Add support for multi-zone volumeHandle
```
=> Automated cherry pick of #1593: Add support for a multi-zone volumeHandle

cmd/gce-pd-csi-driver/main.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/utils/utils.go
>
/kind bug
> /kind design
> /kind flake
Fixes the driver error for empty compute endpoint string from #1586 
Fixes #
```release-note
NONE
```
=> Fix error when no compute endpoint is passed

cmd/gce-pd-csi-driver/main.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce.go, pkg/gce-pd-csi-driver/controller.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/utils/utils.go
/kind feature
Some disks types may reqiure using the instances.get API instead of the disks.get API to validate disk attachment is complete. This adds a flag to control the behavior of using instances.get over disks.get based on the disk type that is being published to a VM.
```release-note
Flag --use-instance-api-to-poll-attachment-disk-types uses instances.get API when polling for disk attachment in ControllerPublish for passed in disk types
```
=> Add flag to toggle instances.get over disks.get compute API on ControllerPublish WaitForAttach

pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go, pkg/gce-pd-csi-driver/utils.go, pkg/gce-pd-csi-driver/utils_linux.go, pkg/gce-pd-csi-driver/utils_windows.go, pkg/mount-manager/statter_linux.go, test/e2e/tests/single_zone_e2e_test.go, test/sanity/sanity_test.go
/kind feature
Adds support for `read_ahead_kb` mount flag. This flag isn't passed directly to the mount command as an option, but it is used to set the readahead value for the underlying block device.
```release-note
Support for read_ahead_kb mount flag to change block device readahead
```
=> Add support for read_ahead_kb mount flag

pkg/deviceutils/device-utils.go, pkg/deviceutils/device-utils_test.go
/kind bug
This PR correctly filters out partition paths in `/dev/nvme`. The search path was updated in PR#1485, however this introduced logic which filtered out all `/dev/nvme` paths. The result was that the logic to trigger a `udev` event for a NVMe device did not work as expected.
Fixes regression of search path https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1485/files
A follow-up PR will introduce an e2e test for a machine type that uses NVMe (current tests use SCSI), to prevent this type of regression in the future.
```release-note
Fixes a regression in the NVMe …
```
=> Fix nvme path filtering logic for udevadm trigger

pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Now that the provisionedIops, provisionedThroughput, enableConfidentialCompute, and storagePool are supported by the [GCE v1 disks insert API](https://cloud.google.com/compute/docs/reference/rest/v1/disks/insert), this PR migrates the disk insert call to alpha/beta --> v1 for these features. This allows us to clean up the code in /pkg/gce-cloud-provider/compute/gce-compute.go. Multiwriter still requires the [GCE beta disks insert …
=> Migrate Hyperdisk/CHD/StoragePools to GCE v1 disk API

pkg/gce-cloud-provider/compute/cloud-disk.go, pkg/gce-cloud-provider/compute/cloud-disk_test.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce.go, pkg/metrics/metrics_test.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This is a follow up PR to [PR 1666](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1666), which Migrated Hyperdisk/CHD/StoragePools features to the GCE v1 disk API. Now that no features are using the GCE alpha disk API, this PR removes support for Alpha Disks. It also adds v1 support to CloudDisk (/gce-cloud-provider/compute/cloud-disk.go) for the Hyperdisk/CHD/StoragePools features (d *CloudDisk) GetEnableConfidentialCompute()` …
=> Remove support for GCE Alpha Disk Insert API

pkg/common/errors.go, pkg/common/utils_test.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-pd-csi-driver/controller.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
When CreateVolume is executed, the csi provisioner expects either "final" or "temporary" errors. If we report final error when disk creation could be ongoing or the disk is already created, then a PVC deletion before successful volume creation could lead to disk leakage as DeleteVolume won't happen.
To prevent disk leakage in PDCSI driver, we changed the error codes returned from GetDisk, InsertDisk, waitForZonalOp / waitForRegionalOp inside of CreateVolume to return …
=> Record original error code to operation_errors metric for temporary errors 

pkg/gce-pd-csi-driver/controller.go
Remove short variable declaration from validateStoragePools for correct error to be passed to RecordOperationErrorMetrics
>
/kind bug
> /kind design
> /kind flake
Remove short variable declaration from validateStoragePools for error to be passed to RecordOperationErrorMetrics. Right now, the scope for validateStoragePools is incorrect leading to us passing nil to RecordOperationErrorMetrics, which results in a [OK grpc status code](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob …
=> Remove short variable declaration from validateStoragePools

pkg/gce-pd-csi-driver/node.go
>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
Clean up the logging message in `isVolumePathMounted` func that is used by both NodePublishVolume and NodeStageVolume functions.
Fixes #
```release-note
NONE
```
=> Update isVolumePathMounted log message

pkg/deviceutils/device-utils.go, pkg/deviceutils/device-utils_linux.go, pkg/deviceutils/device-utils_windows.go, pkg/deviceutils/fake-device-utils.go, pkg/gce-pd-csi-driver/node.go, test/e2e/tests/single_zone_e2e_test.go
/kind bug
Summary: If a PD block device is still being used by the filesystem (misconfiguration, mount namespace capture), return an error during NodeUnstage.
Currently the PDCSI driver performs an unmount on the globalmount during NodeUnstage, and success signals that ControllerUnpublish (GCE disk detach) can proceed. Normally successful mount is an indicator that there is no other consumer of the device on the OS. There are some sitautions where this may not be true:
1) Mount Namespace Capture: If a mount namespace is held open by a container process, due to an open file descriptor to `/proc/<pid>/ns/mnt`, a private mount point to the block device may exist in a container's mount namespace. Typically this only occurs …
=> Add support for checking if a device is being used by a filesystem

test/e2e/tests/setup_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go, test/remote/instance.go, test/remote/setup-teardown.go, test/run-e2e-local.sh
Make e2e tests work from googler cloudtop instances. Note that service accounts that can download keys are still required.
```release-note
None
```
=> Fix e2e tests to run on cloudtop

pkg/deviceutils/device-utils_linux.go, pkg/gce-pd-csi-driver/node.go
/kind bug
The device disable call has been failing because a newline needed to be added to the "offline" state written to sysfs. But in testing that, we've discovered disabling devices can cause problems. From a comment that I've added into this PR:
> Once a device is disabled, it's unusable, and can't be enabled unless the serial number is known. But the serial number cannot be read from the device as it's disabled. If a device is disabled in NodeUnstage, and then NodeStage is called without a NodeUnpublish & publish sequence, the disabled state of the device will cause NodeStage to fail. So this can only be used if we track the serial numbers of disabled devices in a persisent way that survives driver restarts.
```release-note
Remove disable …
```
=> Remove device disable call

pkg/deviceutils/device-utils.go, pkg/deviceutils/device-utils_linux.go, pkg/gce-pd-csi-driver/node.go
The DisableDevice call is no longer used. The comment around the device explains why so that if we ever decide to put it back in we'll have context.
/assign @pwschuurman 
/kind cleanup
```release-note
None
```
=> Remove unused DisableDevice method

cmd/gce-pd-csi-driver/main.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, pkg/gce-pd-csi-driver/gce-pd-driver_test.go, test/e2e/utils/utils.go, test/sanity/sanity_test.go
/kind bug
The `disks.list` API is currently used in ListVolumes RPC. This looks up all disks within a project/region. The response includes a `items[].users[]` field, which contains the list of all VMs that are attached to a given disk. Thehe `items[].users[]` array has an implicit limit of 50 VMs. If a disk is attached to more than 50 instances, only 50 instances will be returned in `items[].users[]`. This causes problems with the [`external-attacher`](https://github.com/kubernetes-csi/external-attacher/blob/5f016e3d49b561d4e72375468684c6e19e56044a/pkg/controller/csi_handler.go#L134) reconciliation logic, since these disks appear to not be attached. When this occurs, the `external-attacher` will re-issue unnecessary …
=> Use instances.list to determine PublishedNodeIds in ListVolume API

Dockerfile, Makefile, cmd/gce-pd-csi-driver/main.go, deploy/kubernetes/base/node_linux/node.yaml, deploy/kubernetes/images/stable-master/image.yaml, pkg/common/constants.go, pkg/common/parameters.go, pkg/common/parameters_test.go, pkg/common/runcmd.go, pkg/common/utils.go, pkg/common/utils_test.go, pkg/gce-pd-csi-driver/cache.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, pkg/gce-pd-csi-driver/gce-pd-driver_test.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go, test/e2e/tests/multi_zone_e2e_test.go, test/e2e/tests/resize_e2e_test.go, test/e2e/tests/setup_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/utils/utils.go, test/k8s-integration/config/data-cache-sc.yaml, test/remote/client-wrappers.go, test/remote/instance.go, test/remote/setup-teardown.go, test/run-e2e-local.sh, test/sanity/sanity_test.go, vendor/k8s.io/mount-utils/mount_linux.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Adds feature to leverage Local SSDs as cache for persistent disks to reduce latency. It uses LVM as caching framework.
Fixes #
```release-note
Added feature to leverage Local SSDs as cache for persistent disks.
```
=> Add data caching feature with Local SSDs for PD

Dockerfile, cmd/gce-pd-csi-driver/main.go, pkg/common/utils.go, pkg/gce-pd-csi-driver/cache.go, test/e2e/utils/utils.go, test/run-e2e-local.sh
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Adds separate flag to controller data cache feature enablement for node and controller
Fixes #
```release-note
NONE
```
=> Add separate flags for node and controller and hash nodeId

pkg/gce-pd-csi-driver/controller.go
>
/kind bug
> /kind design
> /kind flake
Reassign error returned from validateStoragePools so InvalidArgument is recorded. Currently, since the error is not reassigned to have the InvalidArgumentCode, when `defer	gceCS.Metrics.RecordOperationErrorMetrics("CreateVolume", err, diskTypeForMetric, enableConfidentialCompute, enableStoragePools)` is executed, it passes an error that looks like fmt.Errorf("error") to `RecordOperationErrorMetrics`, which is technically an Internal error. 
I'm fixing this first for …
=> Reassign error returned from validateStoragePools so InvalidArgument is recorded

pkg/common/utils.go, pkg/common/utils_test.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Return Unavailable for 'connection reset by peer' errors.  Unavailable error code indicates that a CreateVolume operation might be in progress. https://github.com/kubernetes-csi/external-provisioner/blob/master/pkg/controller/controller.go#L1902
Fixes #
```release-note
Return Unavailable for 'connection reset by peer' errors.
```
=> Return Unavailable for 'connection reset by peer' errors

pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go
/kind cleanup
Improve error messages for ControllerExpandVolume / CreateSnapshot of multi-zone PV.
Before:
CreateSnapshot: "Failed to create snapshot: failed to take snapshot of the volume projects/psch-gke-dev/zones/multi-zone/disks/hdml-llama2-70b-hf: "rpc error: code = Unknown desc = CreateSnapshot, failed 
to getDisk: googleapi: Error 400: Invalid value for field 'zone': 'multi-zone'. Unknown zone., invalid""
ControllerExpandVolume: "resize volume "my-disk-pv" by resizer "pd.csi.storage.gke.io" failed: rpc error: code = Unknown desc = ControllerExpandVolume failed to resize disk: failed to get disk: googleapi: Error 400: In
valid value for field 'zone': 'multi-zone'. Unknown zone., invalid"
After:
CreateSnapshot: "Snapshots are not supported with the `multi-zone` PV volumeHandle …
=> Improve error messages for ControllerExpandVolume / CreateSnapshot of multi-zone PV.

pkg/common/utils.go, pkg/common/utils_test.go, test/e2e/tests/single_zone_e2e_test.go
>  
> /kind api-change  
/kind bug  
> /kind cleanup  
> /kind design  
> /kind documentation  
> /kind failing-test  
> /kind feature  
> /kind flake  
**What this PR does / why we need it**:  
A new way of wrapping errors was introduced in [compute engine API](https://cloud.google.com/compute/docs/reference/rest/v1) (eg. "cloud.service.Disks.Insert") where some of these errors are wrapped with an additional layer of googleapi.Error. This additional wrap does not contain the http error code in its error code field, but instead contains a default value of Unknown. This is problematic because one of the ways we extract errors is by checking …
=> Properly unwrap gce-compute error code.

test/run-k8s-integration-ci.sh
>
> /kind bug
> /kind design
> /kind flake
Prow tests are failing with two errors; 
go: errors parsing go.mod:
/home/prow/go/src/sigs.k8s.io/gcp-compute-persistent-disk-csi-driver/go.mod:3: invalid go version '1.22.0': must match format 1.23
/home/prow/go/src/sigs.k8s.io/gcp-compute-persistent-disk-csi-driver/go.mod:5: unknown directive: toolchain
I think this is because prow tests use 1.21, and we are declaring toolchain 1.22.2 meaning the tests need a golang version of 1.22.2 +. I think installing golang …
=> Install golang version inside  run-k8s-integration-ci.sh script run by prow tests 

cmd/gce-pd-csi-driver/main.go
/kind cleanup
1) Add an `enumConverter` interface to facilitate generic conversion of enum type flags.
2) Add a `parseCSVFlag` function to properly convert comma separated value flags. Currently if these flags are unset, the resulting list contains an a single element array with an empty string.
```release-note
Properly parse comma separated input flags to filter out empty strings
```
=> Improve enum and string list flag parse handling

Dockerfile
>
/kind bug
> /kind design
> /kind flake
Update debian base image to bookworm as all bullseye version are stale and does not contain the fix for CVE-2024-33600, CVE-2024-33602, CVE-2024-2961, CVE-2024-33601, CVE-2024-33599
Fixes #
```release-note
Update debian base image from bullseye to bookworm to fix CVE-2024-33600, CVE-2024-33602, CVE-2024-2961, CVE-2024-33601, CVE-2024-33599
```
=> Update debian image from bullseye to bookworm to fix CVEs

test/e2e/tests/multi_zone_e2e_test.go, test/e2e/tests/setup_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/utils/utils.go
/kind test
Add some improvements to the e2e test suite runner:
* Add a new flag `--extra-driver-flags` to the e2e test runner. This allows additional flags to be passed into the PDCSI driver during the e2e test. This is useful when locally testing a new feature that is hidden behind a feature flag, and the feature is not yet ready to be default enabled in the e2e test.
*  Refactor `testAttachAndMount` function in `multi_zone_e2e_test.go` to pass in a parameter struct of booleans. These parameters are used to control attach and mount characteristics. This disambiguates the ordering of attach/mount parameters (currently there are consecutive booleans passed in with this function call).
* Refactor `testAttachAndMount` to …
=> Improvements to e2e test suite runner

pkg/common/parameters.go, pkg/common/parameters_test.go, pkg/common/utils.go, pkg/common/utils_test.go, pkg/gce-cloud-provider/compute/cloud-disk.go, pkg/gce-cloud-provider/compute/cloud-disk_test.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce.go, pkg/gce-cloud-provider/compute/gce_test.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, test/e2e/tests/multi_zone_e2e_test.go, test/e2e/tests/setup_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/utils/utils.go
/kind feature
Add support for `multi-zone` volume handle provisioning. Volumes created with the `enable-multi-zone-provisioning: true` parameter will be created with multiple underlying disks, one per specified zone. The underlying volume returned will specify the keyword `multi-zone` in place of the `zone` field. See https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1616 for more details on the syntax.
1) If there are zones specified in the requisite topologies, one disk will be created per zone
2) If there are no zones specified in the requisite topologies, one disk will be created per zone in all zones in the driver's default region (where the particular disk type is supported).
Multi-zone …
=> Add support for "multi-zone" volume handle provisioning and deletion

Dockerfile
/kind bug
The command `/usr/bin/nvme` requires this shared library. This is used to validate `nvme` device symlinks. This library is required in Bookworm (after we migrated from Bullseye in #1694)
Validated by running `./hack/verify_docker_deps.h`
```release-note
Fixes NVMe support in NodeStage and NodePublish
```
=> Adding missing libgpg-error.so.0 required by nvme-cli

pkg/deviceutils/device-utils.go
/kind cleanup
Error message is currently being printed out as a byte array (%v). It should be printed out as a string (%s). This is done elsewhere `exec.CombinedOutput()` is parsed.
Current error message is formatted like:
```
couldn't get serial number for disk pvc-b161d218-87e9-4657-9339-a11ef1eb7a54 at device path /dev/nvme1n2: google_nvme_id failed for device "/dev/nvme1n2" with output [91 50 48 50 52 45 48 54 45 50 48 84 49 57 58 50 52 58 52 48 43 48 48 48 48 93 58 32 80 97 115 115 101 100 32 100 101 118 105 99 101 32 119 97 115 32 110 111 116 32 97 110 32 78 86 77 101 32 100 101 118 105 99 101 46 32 32 40 89 111 117 32 109 97 121 32 110 101 101 100 32 116 111 32 114 117 110 32 116 104 105 115 32 115 99 114 105 112 …
```
=> Format byte array error output from google_nvme_id as string

Dockerfile
/kind bug
This reverts the debian image version which was updated in #1738. #1738 introduced a regression due to a missing dependency, we will allow some soak for the fix in 1.30 before backporting.
Fixes #
```release-note
Updates the debian base image to `debian-base:bullseye-v1.4.3-gke.5` from `debian-base:bookworm-v1.0.3-gke.0`
```
=> Reverting the Dockerfile debian image from bookworm to bullseye due to regression

test/e2e/tests/setup_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/utils/utils.go, test/remote/instance.go, test/remote/runner.go, test/remote/setup-teardown.go, test/run-e2e-local.sh, test/run-e2e.sh
/kind cleanup
This adds support to run e2e tests in a configuration that uses NVMe devices. Currently the e2e tests default to using `n2` machine family, which uses SCSI by default. Passing in the `--enable-confidential-compute` flag is a cost effective way to use NVMe (an alternative being running against `c3-standard-4` machine type, but this requires additional test refactoring, or skipping tests, as there are restrictions on disk types).
To support toggling with just the binary flag, this also updates the defaults of the test to use `n2d` as well as a Ubuntu guest OS image instead of Debian.
Support for running "\[NVMe\]" tagged tests are presubmit will be added in https://github.com/kubernetes/test-infra/pull/32214. …
=> Add support for running tests on confidential VMs that use NVMe

Makefile, hack/verify-all.sh
/kind test
This validates that both production container images (amd64,arm64) have hermetic dependencies for all executables in their container images. It runs the `verify-docker-deps.sh` script as part of `verify-all.sh`, which is run in PDCSI github presubmit.
```release-note
NONE
```
=> Add verify-docker-deps.sh to verify-all.sh

pkg/gce-pd-csi-driver/cache.go, test/run-e2e.sh
/kind bug
This updates the RAIDing logic for Local SSD caching to exclude PDs from raiding. 
Fixes #
Validated Data cache E2E tests on c3-standard-22-lssd
```release-note
NONE
```
=> Update LSSD raiding logic to support NVME VMs

Dockerfile, test/e2e/tests/single_zone_e2e_test.go
>
/kind bug
> /kind design
> /kind flake
Copies missing dependency command to Docker
Also fixes e2e test change which mistakenly upgraded a test to hyperdisk 
Fixes #
```release-note
NONE
```
=> Add missing dependency

pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce-compute_test.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
We want to map OPERATION_CANCELED_BY_USER to Canceled and filter out Canceled from ControllerPublishVolumeLatency SLO. We can't filter out Aborted error codes because Aborted means an operation could be ongoing. 
Fixes #
```release-note
Change OPERATION_CANCELED_BY_USER to map to Canceled error code instead of Aborted.
```
=> Change OPERATION_CANCELED_BY_USER to Canceled instead of Aborted

pkg/deviceutils/device-utils.go, pkg/deviceutils/device-utils_linux.go, pkg/deviceutils/device-utils_windows.go, pkg/deviceutils/fake-device-utils.go, pkg/gce-pd-csi-driver/node.go, test/e2e/tests/single_zone_e2e_test.go
Cherry pick of #1658 on release-1.13.
#1658: Add support for checking if a device is being used by a
```release-note
Check if volume's block device is still in use during NodeUnstage
```
=> Automated cherry pick of #1658: Add support for checking if a device is being used by a

deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml, test/e2e/tests/setup_e2e_test.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Update stable rc master image to point to v1.14.2-rc1

docs/kubernetes/user-guides/storage-pools.md
>
> /kind bug
> /kind design
> /kind flake
Add manual deployment instructions for Storage Pools
Fixes #
```release-note
NONE
```
=> Add manual deployment instructions for Storage Pools

deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml, test/e2e/tests/single_zone_e2e_test.go, test/e2e/utils/utils.go, test/run-e2e.sh
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This PR adds ControllerModifyVolume E2E tests. This allows us to directly test the various APIs to check for any breaking changes in the future with the clients used.
Fixes #
```release-note
NONE
```
=> Add ControllerModifyVolume E2E tests

pkg/common/errors.go, pkg/common/utils.go, pkg/common/utils_test.go, test/e2e/tests/single_zone_e2e_test.go
Cherry pick of #1708 on release-1.12.
#1708: Properly unwrap gce-compute error code.
```release-note
Error codes extracted from errors part of compute engine api are now exposed with correct http errors instead of being classified as Unknown.
```
=> Automated cherry pick of #1708: Properly unwrap gce-compute error code.

deploy/kubernetes/overlays/prow-stable-sidecar-rc-master/driver-args.yaml, deploy/kubernetes/overlays/prow-stable-sidecar-rc-master/kustomization.yaml, docs/kubernetes/user-guides/volume-attributes-class.md, test/run-k8s-integration-ci.sh
>
/kind bug
> /kind design
> /kind flake
This PR fixes an issue where the CI tests do not have the feature gate for VolumeAttributesClass set. Additionally, duplicate definitions for --supports-dynamic-iops-provisioning and --supports-dynamic-throughput-provisioning are removed now that the command line arguments are default. ControllerModifyVolume has been replaced with VolumeAttributesClass in the user guide for clarity purposes.
Fixes #
**Special notes for your …
=> Enable VolumeAttributesClass feature gate for CI runs

pkg/deviceutils/device-utils.go, pkg/deviceutils/device-utils_linux.go, pkg/deviceutils/device-utils_windows.go, pkg/deviceutils/fake-device-utils.go, pkg/gce-pd-csi-driver/node.go, test/e2e/tests/single_zone_e2e_test.go
Cherry pick of #1658 on release-1.12.
#1658: Add support for checking if a device is being used by a filesystem
```release-note
Check if volume's block device is still in use during NodeUnstage
```
=> Automated cherry pick of #1658: Add support for checking if a device is being used by a filesystem

deploy/kubernetes/overlays/dev/driver-args.yaml, deploy/kubernetes/overlays/dev/kustomization.yaml, examples/kubernetes/demo-vol-create.yaml, pkg/common/parameters.go, pkg/common/parameters_test.go, pkg/gce-pd-csi-driver/controller_test.go, test/e2e/tests/single_zone_e2e_test.go, test/k8s-integration/config/hdb-volumeattributesclass.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This PR updates the logic to accept SI units for throughput for VolumeAttributesClasses. This makes the VACs consistent with SI being used in other areas, such as in StorageClasses. This also removes the duplicate definition of the command line arguments in the dev overlay.
Fixes #
```release-note
This feature changes VolumeAttributesClass, so …
```
=> Update logic to use SI for VACs

deploy/kubernetes/overlays/dev/driver-args.yaml, deploy/kubernetes/overlays/dev/kustomization.yaml, examples/kubernetes/demo-vol-create.yaml, pkg/common/parameters.go, pkg/common/parameters_test.go, pkg/gce-pd-csi-driver/controller_test.go, test/e2e/tests/single_zone_e2e_test.go, test/k8s-integration/config/hdb-volumeattributesclass.yaml
Reverts kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#1841
```release-note
NONE
```
=> Revert "Update logic to use SI for VACs"

Dockerfile, Makefile, hack/print-missing-deps.sh, hack/verify-docker-deps.sh
>
> /kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: Verify presubmit is currently failing (due to running on QEMU using target platform). This changes from using `ldd` on the target platform to using `readelf` on executables from the target image to validate dependencies exist in the base image.
Fixes #
```release-note
NONE
```
=> Update ./hack/verify-docker-deps.sh script to validate dependencies on build platform

hack/verify-all.sh
/kind cleanup
```release-note
None
```
=> Remove make from verify-all in order to reduce presubmit flakes

CHANGELOG/CHANGELOG-1.12.md, CHANGELOG/CHANGELOG-1.13.md, CHANGELOG/CHANGELOG-1.14.md, CHANGELOG/CHANGELOG-1.15.md
>
Fixes #
Updating change log to keep up with the releases.
```release-note
NONE
```
=> Update change log

cmd/gce-pd-csi-driver/main.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, pkg/gce-pd-csi-driver/gce-pd-driver_test.go, pkg/gce-pd-csi-driver/server.go, pkg/gce-pd-csi-driver/server_test.go, pkg/metrics/interceptor.go, pkg/metrics/metadata.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/metrics/metrics_test_util.go, test/sanity/sanity_test.go
Migrate metric defer() statements to gRPC metric interceptor. This allows for more accurate error code reporting of the internal `operation_errors` metric when gRPC handling functionality is refactored
> /kind bug
/kind cleanup
> /kind design
> /kind flake
**What this PR does / why we need it**: Currently the ControllerServer reports error metrics through a `defer()` function pattern. This captures the output of captured variables when the function returns. If captured references are not updated (eg: a statement is refactored, and the `err` variable is not updated), the error code reported may not be accurate. This can result in poor error classification when this metric is used for reporting (as all error codes …
=> Refactor metric defer() statements to gRPC metric interceptor

Dockerfile
>
/kind bug
> /kind design
> /kind flake
In our Dockerfile, we copy over some libraries from `gke.gcr.io/debian-base:bookworm-` to a `gcr.io/distroless/base-debian12` base. Currently this overwrites `libc.so.6`, which already exists in  `gcr.io/distroless/base-debian12`. This can lead to ABI incompatibilities between `ld-linux` (which is in base-debian) and the overwritten libc library. At the moment the ARM64 Docker image is broken when running applications that depend on `libc`. The following error can be …
=> Don't overwrite libc in distroless debian base image

examples/kubernetes/demo-vol-create.yaml, pkg/common/parameters.go, pkg/common/parameters_test.go, pkg/gce-pd-csi-driver/controller_test.go, test/e2e/tests/single_zone_e2e_test.go, test/k8s-integration/config/hdb-volumeattributesclass.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This PR updates the logic to accept SI units for throughput for VolumeAttributesClasses. This makes the VACs consistent with SI being used in other areas, such as in StorageClasses.
Fixes #
```release-note
This feature changes VolumeAttributesClass, so throughput specifications will need "Mi".
```
=> Require VACs to use SI units

test/run-k8s-integration.sh
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
The volume attribute class tests are valid for 1.31+ cluster By making the param configurable in the run-k8s-integration-*.sh we can disable the flag in k8s clusters lesser than intended minor version
We are seeing failures on clusters < 1.31 from the [code](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/test/k8s-integration/main.go#L817)
```
Failed to run integration test: runCSITests failed: VolumeAttributesClass file …
```
=> Make the volume attribute class file a configurable input in the tester script

test/k8s-integration/main.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
Skip xfs test for GCE test skip. We already do this for GKE, but not for GCE. The XFS test has been failing on the provider testgrid, which runs on GCE, for over 1 year. 
```release-note
NONE
```
=> Skip xfs test for GCE test skip 

pkg/deviceutils/device-utils.go
/kind bug
The current error message uses the wrong path. #1853 would have fixed it, but it was not submitted for some reason.
```release-note
Use correct tool path in udev error message.
```
=> Use correct path in error message for udev tooling

pkg/metrics/metrics.go, pkg/metrics/metrics_test_util.go
/kind bug
This fixes a regression introduced in #1876 where the driver would start panicking on startup if `--http-endpoint` was specified. This was caused by the metrics not being initialized anymore during startup. The proposed fix involves using the `Reset` methods of the metrics object instead of trying to redefine them each time they need to be reset.
Fixes #1894
Tested the PR by building an image and making sure it did not panic:
```
$ docker buildx build --platform "linux/amd64" --tag gcp-pd-csi-driver:test --build-arg=BUILDPLATFORM=linux --build-arg=STAGINGVERSION=v1.15.3 -f Dockerfile --load .
...
$ docker run -it gcp-pd-csi-driver:test --http-endpoint=localhost:8080
I1218 …
```
=> [metrics] Fix panic during metrics manager startup

test/k8s-integration/main.go
>
> /kind bug
> /kind design
> /kind flake
We now always set volume attributes class file after https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1889. This causes all VAC tests with GKE version < 1.31 to fail with `F0113 13:43:21.841754    8775 main.go:228] Failed to run integration test: runCSITests failed: VolumeAttributesClass file hdb-volumeattributesclass.yaml specified, but VolumeAttributesClass tests are skipped: \[Disruptive\]|\[Serial\]|VolumeAttributesClass|csi-gcepd-sc-x …
=> fix VAC tests now that VAC file is always set

pkg/gce-pd-csi-driver/node.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
EXPERIMENTAL COMMIT, DO NOT INCLUDE IN REGULAR RELEASE
```
=> experimental fix, remove deviceInUse check

test/e2e/tests/single_zone_e2e_test.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
DO NOT INCLUDE IN REGULAR RELEASE
```
=> [exp] remove e2e test for in use check, this is to make sure that the rest of the tests are running

test/k8s-integration/filter-junit.go, test/run-k8s-integration-ci.sh, test/run-k8s-integration-migration.sh, test/run-k8s-integration.sh
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
**What this PR does / why we need it**: Update `kubetest2` to a newer version for CI testgrid. This bumps kt2 to a version from December 16, 2024: https://github.com/kubernetes-sigs/kubetest2/commit/22d5b1410bef09ae679fa5813a5f0d196b6079de
Fixes #
```release-note
NONE
```
=> Update kubetest2 version

cmd/gce-pd-csi-driver/main.go, pkg/common/parameters.go, pkg/common/parameters_test.go, pkg/common/utils_test.go, pkg/gce-cloud-provider/compute/cloud-disk.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, pkg/gce-pd-csi-driver/gce-pd-driver_test.go, pkg/gce-pd-csi-driver/utils.go, pkg/gce-pd-csi-driver/utils_test.go, test/e2e/tests/multi_zone_e2e_test.go, test/e2e/tests/setup_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/utils/utils.go, test/run-e2e.sh, test/sanity/sanity_test.go
This PR adds support for the PDCSI driver to provision Hyperdisk-balanced High Availability (HdHA) disks. This allows users to use the latest generation of regional disks from GCE. The feature is gated behind flag `allow-hdha-provisioning`.
Fixes b/391964605
One potential gap I observe is that we have to return the raw GCE error if users call `ControllerPublishVolume` on a HdHA disk in read only mode, because we cannot determine the disk type without actually fetching the disk. I think this is mostly fine since the GCE error is pretty clear (" Error 400: The disk cannot be attached with READ_ONLY mode."), but please let me know if I …
=> Add support for HdHA disk provisioning

test/k8s-integration/filter-junit.go
>
/kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: Test runners that rely on parsing pdcsi_junit.xml are not working. This was changed in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1911 when the XMLName was removed for an output struct.
Fixes #
```release-note
NONE
```
=> Add XMLName back to TestSuite struct

test/k8s-integration/driver.go, test/k8s-integration/main.go
>
> /kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: The OSS Prow testgrid is currently failing, due to `kubectl` and other binaries not being found by `ginkgo`. This was a result of #1911 which updated the `kubetest2` version. In order to fix, the test binaries need to be copied to `_rundir/$KUBETEST2_RUN_ID`.
Fixes #
```release-note
NONE
```
=> Copy kubernetes test binaries to _rundir, instead of _artifacts when running integration test on k8s master branch

test/k8s-integration/config/test-config-template.in, test/k8s-integration/driver-config.go
>
> /kind bug
> /kind design
> /kind flake
Some VAC tests are failing because of 
```
{  [FAILED] While creating new VolumeAttributesClass: VolumeAttributesClass.storage.k8s.io "volume-modify-4528-e2e-vac-invalidvqcvs" is invalid: driverName: Invalid value: "csi-gcepd-sc-hdb--no-vsc--hdb-volumeattributesclass-volume-modify-4528": name part must be no more than 63 characters
```
This just removes VAC name from driver name
Fixes #
**Does this …
=> Remove VAC name from Driver name

deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml, deploy/kubernetes/images/stable-master/image.yaml, pkg/gce-cloud-provider/compute/gce-compute.go
/kind bug
If we use disks.CreateSnapshot, there could be a race condition where snapshot.Status is "READY" but the snapshot creation is not actually done. Snapshots.Insert API avoids this problem.
Fixes #
- snapshot.insert will try to grab resource lock too according to Xin.
- CMEK implicitly will be populated from PD if left blank, which keeps the previous behavior
```release-note
use `snapshots.insert` instead of `disks.createsnapshot` when creating pd snapshots.
pdcsi release including this change **MUST** upgrade csi-snapshotter sidecar to v7.0.0+.
```
=> switch to use snapshots.insert instead of disks.createsnapshot

Dockerfile, cmd/gce-pd-csi-driver/main.go, deploy/kubernetes/base/controller/cluster_setup.yaml, deploy/kubernetes/base/node_linux/node.yaml, initialize-driver.sh, pkg/common/constants.go, pkg/common/parameters.go, pkg/common/parameters_test.go, pkg/common/runcmd.go, pkg/common/utils.go, pkg/common/utils_test.go, pkg/deviceutils/device-utils.go, pkg/gce-pd-csi-driver/cache.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, pkg/gce-pd-csi-driver/gce-pd-driver_test.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go, test/e2e/tests/multi_zone_e2e_test.go, test/e2e/tests/resize_e2e_test.go, test/e2e/tests/setup_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/utils/utils.go, test/k8s-integration/config/data-cache-sc.yaml, test/remote/client-wrappers.go, test/remote/instance.go, test/remote/setup-teardown.go, test/run-e2e.sh, test/sanity/sanity_test.go
>
> /kind bug
> /kind design
> /kind flake
Adds the required support in PDCSI driver to setup caching for PVCs using local SSDs.
Fixes #
```release-note
NONE
```
=> Add support for data cache

pkg/common/constants.go, pkg/common/parameters.go, pkg/common/utils.go, pkg/gce-cloud-provider/compute/fake-gce.go, pkg/gce-cloud-provider/compute/gce-compute.go, pkg/gce-cloud-provider/compute/gce-compute_test.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, pkg/gce-pd-csi-driver/utils.go, pkg/gce-pd-csi-driver/utils_test.go, test/e2e/tests/multi_zone_e2e_test.go, vendor/google.golang.org/protobuf/internal/msgfmt/format.go, vendor/google.golang.org/protobuf/testing/protocmp/reflect.go, vendor/google.golang.org/protobuf/testing/protocmp/util.go, vendor/google.golang.org/protobuf/testing/protocmp/xform.go, vendor/modules.txt
>
> /kind bug
Previously https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1919 introduces multi-writer mode support for hyperdisks, but the access mode was derived through the parameters list. This is not the standard Kubernetes way of configuring access mode; rather we should derive it from the Volume Capabilities list in the CreateVolume request. This would confuse customers if they provide conflicting information in StorageClass vs PVC.
Fixes b/397726676. …
=> Derive access mode from the CreateVolume request instead of parameters

cmd/gce-pd-csi-driver/main.go, pkg/common/constants.go, pkg/common/runcmd.go, pkg/gce-pd-csi-driver/cache.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/node.go, test/e2e/tests/setup_e2e_test.go, test/e2e/utils/utils.go, test/remote/client-wrappers.go, test/remote/instance.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Update RAIDing logic to fetch requested local SSD count for Datacache from GKE node label, set up  RAIDing for Datacache with the corresponding local SSD number, and validate RAID-ing config afterwards.
Fixes #
```release-note
Update RAID logic and post-RAID validation to integrate Data Cache support for GKE nodes
```
=> Update RAID logic and post-RAID validation to integrate Datacache support for GKE nodes

deploy/kubernetes/base/controller/controller.yaml, pkg/common/parameters.go, pkg/common/utils.go, pkg/common/utils_test.go, pkg/gce-pd-csi-driver/cache.go, pkg/gce-pd-csi-driver/cache_test.go
>
/kind bug
> /kind design
> /kind flake
Data cache : Setting up caching would error out for large cache size as LVM has a limit on number of chunks that could be used, this PR fixes that issue by calculating dynamic cache size
Fixes #
Internal error, unreleased feature
```release-note
NONE
```
=> Fix chunksize bug for large cache size in data cache

cmd/gce-pd-csi-driver/main.go, pkg/gce-pd-csi-driver/cache.go
/kind bug
>
> /kind bug
> /kind design
> /kind flake
Adding additional check for data cache:
- Run Data Cache watcher on a node if it is a data cache node.
- check for VG existence during reduceVolumeGroup so that it doesn't run vgreduce and produce unactionable errors on the (pantheon) logs.
Fixes #
```release-note
Run Data Cache watcher on a node if it is a data cache node.
Check for VG …
```
=> Adding additional checks for data cache watcher and reduceVolumeGroup

pkg/gce-cloud-provider/compute/gce-compute.go, test/e2e/tests/multi_zone_e2e_test.go
> /kind bug
We found a bug during bugbash that performance parameters are not passed to `insertRegionalDisks`. I decided to consolidate the two variants of the function (`insertZonalDisks` and `insertRegionalDisks`), because they share almost the same logic except some non-applicable parameters (e.g. storage pool) and differences on the GCE interface. I believe that this will prevent future slips similar to this bug.
Fixes b/402880628
```release-note
NONE
```
=> Pass performance parameters when creating regional disks.

cmd/gce-pd-csi-driver/main.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Fix logic bug while checking available LSSDs for RAIDing for Data Cache
```
=> Fix logic bug while checking available LSSDs for RAIDing for Data Cache

cmd/gce-pd-csi-driver/main.go, pkg/gce-pd-csi-driver/cache.go, test/e2e/utils/utils.go
>
/kind bug
> /kind design
> /kind flake
Add exponential backoff retries for getting Node from API server logic in GetDataCacheCountFromNodeLabel(). After we exceed the retries and still cannot get the Node object, the error will be surfaced for a driver restart (instead of the current logic that allows NodeStageVolume to happen and another error to surface misleadingly).
This is needed since we may hit connectivity issue with API server during driver startup, causing the existing code to fail to get the …
=> Add exponential backoff retries for getting Node from API server logic

pkg/gce-pd-csi-driver/cache.go, pkg/gce-pd-csi-driver/node.go
>
/kind bug
> /kind design
> /kind flake
Map insufficient free space error during cache creating to InvalidArgument error. This helps avoid noise due to DataLoss error in case the machine doesn't have enough local SSDs space for the requested cache size.
Fixes #
```release-note
Map insufficient free space error during cache creating to InvalidArgument error
```
=> Map insufficient free space error during cache creating to InvalidArgument error

pkg/gce-pd-csi-driver/cache.go, pkg/gce-pd-csi-driver/cache_test.go, test/remote/client-wrappers.go
>
/kind bug
> /kind design
> /kind flake
Currently the cache size unit isn't passed along with the cache size causing conversion issues downstream
Fixes #
```release-note
Fix unit calculation bug for cache size setup
```
=> Fix units for cache size while calculating chunk size for LVM

Dockerfile, README.md
This change is enough to provision and run a btrfs filesystems.
Tested workflows:
[x] provisioning (formatting)
[x] disk expansion
/kind feature
Fixes #2000
Enables formatting new PVCs using `btrfs` filesystem.
Mount options like `compress=zstd` work as expected.
**Does this PR introduce a user-facing change?**: YES
```release-note
ubuntu-only: specifying `fsType: btrfs` in the PVC definition now formats & mounts a btrfs filesystem. btrfs support is experimental.
```
Non-btrfs users are not impacted by this change.
It is [not explicitly supported in GCP docs](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/gce-pd-csi-driver), and it does not have to be, at least in the interim. This PR allows users easily experiment with …
=> feat: enable btrfs

pkg/gce-cloud-provider/compute/gce-compute.go, test/e2e/tests/single_zone_e2e_test.go, test/remote/client-wrappers.go
/kind bug
Fixes memory leak in #2003, by breaking the loop when paginated results are complete.
Fixes #2003
```release-note
Fix infinite loop in ListSnapshots that can cause memory usage to grow unbounded
```
=> Add pageToken response check to ListSnapshots gRPC API

Makefile, test/k8s-integration/cluster.go, test/k8s-integration/driver.go, test/k8s-integration/main.go, test/run-windows-k8s-integration.sh
>
We need to support Windows 2022 nodes as well. This PR also makes the integration tests perform build for its platform only, instead of a multi-arch build. This will speed up the time to run the test.
This test will subsequently be enabled to run in CI in https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/gcp-compute-persistent-disk-csi-driver-windows.yaml. We will only need to change the WINDOWS_NODE_OS_DISTRIBUTION env var.
Fixes b/404487793. …
=> Make integration tests support windows 2022

deploy/kubernetes/base/controller/controller.yaml
This reduces the csi-snapshotter maximum retry interval to 60 seconds in the deployed overlay. The goal is to unblock presubmit testing and reduce testgrid failures.
Partially fixes #2016. This PR should be reverted once https://github.com/kubernetes-csi/external-snapshotter/issues/1282 is resolved, as this flag affects exponential backoff used when an error is encountered.
```release-note
NONE
```
=> Increase csi-snapshotter requeue interval --retry-interval-max=60s for deployed overlay

pkg/gce-pd-csi-driver/cache.go
>
/kind bug
> /kind design
> /kind flake
We saw outdated metadata errors with volume groupsduring concurrent  PVC detaching/provisioning operations with Guitar tests like the following, which ultimately caused an error during cache setup.
```
WARNING: ignoring metadata seqno 7 on /dev/sdb for seqno 9 on /dev/md127 for VG csi-vg-x84b7gt4   WARNING: Inconsistent metadata found for VG csi-vg-x84b7gt4   See vgck --updatemetadata to correct inconsistency   WARNING: outdated PV /dev/sdb seqno 7 has been removed in …
```
=> fix outdated metadata error in watcher

pkg/common/parameters.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, test/e2e/tests/multi_zone_e2e_test.go
This enables empty ROX multi-zone PVCs to be created, to allow for static hydration of disks
>
> /kind bug
> /kind design
/kind feature
> /kind flake
**What this PR does / why we need it**: Currently ROX multi-zone volumes can only be created from a volume source (eg: snapshot/disk image). This limits the flexibility of a user that wants to create a ROX multi-zone volume which is empty, and then write the same data individually to each created disk. This allows all disks to share the same name (as they are part of a "multi-zone" volume), but have data populated …
=> Relax volumeContentSource restriction for ROX multi-zone dynamic volume creation

test/k8s-integration/cluster.go, test/k8s-integration/main.go
>
> /kind bug
> /kind design
> /kind flake
Managed tests are seeing failures on the Extended channel due to the lack of the `--enable-autoupgrade` flag during cluster creation.
```release-note
None
```
=> Enable autoupgrade when creating extended channel GKE clusters in CI

pkg/gce-pd-csi-driver/cache.go, pkg/gce-pd-csi-driver/cache_test.go
>
/kind bug
> /kind design
> /kind flake
Updates the logic to calculate chunk size for data cache
Fixes #
```release-note
Updates the logic to calculate chunk size for data cache
```
=> update cache logic to calculate chunk size based on total cache

pkg/gce-pd-csi-driver/cache.go, pkg/gce-pd-csi-driver/cache_test.go
Cherry pick of #2037 on release-1.17.
#2037: update cache logic to calculate chunk size based on total
```release-note
Updates the logic to calculate chunk size for data cache
```
=> [release-1.17]Automated cherry pick of #2037: update cache logic to calculate chunk size based on total

test/run-k8s-integration-ci.sh
<**What type of PR is this?**
>
> /kind bug
> /kind design
> /kind flake
When running CI for the `extended` channel, we intended to specify both the release channel _and_ the version of the cluster.  However, the CI test script was choosing only one of the two depending on the setting of the release channel.
This PR adds a special case of for `extended`, where both the release channel and the cluster version are passed to the test automation.
```release-note
None
```
=> When using the extended channel, also specify the cluster version

test/k8s-integration/main.go
>
> /kind bug
> /kind design
> /kind flake
The `rwop` fsgroup tests [were added](https://github.com/kubernetes/kubernetes/pull/128244) only in k8s versions 1.32 and up.  Failures with node versions below that will not pass.
```release-note
None
```
=> Skip rwop fsgroup tests when node version is below 1.32

test/k8s-integration/main.go
>
> /kind bug
> /kind design
> /kind flake
Earlier #2045 did not also update the golang script, which had validation that needed an exception for extended channel.
```release-note
None
```
=> Add exception for dual-variable setting in utils.go for extended channel

pkg/common/constants.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go
/kind bug
Reserve 1 attachment for the root / OS disk when reporting nr. of attachable hyperdisks.
Fixes #1819
```release-note
Fixed reporting of attachment limits of hyperdisks + gen4 VMs - reserving 1 attachment for the OS disk.
```
=> Fix hyperdisk attach limits

pkg/common/utils.go, pkg/common/utils_test.go, pkg/gce-cloud-provider/compute/gce-compute.go
/kind bug
Currently resizing for Hyperdisk is failing for cases that require IOPS or throughput getting updated in the same resize call.
A [hyperdisk](https://cloud.google.com/compute/docs/disks/hyperdisks)-balanced with size 4Gi needs exactly 2000 IOPS, and 5Gi needs exactly 2500 IOPS. Disks 6Gi and more need a minimum of 3000 IOPS. When resizing a hyperdisk, there is a need to update IOPS as well. 
For hyperdisk-extreme the min IOPS value is 2 IOPS per GiB, if a 64 GiB hyperdisk-extreme disk with 128 IOPS is resized to 65 GiB, the IOPS also need to be updated to 130.
For hyperdisk-ml it is more complicated, min IOPS is 16 IOPS per MBps of provisioned throughput, min throughput is the …
=> Fix Hyperdisk Resize That Requires Iops/Throughput Adjustment

pkg/common/constants.go, pkg/common/utils.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go
/kind bug
Fixes #
Manual chery-pick of https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/2019 and https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/2057 because of conflicts.
```release-note
Add Attach Limit for Hyperdisk + Gen4 VMs
```
=> Add Attach Limit for Hyperdisk + Gen4 VMs

pkg/gce-pd-csi-driver/cache.go
/kind feature
>
> /kind bug
> /kind design
> /kind flake
remove no-op Watcher logs for GKE Data Cache in 1.17 release branch
Fixes #
```release-note
NONE
```
=> Remove no-op Watcher logs for GKE Data Cache in 1.17 release branch

pkg/gce-pd-csi-driver/cache.go
>
> /kind bug
> /kind design
> /kind flake
Remove no-op log statement in reduceVolumeGroup for release 1.18 branch.
Backport of:
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/2068
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/2070
Fixes #
```release-note
NONE
```
=> Remove no-op log statement in reduceVolumeGroup for release 1.18 branch.

pkg/common/constants.go, pkg/common/utils.go, pkg/common/utils_test.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go
/kind feature
For gen3 machines, we lower the attach limit to hyperdisk limit, so that workloads will not fail for attach limit exceeding errors. Users can override the value with node labels.
Fixes #
Tested on GCE clusters via adding logs in branch [attachLimitLocalTest](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/compare/master...sunnylovestiramisu:gcp-compute-persistent-disk-csi-driver:attachLimitLocalTest).
1. Start the cluster for a c3 machine
```NODE_SIZE="c3-standard-4" MASTER_SIZE="c3-standard-4" NODE_DISK_TYPE="hyperdisk-balanced" kubetest --up```
2. Deploy the driver
3. Check the initial attach limit(15), and …
=> Adjust Attach Limits for Gen3 Machines + Add Labels Override

CHANGELOG/CHANGELOG-1.17.md, CHANGELOG/CHANGELOG-1.18.md
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Brings changelogs up to date for 1.17 (10 releases were missed).  Creates a placeholder file for 1.18.  I could compile that one manually but I'm going to get one for free (I think) when I generate the v1.18.0 tag.  If not, I can come back and make it manually.
Fixes #
```release-note
None
```
=> Update 1.17 changelog based on Releases page, make placeholder 1.18

deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml, deploy/kubernetes/images/stable-master/image.yaml
>
Updates the image for external resizer to use the latest version, v1.13.0. This resolves tests failures related to the [verification of beta fields](https://github.com/kubernetes/kubernetes/commit/784c589a77a3fd67b1c1cd16bfccb4f2814bd6fe) not used in the previous version. 
Fixes #
```release-note
NONE
```
=> Upgrade to resizer to v1.13.0

README.md, cmd/gce-pd-csi-driver/main.go, pkg/gce-pd-csi-driver/gce-pd-driver.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go, pkg/gce-pd-csi-driver/utils.go
Add a sysfs knob `btrfs-allocation-{,meta}data-bg_reclaim_threshold`, which will do the equivalent of:
```
echo VALUE > /sys/fs/btrfs/FS-UUID/allocation/data/bg_reclaim_threshold
```
Or, in case of metadata, equivalently:
```
echo VALUE > /sys/fs/btrfs/FS-UUID/allocation/metadata/bg_reclaim_threshold
```
Where VALUE is a number between `0` and `99` inclusive.
Adding it as a "special" mount option, similarly to `read_ahead_kb`, as that's quite convenient.
Some resources about `bg_reclaim_threshold` and more broadly balancing of the btrfs filesystem:
- https://btrfs.readthedocs.io/en/latest/Administration.html#uuid-allocations-data-metadata-system
- https://web.git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=18bb8bbf13c1839b43c9e09e76d397b753989af2
- …
=> btrfs recalim on kernel v5.19+: use bg_reclaim_threshold

pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go
/kind bug
Custom VM naming does not follow the current string handling, it returns an error in NodeGetInfo and breaks customers.
Fixes #
```release-note
Fix Gen4 Custom VM Cases
```
=> Fix Gen4 Custom VM Cases

README.md, cmd/gce-pd-csi-driver/main.go, pkg/common/parameters.go, pkg/common/parameters_test.go, pkg/gce-pd-csi-driver/controller.go, pkg/gce-pd-csi-driver/controller_test.go, test/e2e/tests/single_zone_e2e_test.go, test/e2e/utils/utils.go
/kind feature
This PR makes the disk topology feature only add a disk support label to PV NodeAffinity _if_ a new StorageClass parameter is specified: `use-allowed-disk-topology: true`.
The benefit of this is that GKE can enable the `--disk-topology=true` flag without immediately changing PDCSI's behavior.  The feature becomes available, but not enabled.  Customers can then choose to enable the feature when they are ready, plus they gain the granularity of enabling it for specific disk products at a time.  Since most customers need this for Hyperdisk usage, that allows them to target the functionality to their use case.
I've manually tested this feature.  See the steps recorded …
=> Only add disk support topologies if StorageClass parameter is true

README.md, deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
/kind feature
Put 1.20.0 release into stable-master.
```release-note
NONE
```
=> Release 1.20 cut details for v1.20.0

pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go
/kind bug
For GCP Gen4 machine types, there are CPU dependent volume attach limits. This PR adds missing machine family c4d to this list of machine types. 
Fixes #
```release-note
NONE
```
=> Add c4d to gen4 attach limit list

cmd/gce-pd-csi-driver/main.go, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/utils.go, pkg/gce-pd-csi-driver/utils_test.go
>
/kind bug
We recently had an issue where data cache related watcher was running on non-data cache nodes as we were defaulting to `true` so updating the default values here to `false`
Fixes #
```release-note
Disabling data cache watcher by default if node details are not available.
```
=> default data cache enabled to false

cmd/gce-pd-csi-driver/main.go, pkg/gce-cloud-provider/compute/gce-compute.go, test/k8s-integration/main.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
**What this PR does / why we need it**: Replace Get operations with polling in gce-compute.go
Fixes #
**Does this PR introduce a user-facing change?**: NONE
```release-note
NONE
```
=> Replace Get operations with polling

pkg/gce-cloud-provider/compute/gce.go, pkg/gce-cloud-provider/compute/gce_test.go, pkg/gce-pd-csi-driver/controller.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Recently we were out of SLO for the PDCSI CreateSnapshot endpoint. After analysis of the errors contributing to our slo we have identified the issue to be an excessive amount of INTERNAL errors. Further analysis of these internal errors has brought to light two major types of errors that are being incorrectly tagged as internal. These should not be contributing to our slos, they are the following:
Already exists errors should be converted from INTERNAL to …
=> Added filtering for incorrect slo boosting logs

README.md, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/node_test.go, pkg/gce-pd-csi-driver/utils.go
Add a knob for the btrfs-specific `bdi/read_ahead_kb`. AFAIK this value is the upper limit of the btrfs read-ahead of the _underlying file_.
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Confusingly, this option is not related to `/sys/block/sdX/queue/read_ahead_kb`, which is what controls the read-ahead of the block device (regardless of what's in there). The current `read_ahead_kb` "special" mount option configures the value of the block device.
The default `bdi/read_ahead_kb` is 4MiB (on all the systems I've …
=> [btrfs] add btrfs-specific `bdi/read_ahead_kb`

cmd/gce-pd-csi-driver/main.go, deploy/kubernetes/images/stable-master/image.yaml, pkg/gce-pd-csi-driver/node.go, pkg/gce-pd-csi-driver/utils.go, pkg/gce-pd-csi-driver/utils_test.go
Cherry pick of #2112 on release-1.17.
#2112: dafult data cache enabled to false
```release-note
Disabling data cache watcher by default if node details are not available.
```
=> Automated cherry pick of #2112: dafult data cache enabled to false

pkg/gce-pd-csi-driver/cache.go, pkg/gce-pd-csi-driver/cache_test.go
/kind bug
The GKE Data Cache was exhibiting extreme tail latency on partially
cached volumes, performing significantly worse than non-cached volumes.
Initial investigation into LVM cache policies and `atime`-induced
write-back thrashing did not reveal the root cause.
A series of `fio` benchmarks comparing cached and uncached volumes
uncovered a bug where the LVM cache was being configured with a
massive 1 GB chunk size. This was traced to a failure in the
`fetchPvSizeGiB` function in `cache.go`. The `pvs` command syntax was
malformed, and a subsequent string parsing error on its empty output
caused the driver to fall back to the default `maxChunkSize` of 1 GB.
This 1 GB chunk size led to extreme "read and write …
=> Fix partial cache tail latency by correcting the cache chunk size calc

pkg/common/utils.go, pkg/common/utils_test.go
GCP now offers more than 10 regions in Europe. Update the regex accordingly.
/kind bug
This driver does not work in europe-west10, 11 and 12. Tested in europe-west-12 (Turin, Italy) and got:
```
Failed to create snapshot: failed to take snapshot of the volume projects/own-lab-462214/zones/europe-west12-a/disks/pvc-da12fb90-1832-4e6c-9187-24f4ab3f64d9: "rpc error: code = InvalidArgument desc = Invalid snapshot parameters: invalid location for snapshot: \"europe-west12\""
```
Fixes #
I need this please 🙏 This looks broken.
```release-note
NONE
```
=> pkg/common/utils.go: update regionalLocationFmt for Europe with 10+ regions
